sopt-makers/sopt-playground-frontend

components/common/ImageUploader/index.stories.tsx, components/common/ImageUploader/index.tsx, components/common/Input/index.tsx, components/common/Text/index.tsx, components/project/upload/LinkForm/LinkFormItem.tsx, components/project/upload/LinkForm/constants.ts, components/project/upload/LinkForm/index.tsx, components/project/upload/LinkForm/useLinkForm.ts, components/project/upload/MemberForm/useMemberForm.ts, components/project/upload/constants.ts, pages/project/upload/index.tsx, public/icons/icon-image.svg
- 링크 추가 폼 약간 버그가 있어서 확인중..
- 이미지 업로더 크롭해서 올린다면 어떻게 할지 디자이너에게 자문 구해서 아직 보류
- Input 아래에 에러메시지 추가 예정 `red100`
=> feat: 이미지 업로더, 링크 추가 폼 구현

api/project/index.ts, api/project/types.ts, components/common/ImageUploader/index.tsx, components/project/upload/MemberForm/index.tsx, pages/project/upload/index.tsx
=> feat: 이미지 업로드 api 인터페이스 수정 대응, 제출하기 버튼

.github/workflows/main.yml
✨ 구현 사항
- CloudFlare Pages에 자동으로 배포하는 Github Actions를 구축
=> chore: Cloudflare Pages 배포

api/index.ts, components/auth/AuthProvider.tsx, components/auth/accessToken.ts, components/auth/register/FinishRegister.tsx, pages/_app.tsx, pages/auth/cb/facebook/login.tsx, pages/auth/cb/facebook/register.tsx
- 로그인 시 Project API에 액세스 토큰 저장하는 로직 추가
- 사이트 접속시 로컬스토리지에서 액세스 토큰 로딩하는 로직 추가
=> feat: 액세스 토큰과 API 연결

components/common/Header/Menu.tsx, components/common/Header/index.tsx, components/projects/main/ProjectCard.tsx, pages/projects/index.stories.tsx, pages/projects/index.tsx, styles/reset.ts
- 메뉴에 잘못 들어간 스타일 수정
- a태그로 감싸야 하는 친구들 감싸기
- 등등..
=> fix: detail link 수정

.eslintrc.json
- close #
error로 두니 개발할때도 계속 빨간줄이 뜨는데, 이것까지 강제하는건 불편함이 따른다고 생각하여 `'warn'` 으로 변경합니다.
=> fix: no-unused-vars warning으로 변경

constants/Config.ts, hooks/useLocalLogin.ts, hooks/useMediaQuery.ts, next.config.js, styles/GlobalStyle.tsx, styles/font.ts, styles/global.ts, utils/index.ts, utils/layout.tsx
- close #93 
#93 에서 언급한대로 일부 디렉터리에 ESLint 명령이 적용되지 않던 현상을 수정했습니다.
`next.config.js` 파일에 `eslint` 옵션을 추가했습니다.
=> chore: ESLint 적용 범위 수정

.github/workflows/deploy-production.yml, .github/workflows/deploy.yml
- #102 
- Preview 빌드를 삭제했습니다.
- Cloudflare Pages 의 배포되는 프로젝트 이름을 Secret 변수화 시켰습니다.
- PR시에 배포되는 트리거를 삭제했습니다.
- projectName 필드에 Secret 변수가 들어가게 변경했습니다.
=> chore: Production 배포 스크립트 변경

.github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml
- close #102 
개발용 배포를 추가하고, 프로덕션 배포는 수동으로 눌러 줘야 되도록 변경했어요!
프로덕션으로 배포하려면 리포지토리의 Action탭의 Production Deploy 에서 진행할 수 있습니다!
적절한 워크플로 yml 수정..!
=> chore: 개발 버전 배포 추가

components/users/main/UserCard/index.tsx, components/users/main/UserRoleMenu/UserRoleDropdown.tsx, components/users/main/UserRoleMenu/UserRoleMenuItem.tsx, components/users/main/UserRoleMenu/index.tsx, pages/users/index.tsx, styles/typography.ts
- close #111 
- 멤버 프로필 메인 페이지 마크업 작업을 진행했어요
- 디쟈이너님이 사이즈 조정해주셔서(너무 커보였었음) 그것 반영했어요
- api 연결까지 하고 요청 드릴 예정입니당
https://user-images.githubusercontent.com/26808056/199508951-ab974cca-d413-43c2-bac4-de506e9956e1.mov
=> feat: 멤버 프로필 메인페이지 마크업

components/users/detail/PartItem.tsx, pages/auth/register.tsx, pages/members/[memberId]/index.tsx
- #118
main에서 발생하는 에러를 고쳐요
- import error인데, 삭제한 기존 api 코드를 불러오고 있는 것 같아 새 api 적용해서 고쳤어요
- 하는 김에 [no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars) warning도 고쳤어요
=> fix: import error fix

.github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml
- close #126 
어느 순간부터 배포 오류가 나는 것을 수정합니다.
원래 사용하던 cloudflare/pages-action 액션이 특정 커밋 메시지 상황에서 동작하지 않는 오류를 한참 구글링해서 찾아냈습니다...
직접 wrangler 명령어를 사용하고, `--commit-message " "` 로 메시지를 덮어씌우는 방식으로 해결했습니다.
=> chore: 배포 오류 수정

components/common/Header/index.tsx, pages/members/[memberId]/index.tsx, public/icons/icon-profile.svg
- close #133
- profile 이미지 관련 오류 해결
- ask to me 마크업
=> fix: ask to me 마크업, profile 이미지 관련 오류 해결

pages/members/index.tsx
- close #
- 멤버 메인페이지 하단에 마진을 주었구요,
- 버튼으로 랜딩되는 링크를 변경했어요
=> chore: 멤버 메인 페이지 링크 수정, 마진 추가

apiHooks/members.ts
[ea21fe4](https://github.com/sopt-makers/sopt-internal-frontend/pull/141/commits/ea21fe4e6e83524cf1246eb49b828243c4116124)를 적용하고 다시 id가 undefined일 때에 요청을 하고 있어서 급히 원래대로 돌렸습니다 ㅠ
일단 낼 무사히 끝나면 다시 보는걸로.......
=> fix: 의도대로 동작하지 않는 enabled 옵션 임시 fix

pages/auth/login.tsx, pages/members/detail.tsx
=> Ask to me 멘트 수정 및 회원가입 버튼 컬러 수정

components/members/main/MemberCard/index.stories.tsx, components/members/main/MemberCard/index.tsx
- close #이슈는 없당
- 멤버카드 소개 말줄임을 추가했어요
=> chore: 멤버카드 소개 말줄임 추가

components/common/MobileHeader/index.tsx
- close #없어용
- 모바일 헤더의 뒤로가기 기능이 누락되어있어서 추가했어요
=> chore: 모바일헤더 뒤로가기 추가

components/members/main/MemberCard/index.tsx
=> chore: active badge 수정, 이미지 비율 조정

components/common/TextArea/index.tsx, components/members/upload/AdditionalInfoFormSection.tsx, components/members/upload/forms/CountableTextArea.tsx
- close #161 
그냥.. 모바일 컴포넌트에 react hook form 연결을 빼먹어서 추가했습니다 ..........
ㅠ
넘 바보같은 실수인 것도 맞지만 모바일/데탑 컴포넌트를 따로 만들었을 때의 단점을 알게 되었다는 ..
=> fix: 모바일 뷰에서 한줄소개, 스킬 등록 안되는 버그 fix

api/index.ts, components/auth/states/accessTokenAtom.ts
- close #168 
로그인시 액세스 토큰이 제대로 적용되지 않던 버그를 수정했습니다.
- 액세스 토큰의 변경을 막고있던 axios instance의 기본값을 제거했습니다.
- Recoil Atom Effect에서 첫 로드시 axios instance의 헤더에 토큰을 제대로 넣도록 수정했습니다.
=> fix: 액세스 토큰 로드 버그 수정

pages/auth/login.tsx
- close #
- Internal -> Playground로 워딩 변경
=> chore: login 화면 문구 수정

pages/auth/callback/facebook/register.tsx
회원가입 성공시 잘못된 경로로 가는 것을 긴급 수정했습니다.
=> fix: 회원가입 성공 route 오류 해결

styles/global.ts
- close #164 
- select, input, textarea의 크롬 autofill 스타일을 프로젝트에 맞게 수정했어요
https://user-images.githubusercontent.com/26808056/202178616-24658143-e3bc-4821-965d-5ea01854c6ab.mov
=> chore: 크롬 자동완성 스타일 reset

components/auth/identityProvider/facebook/FacebookButton.tsx, pages/auth/login.tsx
- close #183 
- 로그인 화면 모바일 대응을 진행했어요
- 디자이너 없이 해서 조금 허접할 순 있지만 다른 뷰처럼 좌우패딩 20px, 버튼은 100%로 했어용
- 띄어쓰기랑 개행정도 수정했습니당
=> feat: 로그인 화면 모바일 대응

components/projects/upload/FormStatus/index.stories.tsx, components/projects/upload/FormStatus/index.tsx, components/projects/upload/constants.ts, components/projects/upload/schema.ts, components/projects/upload/types.ts, pages/projects/upload/index.tsx
- close #188
- `FormState`의 `isDirty` 상태를 함수로 받아서 각 필드별로 조건을 따로 지정해주었어요. 
- 별도로 `useArrayField`의 `append` 함수를 호출하면 이상하게 다른 필드의 `dirtyFields`가 수정되는 이슈가 있어서 `category`만 로직이 조금 다릅니다.(https://github.com/react-hook-form/react-hook-form/issues/4256)
- 스키마 및 상수를 다른 파일로 분리했어요
=> refactor: 프로젝트 FormState 검증 로직 개선

components/common/Header/index.tsx, components/makers/PersonBlock.tsx
- 푸터의 의견 제안하기 링크가 새 창으로 뜨지 않는 문제를 수정했습니다.
- 특정 상황에서 기본 프로필 이미지가 뜨지 않고 이미지가 깨져버리는 문제를 수정했습니다.
=> fix: 메이커스 소개 페이지 오류 수정

pages/_app.tsx
네.. 사소하지만 놀랍게도 없더라고요...
title 태그를 추가했어요.
=> fix: 타이틀 추가

components/common/Footer/index.tsx
푸터의 z-index 값이 낮아 다른게 위에 올라오는 현상을 수정했어요.
=> fix: 푸터 z-index 수정

components/auth/AuthRequired.tsx, pages/index.tsx
=> fix: member에 라우트가 갇히는 문제 해결

pages/index.tsx
=> fix: 메인 페이지 리다이렉트 수정

pages/members/detail.tsx
=> fix: 전공만 노출되는 버그 해결

components/members/main/MemberDetail/index.tsx
=> fix: 멤버 상세 프로필 텍스트 줄 넘어가는 버그 해결

components/members/main/MemberDetail/index.tsx
=> fix: 활동 기수 내림차순으로 보여주도록 수정

api/members/type.ts, components/users/detail/MemberProjectCard.tsx
=> fix: 프로필 내 프로젝트 목록에서 서비스타입 보여주도록

components/users/detail/MemberProjectCard.tsx
=> fix: 멤버 상세에서 프로젝트 카드 클릭하면 멤버 페이지로 이동하는 버그 해결

components/members/main/MemberDetail/CoffeeChatModal.tsx
- close #
- 커피챗 api가 응답속도가 느려서 버튼에 스피너를 추가했어요.
- 추후 버튼의 prop으로도 추가할게요!
=> refactor: 커피챗 로딩 추가

apiHooks/members.ts, components/members/main/MemberList/index.tsx
- close #
- window.location.search => router.asPath 로 변경했어요! 
- search 필터값을 쿼리키로 설정해야 하는데, csr시 읽어오는 `router.asPath`로 변경하였습니당
=> refactor: window.location.search => router.asPath로 쿼리키 변경

components/projects/upload/MemberForm/index.tsx
=> fix: 멤버 추가 오류 수정

components/projects/main/ProjectDetail.tsx
- close #
- 모바일뷰에서 프로젝트 상세쪽의 링크가 뜨지 않아 수정합니당
=> fix: 프로젝트 상세 링크 모바일 미노출 이슈 수정

components/makers/data/generation1.ts
=> chore: 만든사람들 누락된 멤버 추가

components/makers/MakersMembers.tsx
메이커스 소개 페이지에서 불필요한 전체 멤버 조회 쿼리를 삭제했어요.
=> fix: 불필요 API 요청 제거

components/members/upload/schema.ts
- close #370 
프로필 항목 중 optional 값들에 null이 들어올 수 있도록 스키마를 수정했어요
리뷰어는 해당 이슈 제보자로 선정되었습니다
=> fix: optional 항목에 null이 들어올 수 있도록 스키마 수정

components/common/Banner/RecruitingBanner/index.tsx, components/makers/AboutMakers.tsx, pages/makers/index.tsx
- close #407 
제목 그대로!
2기 모집 예정 박스는 2기 모집 끝나면 기수만 바꿔서 다시 그대로 넣어야 할 것 같아서 그냥 주석 처리 했습니다~
=> feat: 2기 모집 예정 박스를 모집 홍보 배너로 변경

components/common/Banner/RecruitingBanner/index.tsx
삼항 연산자를 if문으로 바꿨어요
이유
1. jsx retrun문 내에 두 번이나 나오는 삼항 연산자로 인해 가독성이 다소 떨어져 있었기 때문에
2. 굳이 묶여있을 필요 없던 모바일 컴포넌트와 데스크탑 컴포넌트를 구조상 분리하기 위해
=> refactor: RecruitingBanner 컴포넌트 가독성 개선

pages/members/upload.tsx
ㅜㅜ https://github.com/sopt-makers/sopt-playground-frontend/pull/384 변경 사항에서 생일 포맷하는 코드를 빠뜨렸어요
테스트가 부족했습니다 .. 반성합니다 ㅜㅜ
=> fix: 프로필 업로드 > 빠뜨렸던 생일 포맷 코드 추가

components/members/main/MemberDetail/index.tsx
- close #416 
제목이 곧 내용입니다
이번엔 테스트 정말 꼼꼼히 했어요 🥺
=> feat: 프로필 상세 > 생일/전공/지역 빈 값일 경우 라벨 숨기기

components/common/Banner/RecruitingBanner/contants.ts
=> chore: 모집 마감 시간 업데이트

.github/workflows/check.yml, README.md
=> chore: 2기 지원 정보 제거

.github/workflows/check.yml, .github/workflows/chromatic.yml, .github/workflows/deploy-development.yml
=> feat: merge queue 대응시키기

.github/workflows/check.yml, .github/workflows/deploy-development.yml, package.json, tsconfig.json, utils/test.test.ts
=> fix: actions/check.yml의 path filter 삭제

constants/generation.ts
- close #460
32기를 기준으로 동작하도록 변경했어요!
=> feat: 32기 지원 추가

.storybook/preview.js, components/common/Loading/index.tsx, pages/_app.tsx
- close #466
https://www.framer.com/motion/guide-reduce-bundle-size/ 을 참고해서 framer-motion 의 초기 번들 사이즈를 최적화했어요.
=> refactor: framer-motion 번들 사이즈 최적화

components/members/main/MemberList/MemberSearch.tsx, components/projects/upload/LinkForm/index.tsx, components/projects/upload/MemberForm/index.tsx
#461 에서의 변경으로 몇몇 Input의 스타일이 깨지는 문제를 수정했어요.
긴급하지만 중요하지는 않은 이슈라서, 리뷰 없이 머지할게요.
=> fix: Input 스타일 이탈 수정

pages/auth/callback/google/login.tsx, pages/auth/callback/google/register.tsx
구글 로그인이 안되고 있던 버그를 수정했어요!! 리뷰 없이 머지합니다.
=> fix: 구글 로그인 오류 수정

components/projects/form/ProjectForm.tsx, components/projects/form/fields/CategoryField.stories.tsx, components/projects/form/fields/CategoryField.tsx, components/projects/form/fields/GenerationField.tsx, components/projects/form/schema.ts
- close #
- CategoryField를 추가합니다. 완전 간단해용
=> feat: CategoryField 추가

components/auth/register/VerifyByEmail.tsx
이렇게 이메일 입력창이 이상하던 문제를
이렇게 해결했어요!
=> fix: 이메일 입력 인풋 크기 수정

api/members/index.ts, api/members/type.ts, components/members/common/WithMemberMetadata.tsx, components/members/main/MemberList/index.tsx, components/members/main/hooks/useMemberProfileQuery.ts
- close #479 
- api 인터페이스 변경점에 대응했어요!
- 주요 변경점은 `hasNext`가 추가되어서 다음 페이지가 있는지 여부를 확인하여 추가적인 api 요청을 막도록 개선했어요!
- 현재 pr은 멤버리스트만 작업되어있고, 프로젝트쪽 무한스크롤이 추가되면 요 방식을 그대로 적용할 예정입니다!
=> feat: 멤버 리스트 페이지네이션 api interface 변경 대응

playground-common/package.json
=> feat: playground-common 패키지 버전 업

components/members/common/select/Select.tsx
- close #
- 테스트를 위해 적용했던 옵션을 지우는걸 누락하여 수정합니다.
- 구두로 협의하여 머지합니당
=> chore: ScrollBar 보이는 조건 수정

.storybook/preview.js
스토리북의 기본 배경 색상이, 실제 서비스의 배경 색상과 일치하지 않는 문제를 수정했어요.
*AS-IS*
*TO-BE*
=> Fix: 스토리북 배경 색상 수정

components/makers/data/generation2.ts
=> fix: 잘못된 메이커스 멤버 정보 수정

components/members/detail/PartItem.tsx
- close #
- 배민 개발자님께서 누락한 사항을 수정해요.
**AS-IS**
**TO-BE**
=> feat: 파트 텍스트 누락 수정

components/members/upload/BasicFormSection.tsx, components/members/upload/schema.ts
- close #517 
옵셔널 항목이던 이메일을 필수 항목으로 변경했어요
UI를 변경하고, 스키마에 적용시켜서 유효성 검사에 반영되게 했어요
=> feat: 프로필 업로드 > 이메일 필수 항목으로 변경

components/common/Header/SwitchableHeader.tsx, components/makers/data/generation2.ts
- close #520 
**AS-IS**
**TO-BE**
=> feat: 메이커스 소개 모바일 헤더 디자인 수정

components/members/detail/PartItem.tsx
=> fix: 프로필 상세 > 누락된 텍스트 추가

components/members/main/MemberList/index.tsx
무한스크롤이 특정 환경에서 안되는 버그를 (아마) 수정해요!
=> fix: 무한스크롤 오류 수정

components/auth/callback/OAuthLoginCallback.tsx
로그인 오류시에 메시지가 제대로 뜨지 않는 버그를 수정했어요.
fetchStatus의 검증값을 fetching 으로 바꾸었어요.
=> fix: 로그인 오류 표시 수정

components/members/upload/AdditionalInfoFormSection.tsx, components/members/upload/BasicFormSection.tsx, components/members/upload/BasicFormSection/index.stories.tsx, components/members/upload/forms/CountableInput.tsx, components/members/upload/forms/CountableTextArea.tsx, pages/members/upload.tsx
- close #496 
- 활동 지역 ux writing 변경
- 학교/전공 분리
- 추가 정보 섹션에 있던 한줄 소개 옮겨온 뒤 ux writing 변경
=> feat: 프로필 업로드 > 기본 정보 섹션 디자인 변경 사항 반영

components/members/upload/TmiSection/FavorToggle.tsx, components/members/upload/TmiSection/MbtiToggle.tsx
- #508
누락됐던 hover 스타일을 추가했습니당
스토리북 members/upload/TmiSection
=> fix: TMI 섹션 > hover 스타일 추가

pages/auth/login.tsx
로그인 화면이 접속시에 들썩들썩 거리는 이슈를 수정했어요.
메이커스 로고 이미지의 높이를 명시적으로 지정했어요.
=> fix: 로그인 화면 레이아웃 시프트 수정

components/members/upload/schema.ts, components/members/upload/sections/TmiSection/index.stories.tsx
- close #546 
아직 항목이 추가되지 않았는데 폼 스키마를 수정해버려서 유효성 검사에서 걸려서 submit이 안됐었습니다
스키마에서 해당 항목 삭제하고 스토리북에서만 사용하도록 했습니다
=> fix: 프로필 업로드 안되는 버그 fix

components/members/upload/sections/TmiSection/MbtiSelector.tsx, components/members/upload/sections/TmiSection/MbtiToggle.tsx, components/members/upload/sections/TmiSection/constants.ts, components/members/upload/sections/TmiSection/index.tsx, components/members/upload/sections/TmiSection/types.ts
- close #531 
원래 리팩토링 하려고 했던 기술 부채였는데 !
생각보다 대출 기한이 짧았나봐요 ^^
이걸 안 하니까 TMI 섹션 submit & edit 구현에 큰 어려움이 있어서 나중에 하려다 지금 리팩토링 했습니다 ..
스토리북 members/upload/sections/TmiSection
=> refactor: MBTI 항목 폼 데이터 관리 방식 개선

api/members/type.ts, components/members/main/MemberDetail/index.tsx
=> chore: 프로필 상세 api 변경 사항 대응 (userFavor)

api/members/index.ts, api/members/type.ts, components/common/EditableSelect.tsx, components/members/upload/constants.ts, components/members/upload/format.ts, components/members/upload/schema.ts, components/members/upload/sections/TmiSection/index.tsx, components/members/upload/sections/TmiSection/types.ts, components/members/upload/utils.ts, pages/members/edit.tsx, pages/members/upload.tsx
- close #542
TmiSection 컴포넌트를 페이지 컴포넌트에 올리고
api 요청, 유효성 검사에 반영했어요
(오늘까지 배포 완료해야 해서) 정말 ... 오로지 빠른 완성을 위해 안티 패턴 많이많이 생성햇습니다 ..
꼭 빠른 시일 내에 해당 부채 갚을 것을 약속합니다
=> feat: TMI 섹션 프로필 업로드/수정 페이지에 추가하기

components/members/upload/sections/BasicFormSection/index.tsx
=> chore: 프로필 업로드 > 이름, 이메일, 전화번호 placeholder 추가

components/members/upload/AddableItem.tsx, components/members/upload/sections/CareerFormSection.tsx, components/members/upload/sections/SoptActivityFormSection.tsx
=> fix: 프로필 업로드 > AddableItem 첫번쨰 원소는 삭제할 수 없게 하기

components/members/main/MemberDetail/index.tsx, components/members/upload/constants.ts, pages/members/edit.tsx
=> hotfix: userFavor null 체크 및 기본값 설정

components/members/main/MemberDetail/InterestSection.tsx
=> fix: 프로필 상세 > 자유로운 자기소개 개행 되도록

components/members/upload/sections/CareerFormSection.tsx, components/members/upload/sections/SoptActivityFormSection.tsx, pages/members/edit.tsx
- close #571
- 첫 아이템 삭제할 수 있도록
- 수정 페이지에서 빈값인 경우 하나 띄워주도록
=> fix: 프로필 업로드 > AddableItem 사용성 개선

components/eventLogger/controllers/amplitude.ts
=> fix: Amplitude id 오류 수정

components/auth/register/verify/regex.ts, components/auth/register/verify/useByPhone.ts, components/auth/register/verify/view/ByPhoneView.tsx, components/members/upload/schema.ts, pages/auth/login.tsx
올바르지 않은 번호를 입력했을 때 에러 메시지가 뜨도록 수정했어요. 추가로 - 가 없는 번호도 허용하도록 수정했어요.
=> feat: 전화번호 인증 오류 추가

components/members/common/select/Select.tsx, components/members/main/MemberList/GenerationSelect.stories.tsx, components/members/main/MemberList/GenerationSelect.tsx, components/members/main/MemberList/MemberSearch.tsx, components/members/main/MemberList/index.tsx, components/members/upload/sections/TmiSection/index.tsx
=> fix: member List 수정

components/members/main/MemberList/index.tsx, components/members/main/hooks/useMemberProfileQuery.ts
- close #582 
- 새로고침시에 url의 query Param 을 읽어오지 못하는 문제를 수정합니다.
- useQuery가 router.query를 읽어오기 이전에 데이터 패칭을 수행해서 생기는 문제로 확인되어, enabled 조건을 추가합니다.
- 쿼리키를 router.asPath => router.query 로 변경합니다.
=> fix: 멤버 리스트 패칭 동작 오류 수정

components/eventLogger/events.ts, components/members/main/MemberList/index.tsx
파트별 필터와 기수필터에 Amplitude 이벤트를 추가했어요.
=> feat: 기수필터 Amplitude 추가

components/members/main/MemberDetail/InterestSection.tsx, components/members/main/MemberDetail/index.tsx
- close #591
userFavor null인 경우 처리
userFavor 관련한 null 처리를 안 해줘서 프로덕션에서 발견한 에러만 벌써 3-4번째인 것 같네여
얼른 타입 정리 작업을 해야 할 것 같습니다 ..
하지만 userFavor 관련해서는 이제 안 터질 거예요 ..
=> hotfix: 프로필 상세 > userFavor 모두 빈 값인 경우 의도치 않은 값이 보여지는 버그 fix

pages/members/edit.tsx
- close #
- edit 페이지를 누락했네요..ㅎㅎ 추가했습니당
=> feat: 폼 아코디언 수정페이지에도 추가

pages/members/upload.tsx
- close #
제곧내 입니다 ..
업로드에 버그가 좀 있었을 것 같네요ㅠ
=> hotfix: 프로필 업로드 > 수정 페이지와 submit 로직 통일

components/members/main/MemberDetail/index.tsx
- close #607 
SOPT 활동 정보가 정렬되지 않던 문제를 수정했어요.
=> fix: 활동 정보 정렬

pages/members/index.tsx, pages/projects/index.tsx
- close #619 
스터디 모집 배너를 제거했어요
삭제 버튼을 눌렀답니다?
나중에 또 사용될것 같아서 컴포넌트는 냅뒀어요!
=> feat: 스터디 모집 배너 제거

components/eventLogger/controllers/amplitude.ts, components/eventLogger/controllers/consoleLog.ts, components/eventLogger/controllers/storybookAction.ts, components/eventLogger/events.ts, components/eventLogger/hooks/useEventLogger.ts, components/eventLogger/types.ts, components/members/main/MemberDetail/index.tsx, components/members/main/MemberList/index.tsx, hooks/useRunOnce.ts
- close #617 
- 페이지 뷰에 대한 부분을 추가했어요.
- 일단은 요청이 들어온 멤버쪽만 추가했어요!
=> feat: amplitude pageview 추가

api/auth/index.ts, components/auth/register/verify/Verify.tsx, components/auth/register/verify/useByPhone.ts
- close #625
iOS 심사용 플로우 대응을 완료했어요.
=> feat: iOS 심사용 루트 추가

components/members/upload/FormSection/PublicQuestion.tsx
=> chore: 프로필 업로드 > 공홈 공개 관련 텍스트 수정

components/common/EditableSelect.stories.tsx, components/common/EditableSelect.tsx, components/members/upload/FormSection/Career.tsx
- close #616
- 멤버 업로드 쪽 디자인이 깨지는 문제를 수정했어요.
- 약간 주먹구구로 맞춘 감이 없지않아 있는데요, 어차피 New Select로 변경이 필요하여 이렇게 대응했어요.
https://user-images.githubusercontent.com/26808056/230900997-33b251b3-521d-4a0a-b301-7e34b18699ca.mov
=> fix: 멤버 업로드 > EditableSelect 스타일 수정, 스토리 추가

components/auth/oauth/OAuthCallback.tsx, components/auth/oauth/whitelists.ts
iOS 에서 딥링크로 redirect가 제대로 되지 않는 현상을 수정해요.
=> fix: iOS 딥링크 오류 수정

components/auth/oauth/OAuthCallback.tsx
=> feat: oauth 자세한 오류 메시지 추가

components/common/Banner/SOPTEventBanner/constants.ts, components/common/Banner/SOPTEventBanner/index.tsx
- close #638 
배너 링크에 target="_blank" 가 남아있는었지 뭐에요??? 그래서 삭제했답니다.
삭제한김에 Link 도 행사 링크로 바꿔주었어요
=> fix: target='_blank' 제거

components/auth/oauth/OAuthCallback.tsx
아이폰 사파리에서 `/auth/oauth` 엔드포인트가 제대로 동작하지 않던 문제를 수정해요.
=> fix: 아이폰 사파리 인증 오류 대응

components/auth/oauth/OAuthCallback.tsx
iOS 에서 딥링크가 제대로 작동하지 않는 문제를 해결하기 위해 동작 방식을 변경했어요.
=> feat: 인증 후 딥링크 동작 방식 변경

styles/global.ts
=> chore: 글로벌 스타일 button 태그에 cursor: pointer; 추가

pages/members/index.tsx, pages/projects/index.tsx
- close #645 
배너 철거했어요!
잘 사용하고 반납합니다 !
=> feat: 1차행사 모집 배너 철거

components/members/detail/MessageSection/MessageModal.stories.tsx, components/members/detail/MessageSection/MessageModal.tsx, components/members/detail/MessageSection/index.tsx
- close #637 
pm들이랑 상의해서 `커피챗`과 `쪽지`로 혼용되던 용어를 통일하고 쪽지를 Message로 명명했어요
커피챗모달만 변경하면 돼서 바꿈
=> refactor: 쪽지를 Message로 네이밍 통일

components/members/detail/CareerSection/index.tsx, components/members/detail/MemberDetail.tsx
API 타입과 컴포넌트 타입 분리를 안 해서 생기는 실수 중 하나 ㅜ
=> fix: 누락된 null 체크

components/members/main/MemberCard/index.stories.tsx, components/members/main/MemberCard/index.tsx, components/members/main/MemberList/index.tsx
- 모바일에서 카드간 가로선 색상을 수정했어요.
- 소속이 길때 레이아웃이 깨지는 문제를 해결했어요.
- 애니메이션에 문제가 많아서, 일단 간단한 방식으로 변경했어요.
- 모바일에서 활동 정보 오른쪽에 흰색이 남는 현상을 수정했어요.
=> fix: 멤버 카드 오류 수정

components/members/upload/schema.ts
- close #676
바뀐 타입 관리 방식에 맞추어 스키마 변경
저번에 타입 수정하고 실수했네용 ..
프로필도 스키마에서 타입 infer 해서 RHF에 넣어줘야겠습니다 ㅠ
=> fix: 프로필 업로드 > 커리어 validate 버그 fix

components/projects/form/ProjectForm.tsx, components/projects/form/fields/ServiceTypeField.stories.tsx, components/projects/form/fields/ServiceTypeField.tsx, components/projects/form/schema.ts
- close #
- `serviceType` 필드를 새로운 방식으로 리팩토링 하여 추가합니다.
=> refactor: 프로젝트 업로드 > 서비스 타입 필드 추가

components/common/Switch/index.tsx, components/projects/form/ProjectForm.tsx, components/projects/form/fields/StatusField.stories.tsx, components/projects/form/fields/StatusField.tsx, components/projects/form/schema.ts
- close #
- 프로젝트 현재 상태에 대한 폼을 추가합니다.
- 기존 SwitchProps가 타입을 잘못 extends 하고 있더라구요,, 그래서 이것도 함께 수정했습니다.
=> refactor: 프로젝트 업로드 > 프로젝트 현재 상태

components/projects/form/ProjectForm.tsx, components/projects/form/constants.ts, components/projects/form/fields/LinkField.stories.tsx, components/projects/form/fields/LinkField.tsx, components/projects/form/fields/MemberField.stories.tsx, components/projects/form/schema.ts
- close #
- 멤버쪽과 거의 비슷한 방식으로 LinkField 를 추가했어요.
- 그래서 사실 설명에 딱히 적을 내용은 크게 없숩니다.. 이제 슬슬 끝이 보인다,,
https://user-images.githubusercontent.com/26808056/235700444-93414fc9-257c-4ffa-91e7-0c191ff8aad0.mov
=> refactor: 프로젝트 업로드 > LinkField 추가

components/members/main/MemberList/index.tsx
- close #682 
모바일 뷰에서 멤버 프로필 간 간격이 이상해지는 문제를 해결했어요.
=> fix: 모바일 멤버 카드 간격 수정

components/members/main/MemberCard/MessageButton.tsx, components/members/main/MemberCard/index.tsx
- close #684 
멤버 카드에 마우스 올렸을 때 호버 스타일을 수정했어요.
=> feat: 멤버 카드 호버 스타일 수정

components/members/detail/CareerSection/CareerItem.tsx, components/members/detail/CareerSection/index.tsx
- close #661
모바일 뷰에서는 직무와 날짜가 다른 줄이 되도록 변경했어요~
데스크탑 뷰 line-height도 변경 사항 있길래 적용했습니당
=> feat: 프로필 상세 > 커리어 디자인 변경 반영

components/common/Banner/SOPTKATONBanner/DesktopEventBanner.tsx, components/common/Banner/SOPTKATONBanner/MobileEventBanner.tsx, components/common/Banner/SOPTKATONBanner/constants.ts, components/common/Banner/SOPTKATONBanner/index.tsx, pages/members/index.tsx, pages/projects/index.tsx
=> feat: SOPTKATON 배너 제작

pages/projects/[id].tsx, pages/projects/index.tsx
- close #692 
- 체리피킹되고 사용되지 않는 lodash api를 제거했어요
- @na-reum 형님이 제보해주셨슴다
=> chore: 체리피킹 되고 사용되지 않는 lodash api 제거

components/members/main/MemberList/index.tsx
- close #
- grid layout을 개선했어요! (원래 디자인이 없었어서 제 임의로 하느라 있던 드러운 코드들을 없애서 행복해요..)
- 현재 `MOBILE_MEDIA_QUERY`, `DESKTOP_MEDIA_QUERY` 두 가지만 존재하는데요, 해당 뷰에서만 브레이크 포인트가 여러개 존재하여 해당 페이지에서 변수를 만들어 사용했어요. (혹시 다른 파일로 빼는게 좋을까요?)
- `MemberRole` 컴포넌트가 새로운 필터로 대체될 예정이라 제거했는데, 다음 PR에서 지우는걸 혹시나 까먹을까봐 import 구문엔 놔뒀습니당..ㅎㅎ
https://user-images.githubusercontent.com/26808056/236666475-fd0d885f-e33c-4e31-96d4-27f059966f75.mov
=> feat: MemberList grid layout 개선

components/common/Banner/ActiveBannerSlot.tsx
=> feat: SOPTMATE 배너 제거

api/endpoint_LEGACY/projects/type.ts, components/projects/main/ProjectDetail.tsx, components/projects/upload/MemberForm/constants.ts
- close #706 
- 아래와 같이 라벨링만 변경했어요.
=> feat: 프로젝트 멤버 역할 명시적으로 변경

next.config.js
- close #712 
- Next.js experimental 기능인 스크롤 복원 옵션을 켜서 해당 기능을 추가합니다.
- 저번에 테스트할땐 안됐었던 것 같은데, 지금 다시 해보니 동작하더라구요
https://github.com/sopt-makers/sopt-playground-frontend/assets/26808056/6b686319-147d-4e8c-80e2-2e463ae59cce
=> feat: 스크롤 복원기능 추가

components/members/main/MemberList/index.tsx, pages/members/index.tsx
- close #
- 무한스크롤 오류 및 미 반영된 스타일이 있어서 수정했습니다.
- 핫픽스라 바로 나가볼게유
=> fix: 무한스크롤 오류 수정, 스타일 수정

components/members/main/MemberList/filters/MemberListFilterSheet.tsx
- close #
- https://github.com/Temzasse/react-modal-sheet/blob/master/example/components/Scrollable.tsx
- 위의 코드를 참고했어요! Content 내부에 스크롤되는 wrapper를 따로 만들어줘야 하더라구요
=> fix: 모바일에서 바텀싯 스크롤되지 않는 문제 수정

components/common/Modal/index.tsx, components/members/detail/MessageSection/MessageModal.tsx
=> fix: 쪽지 모달 모바일 반응형 임시 대응

components/mentoring/data/production.ts
=> chore: 멘토링 데이터 수정

components/members/detail/MessageSection/MessageModal.tsx
- close #753 
서버 스펙에 맞추어 쪽지 모달 컨텐츠가 750자가 넘으면 전송이 되지 않게 했어요
=> feat: 쪽지 모달 컨텐츠 글자 수 제한하기

components/members/detail/MessageSection/MessageModal.tsx
=> hotfix: 쪽지 모달 컨텐츠 길이 제한 버그 fix

components/mentoring/MentoringList/index.tsx
=> fix: 멘토링 리스트 스타일 수정

api/endpoint_LEGACY/hooks/members.ts, api/endpoint_LEGACY/members/index.ts, api/endpoint_LEGACY/members/type.ts, components/members/detail/MessageSection/MessageModal.tsx
- close #775 
쪽지 모달 > 카테고리 멘토링일 때의 placeholder 변경
=> feat: 쪽지 모달 > 카테고리 멘토링일 때의 placeholder 변경

components/eventLogger/events.ts, components/mentoring/MentoringList/index.tsx, constants/links.ts
- close #776
- 멘토 신청 버튼 추가
- 버튼에 Amplitude 클릭 이벤트 등록
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/5a4c44a5-78ec-4508-a6d2-10ba928ededb
=> feat: 멘토링 리스트 > 멘토 신청 버튼 추가

components/members/upload/forms/Form.tsx
- close #782
간단한 디자인 변경 사항이라 빠르게 머지하고 다음 작업하겠습니다!
=> feat: 프로필 업로드/수정 페이지 > submit 버튼 디자인 변경 반영

components/common/Banner/AppJamBanner/AppJamBanner.tsx
- close #
- 모바일 배너 '기획 자료를 공개' => '기획 자료 공개' 로 수정합니다.
=> fix: AppJamBanner 오타 수정

components/common/Banner/ActiveBannerSlot.tsx
=> chore: 앱잼 기획경선 배너 제거

components/mentoring/data/production.ts
=> chore: 멘토링 데이터 변경

components/mentoring/MentoringDetail/index.tsx
=> chore: disable 버튼 cursor default로 바꾸기

components/wordchain/WordchainChatting/WordChatMessage/index.tsx, components/wordchain/WordchainChatting/index.tsx
- close #816 
- 끝말잇기 최초 로드 및 업데이트 시 스크롤 최하단으로 이동
- 빠뜨린 스타일링 하나 추가
- 자잘 리팩토링 (0c6940a8634cea7bd55c5a48fb9ba8ae869bc686, a4e1b0a77dedf85dabc3b15494ee2fc1a5a8a0ab)
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/3bf0aadd-afc1-4745-9c90-bb76f5a2c0b4
=> feat: 끝말잇기 최초 로드 및 업데이트 시 스크롤 최하단으로 이동

api/endpoint/wordchain/newGame.ts, components/common/Modal/Confirm.tsx, components/members/detail/MessageSection/MessageModal.tsx, components/members/detail/MessageSection/Modal.tsx, components/wordchain/WordchainChatting/Wordchain/index.tsx
- close #
- 새 게임 시작하기 기능을 추가했어요. api 연결도 했으나 아직 정상 동작은 하지 않아요(서버 이슈)
- 커피챗 모달 모바일 버전을 대응하기 위해 공통의 모달을 수정한 이력이 있어서, 사이드 이펙트가 발생하고 있었어요.
- 사이드 이펙트가 전파되지 않도록 커피챗 모달쪽에 모달을 복사해서 생성해서 문제를 임시조치 했어요.
=> feat: 끝말잇기 새 게임 시작하기

components/mentoring/MentoringDetail/InfoItem.tsx
- close #829
gap 값을 잘못 설정해놓았던 것을 수정했어요!
=> fix: 멘토링 상세 페이지 > 스타일 수정

api/endpoint/wordchain/postWord.ts, components/wordchain/WordchainChatting/Wordchain/index.tsx, components/wordchain/WordchainChatting/index.tsx
- close #818 
- 단어 생성 에러 처리 구현 => 에러 response 올 시 에러 메시지가 담긴 에러 UI 2초 동안 보여주기
- 에러 상태 관리
- useMutation onError 메소드를 통해 에러 상태를 제어했어요
- 에러 토스트
- 기존 디자인의 삼각형이 메시지 박스와 겹쳐 애니메이션 과정에서 아래와 같이 보이는 현상이 있어 삼각형 크기를 임의로 조정했어요 (동영상 참고해주세요, 디자이너에게 피드백 받겠습니당)
동영상 촬영 시점 기준 서버 에러 처리 로직에 문제가 있어 에러 메시지가 적절치 않은 점 참고해주세요
UI와 에러 메시지를 잘 가져오는지 여부만 확인해주시면 됩니다!
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/66b2daab-d7c3-47ed-8b5b-2ed9eeb5f39f
=> feat: 끝말잇기 채팅 단어 생성 에러 처리 구현

components/sopticle/Success.tsx
이전 PR에서 누락된 솝티클 링크 수정사항을 반영했어요.
=> fix: 솝티클 링크 수정

api/endpoint/wordchain/getWordchain.ts, components/wordchain/WordchainChatting/index.tsx
- close #815
useInfiniteQueries와 @juno7803 가 만들어둔 useIntersectionObserver를 활용해서 무한 스크롤을 구현했어요
역방향 무한스크롤이라 옵저버 타겟(빈 공백 div)의 위치를 어떻게 해야 할지 고민했는데 아래와 같은 방법으로 풀어냈어요
(스크롤의 시작 위치를 살짝 위로 하면 된다 이런 의견도 있었는데 너무 까다로워서 이 방법으로 했습니다)
스크롤을 내리는 과정에서 잠깐 여백이 보이는 것은 괜찮으니 타겟을 넣어뒀어요
그러나 다음 페이지가 없을 때에는 쓸데 없는 여백이 항시 보이게 되기 때문에 `hasNext`로 타겟의 display를 조절했어요
아래 개선해야 할 사항이 있는데 작업 분리하는 게 나을 것 같아서 일단 올립니다
1. 새 페이지 fetch 시 스크롤 위치가 변하지 않아서 사용자가 갑자기 새 페이지의 가장 처음 데이터를 보게 돼요
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/1eae7396-9b07-423b-9625-a8da8a92243a
2. useInfiniteQueries select에서 데이터를 잘 가공해보려고 했는데 결과적으로 맥락을 알아야만 하는 코드가 됐어요 (pages의 첫 원소에 데이터를 다 몰아넣어 버림ㅠ ㅋㅋ)
그런데 데이터 가공에 있어 다른 문제도 있어 어차피 데이터 가공 전반으로 리팩토링을 하려던 예정이었어요 그때 이 부분도 해결될 수 있도록 하겠습니다
=> feat: 끝말잇기 채팅 무한 스크롤 구현

api/endpoint/wordchain/getWordchain.ts, components/wordchain/WordchainChatting/Wordchain/index.tsx
- close #827 
- close #838 
마크업 할 때 임의로 하드 코딩 해놨던 데이터 중 api 연결 후에도 수정하지 않은 것들이 있었습니다
첫 단어 뽑아내는 로직에 사소한 실수도 있어서 같이 수정했습니다~!
=> fix: 끝말잇기 채팅 > 우승한 게임 순서, 첫 단어 서버 response 반영

api/endpoint/wordchain/getWordchain.ts
- close #848
api 변경 사항에 맞추어 끝말잇기 채팅 GET api의 cursor 계산 방식을 지난 페이지의 마지막 끝말잇기의 id를 넘겨주는 방식으로 변경했어요
머지는 유진이랑 맞춰서 하겠습니다!
=> chore: 끝말잇기 채팅 GET api cursor 계산 방식 변경

components/wordchain/WordchainChatting/index.tsx, pages/members/index.tsx, pages/wordchain/index.tsx
- close #
- 메인에서의 진입점을 제거했어요
- 페이지 접근 시 모바일은 지원하지 않는다는 메시지를 볼 수 있도록 했어요
=> feat: 끝말잇기 모바일에서는 지원하지 않도록 하기 (임시)

components/wordchain/WordchainChatting/index.tsx, pages/members/index.tsx, pages/wordchain/index.tsx
- close #
1. 새 게임 시작했을 때
2. 페이지 최초 진입 시
위 두 경우에 스크롤이 최하단이어야 하는데 그렇지 않아서 반영했습니다
2는 useLayoutEffect로 해결이 됐는데 1은 안돼서 setTimeout으로 시간 간격을 좀 주었어요
안정적인 방법은 아니라 생각하는데 일단 빠른 배포를 위해 이렇게 올린 뒤 추후에 개선해보겠습니다
=> fix: 끝말잇기 채팅 스크롤 최하단으로 이동시켜야 하는 경우 대응

components/wordchain/WordchainChatting/Wordchain/index.tsx, components/wordchain/WordchainChatting/index.tsx, pages/members/index.tsx, pages/wordchain/index.tsx
=> feat: 추가된 단어가 하나 이상 있을 때에만 새 게임 시작할 수 있도록 하기

components/eventLogger/events.ts, components/wordchain/WordchainChatting/Wordchain/index.tsx, components/wordchain/WordchainChatting/index.tsx, components/wordchain/WordchainEntry/WordChainEntry.tsx, pages/wordchain/index.tsx
- close #857
- 다음의 네 가지 이벤트 로깅을 추가합니다.(스샷 참고)
=> feat: 끝말잇기 로깅 추가

components/wordchain/WordchainChatting/StartWordChatMessage/index.stories.tsx, components/wordchain/WordchainChatting/WordChatMessage/index.stories.tsx, components/wordchain/WordchainChatting/Wordchain/index.stories.tsx, components/wordchain/WordchainEntry/WordChainEntry.stories.tsx, components/wordchain/WordchainEntry/WordChainEntry.tsx, components/wordchain/WordchainEntry/WordchainMessage.stories.tsx, components/wordchain/WordchainRules.stories.tsx, pages/wordchain/index.tsx
- close #
- 스토리북 7 업데이트 대응
- Wordchain 스토리북 개선
=> chore: 끝말잇기 채팅 > 스토리북 업데이트 대응 및 개선

components/wordchain/WordchainChatting/Wordchain/index.tsx
=> feat: 첫 끝말잇기 시작 메시지 워딩 수정

components/wordchain/WordchainRules.tsx
=> chore: 끝말잇기 규칙 텍스트 수정

components/common/Header/desktop/DesktopHeader.tsx, components/makers/Notifier.tsx, components/members/common/select/Select.tsx, components/mentoring/data/development.ts, components/mentoring/data/production.ts, components/projects/upload/MemberForm/index.tsx, components/wordchain/WordchainChatting/index.tsx, pages/wordchain/index.tsx
- close #869 
- husky로 `pre-commit`때 실행되는 eslint 에 warnning이 표시되어 이를 수정합니다.
=> chore: eslint warning을 제거합니다.

components/wordchain/WordchainChatting/index.tsx
- close #
메이커스에 홍보하고 여러 사람들이 동시에 사용해보니 업데이트가 좀 더 원활하게 이루어지게 개선하는 것이 좋겠다 판단했습니다
따라서 SOPT에 본격적으로 홍보하기 전에 개선 작업을 합니다
- 에러 상황에도 업데이트
- 5초마다 polling
빠르게 전달하는 게 좋은 상황이라 일단 리뷰어 달지 않고 바로 머지하겠습니다!
제가 계속 모니터링 할게용
=> feat: 끝말잇기 채팅 업데이트 개선

components/wordchain/WordchainChatting/index.tsx
=> fix: polling 제거

components/wordchain/WordchainEntry/WordChainEntry.tsx
=> chore: 끝말잇기 진입점 터치영역 수정

components/wordchain/WordchainChatting/index.tsx
This reverts commit 82bff901f1ffa68182c2099555a7b814768f456f.
- close #
https://github.com/sopt-makers/sopt-playground-frontend/pull/884 참고
=> Revert "feat: 스크롤이 최하단일 때에만 polling 되도록 (#884)"

components/projects/edit/ProjectEdit.tsx, components/projects/form/ProjectForm.tsx, pages/projects/upload/index.tsx
- close #
- 제곧내
- 테스트하다가 발견했어요,,
- 글고 이미지 필수로 받도록 변경해봤는데 별로면 롤백 예정..
=> fix: 프로젝트 업로드 후 onSuccess 실행되지 않던 문제 수정

components/members/main/MemberList/MemberSearch.tsx, components/members/main/MemberList/index.tsx, components/projects/main/ProjectList.tsx, components/wordchain/WordchainEntry/WordChainEntry.tsx
=> feat: 멤버 검색 css 수정, 끝말잇기 및 프로젝트 헤더쪽 layout shift 수정

components/members/upload/schema.ts
=> fix: 프로필 업로드 스키마 수정

components/wordchain/WordchainChatting/StartWordChatMessage/index.tsx, components/wordchain/WordchainChatting/WordChatMessage/index.tsx, components/wordchain/WordchainChatting/Wordchain/index.tsx, components/wordchain/WordchainChatting/index.tsx, pages/members/index.tsx, pages/wordchain/index.tsx, styles/typography.ts
- close #821
모바일 뷰에 끝말잇기 뷰를 노출하고, 모바일 디자인 대응을 했어요
\+ 데스크탑뷰 구현 당시에 급하게 구현해서 실수로 잘못 스타일링한 것들도 몇 개 수정했어요
=> feat: 끝말잇기 모바일 대응

components/makers/Notifier.tsx
- close #910
만든 사람들 > 메이커스 3기 모집 홍보 배너 추가
서브타이틀 없으니까 약간 허전해버려 .... 이거 피드백 받으면 좋을 듯
=> feat: 만든 사람들 > 메이커스 3기 모집 홍보 배너 추가

components/members/upload/FormSection/Basic/index.tsx, components/members/upload/FormSection/SoptActivity.tsx, pages/members/edit.tsx
- close #914
- 이름 수정 불가능하게 변경
- 활동 정보 > 파트, 기수 수정 불가능하게 변경 (select -> disabled input)
=> feat: 회원가입 플로우 변경 대비 프로필 업로드 스펙 변경

pages/members/edit.tsx
- close #
활동 기수 -> 숫자만 보내도록 수정
=> fix: 프로필 수정 > 활동 기수 request body 형식 맞추기

components/members/detail/MessageSection/index.tsx
- close #
빨리 api 함수를 createEndPoint 방식으로 바꿔야겠어요
섹션 별 에러 바운더리 도입도 하면 너무 좋을 것 같구 ..
=> fix: 이메일 null 예외 처리

components/common/Banner/RecruitingBanner/index.tsx
=> feat: 모집 배너 변경

components/common/Banner/ActiveBannerSlot.tsx, components/common/Header/mobile/MobileSideBar.tsx, components/makers/Notifier.tsx
메이커스 3기 모집용으로 만들었던 배너와 안내를 제거했어요.
=> feat: 3기 모집 정보 제거

components/members/detail/InterestSection/index.tsx
=> fix: 프로필 상세 > mbti 설명 개행 되도록

constants/generation.ts
=> feat: 33기 적용

src/components/mentoring/data/production.ts
- close #939
이준호를 멘토링에서 내렸어요.
isOpened를 false로 변경했어요.
온보딩 짱!
=> chore: 이준호 없애기

src/pages/auth/login.tsx
- close #942 
- 페북 로그인이 불가능 함을 알리는 임시 팝업을 추가했어요.
=> chore: 페이스북 로그인 불가 알럿 임시 추가

src/components/makers/data/generation3.ts, src/components/makers/data/index.ts
=> feat: 3기 정보 추가

src/api/endpoint/auth/appleChange.ts, src/api/endpoint/auth/googleChange.ts, src/pages/auth/login.tsx
- 소셜로그인 API 오류를 수정했어요.
- 로그인 화면의 간격을 수정했어요.
=> fix: 소셜로그인 재설정 오류 수정

src/api/endpoint/auth/changeSMSCode.ts, src/api/endpoint/auth/changeSMSToken.ts, src/components/auth/reset/useResetLogin.ts, src/pages/auth/reset.tsx
- close #
잘못 적용되어 있던 소셜로그인 재설정 API 엔드포인트 호출을 바로잡습니다.
=> fix: 소셜로그인 재설정 엔드포인트 수정

src/components/members/upload/FormSection/PublicQuestion.tsx
=> chore: 프로필 업로드 > 공홈 공개 여부 관련 텍스트 제거

components/members/upload/FormSection/Basic/index.tsx, components/members/upload/schema.ts
- close #956 
휴대폰 번호를 필수 항목으로 수정합니다
이제 휴대폰 번호가 없었을 경우 수정하기 버튼을 누르면 번호를 입력하라고 뜹니다
UI 및 스키마 변경
=> feat: 프로필 > 휴대폰 번호 필수 항목으로 수정

src/components/members/upload/schema.ts
- close #960
정규식이 스펙과 맞지 않는 상태였어서 수정했습니다
=> fix: 프로필 업로드 > 휴대폰 번호 정규식 수정

src/components/makers/data/generation3.ts
=> feat: 메이커스 팀원 정보 변경

src/pages/_app.tsx, src/pages/_document.tsx
=> chore: og tag 기본 이미지로 계속 오버라이드 되는 문제 수정

src/components/members/upload/schema.ts, src/pages/members/edit.tsx
=> fix: 플그 소셜로그인 -> 회원가입 플로우 오류 수정

src/components/common/Banner/WelcomeBanner/index.tsx, src/components/members/main/MemberList/index.tsx, src/components/mentoring/MentoringList/index.tsx, src/components/wordchain/WordchainEntry/WordChainEntry.tsx, src/pages/members/index.tsx
- close #993 
- 컴포넌트간의 간격을 피그마에 맞게 조정했어요.
=> chore: 뷰 간격 조정

src/pages/intro/index.tsx
=> feat: 인트로에서 채널톡 숨기기

src/components/wordchain/WordchainEntry/WordChainEntry.tsx
=> fix: 끝말잇기 크래시 수정

src/pages/_app.tsx, src/pages/intro/index.tsx
=> feat: 채널톡 제거

playground-common/package.json, yarn.lock
- close #
- 크루쪽에서 사용할 때 에러가 발생했어요. ([관련 쓰레드](https://sopt-makers.slack.com/archives/C042T81PW80/p1695423057961749))
- radix-ui 쪽이 ^캐럿으로 다운받게 되어있는데, 요게 윗 마이너 버전껄 다운로드 하다가 문제가 생겼나봐요. 그래서 버전을 고정시켜주었습니다.
=> fix: radix-ui 버전 고정

src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx, src/components/wordchain/WordchainWinners/index.tsx
=> fix: 끝말잇기 모바일 크기 수정

src/components/wordchain/WordchainEntry/WordChainEntry.tsx
=> feat: 끝말잇기 배너 줄바꿈 수정

src/components/wordchain/WordchainEntry/WordChainEntry.tsx
=> chore: 조사 추가

src/components/members/upload/FormSection/SoptActivity.tsx
=> fix: 프로필 수정/업로드 > 활동 정보 모바일 반응형 버그 fix

src/components/members/upload/FormSection/SoptActivity.tsx
=> fix: 프로필 수정 > UI 깨짐 수정

src/components/wordchain/WordchainWinners/WordchainWinner/index.stories.tsx, src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
- close #1020 
- 줄바뀜 이슈 대응했습니다!
- `white-space: nowrap;` 를 추가해주었습니다.
=> fix: 명예의 전당 줄바뀜 이슈 대응

src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
- close #1022 
- 줄바꿈 이슈 대응했습니다!
- 건영 선상님의 팁인   `min-width: max-content; `코드를 추가했어요!
=> fix: 줄바꿈 대응

src/components/common/Banner/ActiveBannerSlot.tsx
- close #1025 
-33기 환영 배너를 내렸어요
- 코드를 삭제했어요
=> chore: 환영 배너 내리기

src/components/makers/data/generation3.ts
- close #1027
- 관련 쓰레드: https://sopt-makers.slack.com/archives/C042T81PW80/p1697459345358839
=> chore: 브컴팀 소개 설명 추가

src/components/wordchain/WordchainChatting/index.tsx
- close #
#1050 에서 작업하고 끝말잇기 스크롤이 깨졌는데, 아주 이상한 실수를 해서 깨졌던 것 이었습니다...
=> fix: 끝말잇기 스크롤 오류 수정

src/components/common/ImageUploader/index.tsx, src/components/feed/upload/ImagePreview/index.stories.tsx, src/components/feed/upload/ImagePreview/index.tsx, src/components/feed/upload/ImageUploadButton/index.stories.tsx, src/components/feed/upload/ImageUploadButton/index.tsx, src/components/projects/upload/form/ListImageUploader.tsx, src/hooks/useImageUploader.ts
- close #1051 
- 이미지 업로드 로직 커스텀 훅화
- 이미지 업로드 버튼, 이미지 프리뷰 컴포넌트 구현
커뮤니티 업로드 페이지에서 이미지 업로드 구현 시 useImageUploader와 ImageUploadButton, ImagePreview 컴포넌트를 조합하면 되도록 했습니다 !
=> feat: 커뮤니티 업로드 > 이미지 업로드 버튼, 이미지 프리뷰 컴포넌트 구현

src/components/auth/useAuth.ts
=> feat: 로그아웃시 인트로 페이지로 보내기

package.json, src/components/feed/common/FeedDropdown.stories.tsx, src/components/feed/common/FeedDropdown.tsx, src/hooks/useCopyText.tsx, yarn.lock
- close #1067 
- 드롭다운 추가했어요
- 디자인에 그려둔건 seperator가 있는데, 이게 1px 보다 작은 값입니다.. (크롬 브라우저에는 1px 보다 낮은 값을 사용할 수 없대요..)
- 의도가 os 기본 select를 이용하라는데, 이미 여기까진 해버려서 그냥 요걸로 하고 후 컨펌 받을 예정입니다!
- copyText도 유틸 훅으로 만들어두었어요.
=> feat: 더보기 드롭다운 추가, 클립보드 복사 유틸 훅 작성

src/api/endpoint/feed/getCategory.ts
- close #1071
- 카테고리 get api 구현
- zod를 이용해서 구현했습니다!
- 해당 api는 추후 확장가능성을 고려해서 재귀로 오는 데이터입니다! 그래서 zod의 타입을 어떻게 줄지 고민이었는데, 커비 선상님께서 큰 도움을 주셨습니다! 감사합니다!!!!!!!!!!!!!!!!!!!!!
- [zod 재귀 방법](https://github.com/colinhacks/zod#recursive-types) 
- lazy를 이용했습니다!
=> feat: 카테고리 get api 구현

src/components/feed/common/queryParam.tsx, src/components/feed/list/CategorySelect.tsx, src/components/feed/list/FeedList.tsx, src/components/feed/page/FeedHomePage.tsx
=> feat: 카테고리 가져오기 API 추가

src/api/endpoint/feed/uploadFeed.ts
- close #1076
- feed post api를 구현했어요.
- 기존 방식들과 동일하게 구현했습니다!
=> feat: feed post api 구현

src/api/endpoint/feed/uploadFeed.ts, src/components/feed/page/FeedUploadPage.tsx, src/components/feed/upload/ImageUploadButton/index.tsx, src/components/feed/upload/hooks/useUploadFeedData.ts, src/components/feed/upload/types.ts
- close #1081
- 피드 업로드 post api를 연결했어요. 
- useMutation을 이용했어요. 
업로드하고 community에 반영된 모습을 확인할 수 있습니다!
=> feat: 피드 업로드 post api 연결

src/components/feed/detail/slider/DynamicImage.tsx, src/components/feed/detail/slider/FeedImageSlider.tsx
- close #1084
- 포털 혹시몰라 client-side import 로 변경
- 이미지 슬라이더 아래 화면처럼 스크롤 되는 버그 픽스
https://github.com/sopt-makers/sopt-playground-frontend/assets/26808056/e150240a-aa0e-46aa-89ab-1d58df98c50c
https://github.com/sopt-makers/sopt-playground-frontend/assets/26808056/bbf3bc5d-3500-451e-9b89-0749d576486f
=> fix: 이미지 슬라이더 위치 버그픽스

src/components/feed/upload/Category/CategoryHeader/index.tsx
- close #1091 
- 모바일에서 호버 이벤트 삭제
- css에서 background를 투명으로 주었어요.
=> fix: 모바일에서 호버 이벤트 삭제

src/components/feed/common/hooks/useShareFeed.ts, src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetail.tsx, src/pages/feed/[id].tsx, src/pages/projects/[id].tsx, src/styles/global.ts
- close #1086 
- 포커스 비지블 스타일 제거
- 상세 페이지 추가 (`/feed/123`)
- 상세 페이지에서와 리스트 페이지에서와 뒤로가기 로직 다르게 하기 위해 left, right 로 주입할 수 있도록 변경 (로직은 적용 이전 - 링크가 바뀔때 적용 필요)
=> feat: 커뮤니티 상세페이지 추가

src/api/endpoint/feed/getComment.ts, src/api/endpoint/feed/getPosts.ts, src/api/typedAxios.ts
=> fix: 서버 스키마 오류 수정

src/components/feed/page/layout/MobileCommunityLayout.tsx
- close #
모바일에서 레이아웃이 이상하게 보이던 오류를 수정했습니다.
- 카테고리 위치
- 상세쪽 스크롤 이슈
=> fix: 카테고리 모바일 이슈 수정

src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedList.tsx
=> fix: 리스트에서도 댓글 익명으로 보이도록 수정

src/components/feed/list/FeedList.tsx, src/components/feed/page/FeedHomePage.tsx, src/components/feed/page/layout/MobileCommunityLayout.tsx
=> feat: 모바일 피드 상세 정책 변경

src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedList.tsx
=> fix: 질문 뱃지 nowrap 추가

src/components/feed/list/FeedList.tsx
=> fix: 피드 > 드롭다운 수정, 삭제 버튼색 변경

src/components/feed/list/CategorySelect.tsx
=> feat: 카테고리 wrap 추가

src/components/feed/page/FeedUploadPage.tsx, src/components/feed/upload/CheckboxFormItem/index.stories.tsx, src/components/feed/upload/CheckboxFormItem/index.tsx, src/components/feed/upload/CodeUploadButton/index.tsx
- close #1105
지수가 틀을 잘 만들어줘서 아주 편하게 작업했어용 짱짱
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/90694e08-9d13-4627-a2ec-d55ff908ead1
=> feat: 커뮤니티 업로드 > 질문글/익명 체크박스, 코드 버튼 추가

src/components/common/BottomSheet/index.tsx
- close #
- console.log를 삭제했어요.
=> chore: 불필요 코드 삭제

src/components/feed/common/hooks/useCurrentCategory.ts, src/components/feed/detail/DetailFeedCard.stories.tsx, src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetail.tsx, src/components/feed/page/FeedHomePage.tsx, src/constants/links.ts, src/pages/feed/[id].tsx
=> feat: 피드 상세 태그 추가

functions/feed/[id].ts
- close #
URL 로 직접 들어가면 연결해주는 Cloudflare Pages Function을 추가합니다.
SEE: https://github.com/sopt-makers/sopt-playground-frontend/pull/440
=> fix: 피드 상세 URL 직접접근 오류 수정

src/components/feed/common/hooks/useCurrentCategory.ts, src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetail.tsx
카테고리 ID를 넣으면 카테고리와 태그 정보를 추출하는 훅을 만듭니다.
=> refactor: 카테고리 정보 가져오는 훅 리팩터링

src/api/endpoint/feed/getComment.ts, src/api/endpoint/feed/getPost.ts, src/api/endpoint/feed/getPosts.ts, src/components/feed/detail/DetailFeedCard.stories.tsx, src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetail.tsx, src/components/feed/list/FeedCard.stories.tsx, src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedList.tsx
=> fix: 익명 글 및 댓글 작성시 member null로 내려오도록 수정된 것 타입 대응

src/components/feed/common/Icon.tsx, src/components/feed/list/FeedList.tsx
- close #
피드 로딩을 보여주는 방식 변경하고, 글이 없을때와 에러 났을때 표시를 추가했어요.
=> feat: 피드 로딩과 에러 처리 추가

src/components/feed/page/FeedUploadPage.tsx, src/components/feed/upload/Category/CategoryHeader/index.tsx, src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx, src/components/feed/upload/hooks/useUploadFeedData.ts
- close #1139
- 카테고리 셀렉터의 버그를 수정했어요. 
- 경우의 수가 잘못된 경우를 수정했습니다.
- 모바일 ui수정했어요.
=> fix: 카테고리 셀렉터 버그 수정

src/api/endpoint/feed/getComment.ts, src/api/endpoint/feed/getPost.ts, src/api/endpoint/feed/getPosts.ts, src/api/endpoint/feed/postReportComment.ts, src/api/endpoint/feed/postReportPost.ts, src/components/feed/common/hooks/useReportComment.ts, src/components/feed/common/hooks/useReportFeed.ts, src/components/feed/detail/FeedDetail.tsx, src/components/feed/list/FeedList.tsx
=> feat: 글 신고기능 추가, 내 글 판단여부 isMine으로 변경

src/components/feed/detail/DetailFeedCard.tsx, src/utils/parseTextToLink.tsx
- close #1146
- 글 상세에서 컨텐츠와 댓글에서 링크가 있을 경우 underline 추가
- 댓글 스타일 깨지는 것 수정
- 댓글 인풋창과 보내기 버튼 간격 조금 넣기
=> feat: 글 상세에서 컨텐츠와 댓글에서 링크가 있을 경우 a 태그로 변경

src/api/endpoint/feed/getCategory.ts, src/components/feed/page/FeedUploadPage.tsx
- close #1138
- 익명, 질문글 서버값에 따라 보이도록 서버가 변경되어서, 그에 따라 타입을 추가했어요!
- 다음의 내용을 추가했어요!
```
hasBlind: z.boolean().nullable(),
hasQuestion: z.boolean().nullable(),
```
=> fix: hasBlind, hasQuestion 타입 추가

src/components/feed/list/FeedList.tsx
- close #1149
- 업로드 페이지로 이동하는 버튼에 스타일을 추가했어요. 
- 코비 선상님의 조언대로 shadow를 넣어주었습니다
=> chore: 업로드 버튼 스타일 추가

src/components/feed/common/FeedDropdown.tsx, src/components/feed/page/FeedHomePage.tsx, src/components/feed/page/layout/MobileCommunityLayout.tsx, src/pages/feed/[id].tsx
모바일 레이아웃의 방식을 변경해 기존의 문제를 수정합니다.
- 스크롤 유지 안됨 이슈
- 카테고리를 눌러 리스트로 돌아갈때 이상해지는 이슈
=> feat: 커뮤니티 모바일 레이아웃 변경

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetail.tsx
- close #
글마다 작성중인 댓글을 따로 관리해서 유지되도록 변경합니다.
=> feat: 글마다 작성중 댓글 따로 유지

src/components/common/Header/mobile/MobileSideBar.tsx, src/components/feed/upload/Category/DropDown/index.tsx, src/components/layout/FullScreenLayout.tsx, src/components/layout/utils.ts, src/components/members/detail/MessageSection/MessageModal.tsx, src/components/wordchain/WordchainChatting/index.tsx, src/pages/mentoring/[id].tsx
- close #
마법같은 dvh 단위가 있더라고요 ([참고](https://abcdqbbq.tistory.com/104)). 추가로 [@supports](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) 쿼리를 사용해 dvh 사용이 가능할 때만 dvh를 사용하도록 추가했어요.
=> fix: 100vh 문제 해결

src/api/endpoint/feed/getPost.ts, src/components/feed/detail/FeedDetail.tsx
- close #
변경된 피드 API의 형식을 반영합니다.
=> fix: 피드 API 형식 변경

package.json, src/components/feed/detail/FeedDetail.tsx, src/components/feed/detail/FeedDetailComments.tsx, src/components/feed/detail/FeedDetailContent.tsx, src/components/feed/detail/FeedDetailInput.tsx, src/components/feed/list/FeedList.tsx, src/components/feed/list/FeedListItems.tsx, yarn.lock
렌더링 오류가 터져도 사이트 전체가 터지지 않고 일부만 터지게 해서 영향력을 최소화시키는 코드를 작성했어요.
[@toss/error-boundary](https://slash.page/ko/libraries/react/error-boundary/src/ErrorBoundary.i18n) 를 사용했고, 적용하기 위해 피드 상세와 리스트 컴포넌트를 조금 리팩터링했어요.
=> feat: 피드 보기 에러 바운더리 추가

package.json, src/components/common/ImageUploader/index.tsx, src/components/feed/page/FeedUploadPage.tsx, src/components/projects/upload/form/ListImageUploader.tsx, src/hooks/useImageUploader.ts, yarn.lock
- close #
서버 이미지 리사이징이 생길 때까지 일단 클라에서 리사이징해서 올리는거로 대응해요.
=> feat: 업로드시 프론트에서 이미지 리사이징

src/components/feed/page/FeedUploadPage.tsx
- close #
- 업로드 페이지의 뒤로가기 버튼에 cursor pointer 추가했어요.
=> chore: 백버튼에 cursor pointer 추가하기

src/components/feed/list/FeedListItems.tsx
- close #
- 피드 디테일로 들어가지 않아도 수정 버튼 클릭 시 토스트 뜨도록 수정했어요.
=> feat: 피드 디테일로 들어가지 않아도 수정 버튼 클릭 시 토스트 뜨도록 수정

src/components/feed/detail/FeedDetailContent.tsx
- close #
- 질문 글 아닌 경우에는 질문 칩 안 뜨도록 isQuestion 값을 내려주었어요.
=> fix: 질문 글 아닌 경우에는 질문 칩 안 뜨도록 isQuestion 값 내려주기

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetailInput.tsx
- close #1172
- 댓글 등록 시 로딩을 추가했어요. 
- 더불어, 댓글이 공백인 경우 submit 버튼이 disabled되도록 했어요. 
- 댓글 post할 때 isPending이 true인 경우 로딩이 뜨도록 했어요. 
- 기존에 있던 is버튼액티브 에 isPending이 false인 경우도 추가해서, is버튼액티브가 아닌 경우에 버튼이 disabled되게 처리했습니다.
=> feat: 댓글 등록 시 로딩 추가

src/pages/community/index.tsx, src/pages/feed/[id].tsx
=> feat: 커뮤니티 메인 AuthRequired 추가

src/api/endpoint/feed/postComment.ts, src/components/feed/detail/FeedDetailInput.tsx, src/constants/links.ts
- close #1179
- 댓글 보낼 때 weblink도 같이 보냅니다. 그래야 알림 간대용
=> feat: 댓글 보낼 때 weblink 같이 보내도록 수정

src/components/feed/detail/FeedDetailInput.tsx
=> fix: 빈 텍스트 입력시 댓글 전송 막기

src/components/feed/detail/DetailFeedCard.tsx
This reverts commit 2ffd0a7b612d798043184211fa29643022f6bf8a.
- close #
- @seojisoosoo 요거 잠시 리버트 할게요..! ([관련 스레드](https://sopt-makers.slack.com/archives/C046R63J492/p1701085771234829))
=> Revert "chore: 익명박스 하단에 붙도록 수정 (#1180)"

src/components/feed/detail/FeedDetailComments.tsx
- close #
- #1171 요거 댓글쪽 마진준거 사이드이펙트로 그렇게 돼서 여기다가 flex:1 추가해써용
=> feat: 댓글 영역 flex:1 로 늘리기

src/components/common/ImageUploader/index.tsx, src/components/feed/page/FeedUploadPage.tsx, src/components/feed/upload/ImageUploadButton/index.tsx, src/components/feed/upload/hooks/useUploadFeedData.ts, src/components/projects/upload/form/ListImageUploader.tsx, src/hooks/useImageUploader.ts
- close #1167
이제 기본적으로 useImageUploader는 이미지 배열을 다룹니다아아
=> feat: 이미지 업로드 여러 장 가능하도록

src/components/feed/common/utils.ts
- close #
- https://sopt-makers.slack.com/archives/C042T81PW80/p1701085142118769?thread_ts=1700980411.484089&cid=C042T81PW80
=> feat: 특수임원 예외처리

src/components/feed/common/utils.ts
=> feat: 취업진로 카테고리에서 이름 나오게

src/components/feed/detail/DetailFeedCard.tsx
=> feat: 댓글 입력창 길이 수정

src/components/common/Loading/index.tsx, src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetailComments.tsx, src/components/feed/list/FeedCard.tsx
- 댓글과 댓글 입력창의 UI를 개선했어요.
- [refactor: 댓글을 여러줄로 작성할 수 있도록 개선](https://github.com/sopt-makers/sopt-playground-frontend/commit/667e8b827e23b201ec38e5b0528bcb494cdca11f) </br> 댓글을 여러줄 입력할 수 있도록 input → textarea로 변경했어요. (`TODO` 댓글은 여러줄 입력할 수 있는데, 실제 남겨진 댓글은 한줄로 보여요. 실제로도 줄바꿈이 되도록 개선이 필요해요. 이건 부탁하겠습니다 fe 분들 ㅎㅎ)
- [refactor: Loading size props 추가 및 댓글 post pending ui 개선](https://github.com/sopt-makers/sopt-playground-frontend/commit/129af33734dc1b20a94dfa024036cfed7a41764f) </br> 댓글이 등록되는 pending 상태일 때 로딩 ui가 자연스럽게 보이도록 개선했어요. 추가로 SendButton도 disabled 시켰어요.
- [feat: 이름 옆 정보가 길때 짤리지 않도록 처리](https://github.com/sopt-makers/sopt-playground-frontend/commit/c5b1639591c12bf3a40904d81331b9827e680b2f) </br> 이름 옆에 커리어가 길게 표시될 경우 댓글 레이아웃이 다 깨져서 특정 width부턴 ellipsis되도록 처리했어요.
commit by로 보시면 편합니당
=> 댓글 및 댓글 입력창 UI 전반적인 개선

src/components/feed/upload/hooks/useUploadFeedData.ts
- close #
- 익명박스와 질문박스 체크 후, 체크가 불가능한 카테고리로 이동시(ex.홍보)에도 체크박스값이 true가 되어버리는 이슈가 발생했습니다. 
- 체크가 불가능한 카테고리를 선택하면 익명박스와 질문박스를 false로 초기화해주었어요.  
```
const resetIsBlindWriter = (categoryId: number) => {
!findParentCategory(categoryId)?.hasBlind && setFeedData((feedData) => ({ ...feedData, isBlindWriter: false }));
};
const resetIsQuestion = (categoryId: number) => {
!findParentCategory(categoryId)?.hasQuestion && setFeedData((feedData) => ({ ...feedData, isQuestion: false }));
};
```
- 저장된 categoryId로 부모 카테고리값을 찾은뒤, hasBlind, hasQuestion값으로 참조했습니다! 
- 카테고리를 저장하는 handleSaveCategory 함수에서, resetIsBlindWriter, resetIsQuestion를 실행시켜서 익명과 질문글이 불가능한 경우에 false로 초기화되게 했어요. 
- 홍보 게시판 이외에도 익명, 질문이 불가능한 카테고리가 추후 추가될 수도 있으므로, hasBlind, hasQuestion값으로 참조했습니다!
=> feat: 익명, 질문글 체크 후, 체크가 불가능한 카테고리로 이동시 체크박스 값 초기화 구현

src/components/common/Modal/useConfirm.tsx, src/components/feed/common/hooks/useBlindWriterPromise.tsx, src/components/feed/common/hooks/useDeleteComment.ts, src/components/feed/common/hooks/useDeleteFeed.ts, src/components/feed/common/hooks/useReportFeed.ts, src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetailComments.tsx, src/components/feed/list/FeedCard.tsx, src/components/feed/upload/Input/ContentsInput/index.tsx, src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
- close #
- 댓글 박스 고정 크기 css 추가
- 그에 따른 ellipsis 추가해주었습니다. 
- 모달 max-width를 추가해주었습니다. 
```
white-space: nowrap;
text-overflow: ellipsis;
overflow: hidden;
width: 240px;
```
- 위의 css 추가해주었어요~
=> chore: css 수정

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetailComments.tsx, src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
- close #
- 커뮤니티 이용규칙 overflow css속성 추가
- 댓글 white-space 속성 추가
=> chore: css 디테일 더하기

src/components/common/HorizontalScroller/index.tsx
- close #
가로 스크롤 버튼을 클릭할 때 상위의 클릭이 실행되는 오류를 수정했어요.
=> fix: 가로 스크롤 버튼 클릭 오류 수정

src/components/common/Text/index.tsx, src/components/feed/detail/DetailFeedCard.tsx
- 입력창과 버튼 간격 수정
- 익명 체크박스의 텍스트를 눌러도 체크가 되도록 변경
- 글을 입력중일 땐 포커스가 나가도 스타일이 유지되도록 변경
=> feat: 커뮤니티 몇몇 디테일 추가

src/components/auth/AuthRequired.tsx
=> feat: 로그아웃시 인트로 페이지로

src/components/eventLogger/events.ts, src/components/feed/common/hooks/useFeedReferral.ts, src/components/feed/detail/FeedDetail.tsx, src/components/feed/detail/FeedDetailInput.tsx, src/components/feed/list/CategorySelect.tsx, src/components/feed/list/FeedList.tsx, src/components/feed/list/FeedListItems.tsx, src/components/feed/page/FeedHomePage.tsx, src/pages/feed/[id].tsx
- close #1230
```ts
{
feedListCategoryFilter: { // 카테고리 선택 필터
category: string;
};
feedCard: { // 피드 카드
feedId: string;
};
feedShareButton: { // 피드 공유하기
feedId: string;
referral: 'list' | 'more' | 'detail'; // 리스트 페이지에서, 더보기해서 나온 카드에서(`?feed=id`), 상세 피드(`feed/:id`)에서
};
feedBackButton: { // 뒤로가기
feedId: string;
referral: 'more' | 'detail';
};
feedCategoryChipLink: { // 상세페이지의 카테고리 칩 링크버튼
feedId: string;
};
feedUploadButton: undefined; // 업로드 버튼
}
```
```ts
{
postComment: { // 댓글 전송
feedId: string;
referral: 'more' | 'detail';
isBlindWriter: boolean;
};
}
```
```ts
{
feedList: undefined; // 피드 리스트 페이지
feedDetail: { // 피드 상세 페이지
feedId: string;
};
}
```
```ts
{
feedCard: { // 피드 카드
feedId: string;
}
}
```
=> feat: 피드 리스트, 디테일 등 로깅 추가

src/pages/members/index.tsx
- close #
- 멤버에서 끝말잇기와 멘토링을 삭제했어요.
=> chore: 끝말잇기와 멘토링 멤버에서 삭제

src/components/members/main/MemberList/index.tsx
- close #1237
- 데탑은 프로젝트쪽 간격과 맞췄고
- 모바일은 기존 멘토링과 띄어진 간격만큼만 맞췄어용
=> feat: 멤버 페이지 헤더 변경에 따른 간격 수정/추가

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/list/CategorySelect.tsx, src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedList.tsx, src/components/feed/list/FeedListItems.tsx, src/components/feed/page/layout/MobileCommunityLayout.tsx, src/components/feed/upload/ImageUploadButton/index.tsx
- 자잘하게 스타일 다른 부분 수정하고, 보면서 어색했던 부분도 업데이트했어용
- 스타일 관련된 부분이라 바로 배포할게요
=> 자잘한 스타일 수정

src/components/feed/page/FeedUploadPage.tsx
=> 글쓰기 뒤로가기 버튼 에러 수정

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/list/FeedCard.tsx
=> 이미지 사이즈 크게 조정

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedListItems.tsx
- close #
#1239 에서 누락된 커뮤니티 이미지 리사이징을 추가하고 리사이징 크기를 미세조정해요.
=> feat: 커뮤니티 이미지 리사이징 추가

src/components/feed/page/layout/DesktopCommunityLayout.tsx
- close #
다른 페이지로 이동했다가 뒤로가기로 돌아올 때 열리는 애니메이션이 다시 재생되는 문제를 해결해요.
=> fix: 페이지 이동시 애니메이션 들썩거리는 현상 수정

src/pages/intro/index.tsx
- close #
- 인트로 페이지에서 로그인이 되어있을 때 member페이지로 이동하는 것을 발견해서, feed로 가도록 링크를 수정해주었습니다!
=> chore: 인트로에서 로그인되어있을 시 이동 링크, feedList로 변경

src/components/feed/list/CategorySelect.tsx, src/components/feed/list/FeedList.tsx, src/components/feed/page/FeedHomePage.tsx
- close #
카테고리가 변경될 때 일괄적으로 기존 쿼리를 invalidate 하도록 만들고, 스크롤을 가장 위로 이동시키도록 만들었습니다.
=> feat: 카테고리 변경시 동작 고도화

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetail.tsx
=> feat: 피드 상세 스크롤 정책 수정

src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
- close #1260 
- 익명 규칙 레이아웃이 작게 설정되는 것을 해결하기 위해 width:100%를 주었어요.
=> fix: width 100%로 수정

src/components/common/form/FormProgress.tsx, src/components/projects/upload/form/ProjectForm.tsx, src/components/projects/upload/form/fields/CategoryField.tsx, src/components/projects/upload/form/fields/GenerationField.tsx, src/components/projects/upload/form/fields/LinkField.tsx, src/components/projects/upload/form/fields/MemberField.tsx, src/components/projects/upload/form/fields/PeriodField.tsx, src/components/projects/upload/form/fields/ServiceTypeField.tsx, src/components/projects/upload/form/fields/StatusField.tsx, src/components/projects/upload/form/fields/member/MemberSearch.tsx
- close #1267 
- 관련 제보 쓰레드 https://sopt-makers.slack.com/archives/C042T81PW80/p1705233220024659
=> feat: 프로젝트 업로드 > 보라색 걷어내기 수정

src/api/endpoint/projects/getProjects.ts, src/api/endpoint_LEGACY/hooks/projects.ts, src/api/endpoint_LEGACY/projects/index.ts, src/api/endpoint_LEGACY/projects/type.ts, src/components/projects/main/ProjectList.tsx, src/components/projects/upload/hooks/useGetProjectListQuery.ts
- close #1266
- 프로젝트 api를 무한스크롤로 변경합니다.
- 검색 등 다른 필터들은 ui 개선하면서 다음 PR에서 이어갈게요!
- 프로젝트 전체 갯수는 서버에서 추가로 내려줘야 해서 요청한 상태구, 그래서 잠시 주석처리했습니당
=> feat: 프로젝트 리스트 무한스크롤 적용

src/components/intro/sections/CatchPhrase/icons.tsx, src/components/intro/sections/CatchPhrase/index.tsx, src/pages/auth/login.tsx, src/styles/typography.ts
=> feat: 새로운 로그인 화면 적용

src/pages/auth/login.tsx
=> fix: 로그인 화면 클릭 안됨 오류 해결

src/components/projects/main/ProjectList.tsx, src/components/projects/main/ProjectSearch.tsx
- close #1277
- 나머지 필터들은 투비컨티뉴
=> feat: 프로젝트 검색 기능 추가 / 업로드 버튼 플로팅으로 변경

src/components/intro/sections/Footer.tsx, src/components/makers/Notifier.tsx
=> feat: 4기 모집 준비 대응

src/api/endpoint_LEGACY/projects/type.ts, src/components/members/common/select/context.ts, src/components/projects/main/ProjectCategorySelect.stories.tsx, src/components/projects/main/ProjectCategorySelect.tsx, src/components/projects/main/ProjectFilterChip.stories.tsx, src/components/projects/main/ProjectFilterChip.tsx, src/components/projects/main/ProjectList.tsx, src/components/projects/upload/hooks/useGetProjectListQuery.ts
- close #1284 
- 카테고리를 선택하는 CategorySelect
- 창업중, 이용가능 필터를 모바일 / 데스크톱 모두 반영하였습니다!
- 생각해보니 새로운 ui는 서버도 변경작업이 또 필요하겠더라구요 ㅠㅠ 그래서 유진 돌아오면 부탁하고 반영하려고 합니다!
=> feat: 프로젝트 리스트 필터 3종 추가

src/components/projects/main/ProjectList.tsx
=> feat: 프로젝트 리스트 모바일 화면 들썩임 현상 수정

src/components/projects/main/ProjectList.tsx
- close #
- width 100% 컨텐츠에 주고 그 위의 컨테이너에 있는 패딩 때문에 정렬이 맞지 않게되어 패딩을 컨텐츠로 이동시킴
=> fix: 프로젝트 리스트 모바일 > padding 위치 수정

src/components/projects/main/ProjectCategorySelect.stories.tsx
=> feat: 프로젝트 필터 스토리 추가

src/components/makers/Notifier.tsx, src/components/makers/data/generation3.ts
- close #
- 4기 모집이 시작되었는데, 아직 시작될 예정이에요. 라는 멘트가 남아있어서 수정했습니다.
=> chore: 4기 모집 시작으로 워딩 변경

src/components/common/ContentsCard/index.tsx
- close #
- 콘텐츠 카드의 너비가 텍스트 길이에 따라 변경되는 이슈를 해결했어요.
- max-width를 설정했어요.
=> fix: 콘텐츠 카드 max-width 설정

src/components/makers/Notifier.tsx
- close #
- 4기 지원 가능 날짜를 변경했어요.
=> chore: 4기 지원 가능 날짜 변경

src/components/common/ContentsCard/index.tsx, src/components/members/detail/MemberDetail.tsx, src/components/members/detail/MemberProjectCard.tsx
=> refactor: 컨텐츠 카드 가로 길이 문제 해결

src/components/makers/Notifier.tsx
- close #
- 4기 모집 중 멘트를 수정했어요.
=> chore: 4기 모집 중 멘트 내리기

src/constants/generation.ts
플그에서 34기를 선택할 수 있도록 대응해요.
(자동으로 처리하면 참 좋을텐데... 활동 기간이 조금씩 달라서 어떤 공식으로 처리하기 참 애매하네요)
=> feat: 34기 적용

.github/actions/randomReviewer.js
- close #1303
- 랜덤 리뷰어 목록을 4기 기준으로 변경했어요.
=> chore: 랜덤 리뷰어 4기 기준으로 변경

README.md
- close #1304
- 리드미에 플레이그라운드 4기 메이커 정보를 반영했어요.
=> chore: 플레이그라운드 4기 메이커 정보 반영

src/components/makers/data/generation4.ts, src/components/makers/data/index.ts
- close #1300 
- 플그에 4기 메이커스 정보를 추가했어요. 
- 기존에 구현되어있던 타입을 가져와서 데이터만 넣어주었습니다. 
- 서버에서 화이트리스트 열어주시면, 확인 후 머지할게요~
=> feat: 4기 정보 추가

src/components/common/Banner/WelcomeBanner/index.tsx
- close #1328
- 데탑에서만 환영 배너를 고정했어요.
- 데탑에서만 position:fixed
=> feat: 데스크탑에서만 환영 배너 고정하기

playground-common/README.md, playground-common/export.ts, src/components/common/Banner/WelcomeBanner/index.tsx
=> chore: 배너 밑줄 수정

src/components/common/Banner/WelcomeBanner/index.tsx
=> chore: 환영배너 스타일링 수정

src/components/resolution/MemberCardOfMe.tsx, src/pages/members/complete.tsx
- close #1354
- 뱃지 색상 잘못되어있어서 변경
- 페이지 레이아웃 적절히 조정
- 등록완료 페이지에서 푸터 안보이도록
=> fix: 프로필 등록 완료 페이지 디테일 수정

src/components/members/upload/CheckActivity/CheckSoptActivity.tsx
- close #1359 
- ux writing을 수정했어요.
=> chore: ux writing 수정

src/constants/links.ts
- close #1361
`groupDetail: (id: string | number) => `/group/${id}`,` 로 되어있던 링크를
`groupDetail: (id: string | number) => `/group/detail?id=${id}`,` 로 알맞게 변경
=> fix: groupDetail link 변경

src/components/feed/common/hooks/useBlindWriterPromise.tsx
- close #1367
모달 zIndex prop을 zIndex.헤더+1 값으로 넘겨주었습니다.
=> fix: 익명 여부 수정 모달 zIndex 수정

src/components/projects/main/ProjectList.tsx
=> chore: 프로젝트 검색창 layout shift 수정

src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedListItems.tsx
- close #1376 
- 미리보기로 볼 수 있었던 댓글과 조회수를 내리고, 디테일 페이지 안에서만 보여지도록 했어요.
=> chore: 댓글, 조회수 미리보기 내리기

src/components/feed/list/FeedCard.tsx
- close #
- 피드 업로드 시간 미리보기를 삭제했습니다.
=> chore: 피드 업로드 시간 미리보기 삭제

src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedListItems.tsx
=> fix: 익명프로필 없는 익명 유저 대응

src/components/feed/page/FeedUploadPage.tsx
- close #1387 
- 모바일 피드 업로드 헤더 고정
- position: fixed; 로 스타일리을 부여해주었어요.
=> chore: 모바일 피드 업로드 헤더 고정

src/components/feed/page/FeedUploadPage.tsx
- close #
- 피드 작성 모바일 부분에서 헤더와 콘텐츠 부분이 겹치는 문제를 확인했어요. 
- z-index를 주었어요, z-index에 대한 위계를 하루빨리 정하면 좋겠습니다!
=> chore: 모바일 헤더 앞으로 오도록 수정

src/components/feed/detail/DetailFeedCard.tsx
- close #1395
- 댓글 익명프로필 엑박 해결했어요.
- anonymousProfile이 있는지 없는지 삼항 연산자를 추가해주었어요.
=> chore: 댓글 익명프로필 엑박 이슈 해결

src/components/members/hooks/useRegisterModal.tsx
- close #1399 
슬랙: https://sopt-makers.slack.com/archives/C042T81PW80/p1714393433638219
모바일 환경일 경우 모달 배경이 찌그러지는 거 수정했습니다
|전|후|
|--|--|
|<img width="468" alt="image" src="https://github.com/sopt-makers/sopt-playground-frontend/assets/63948884/49114008-f28e-4206-9ecf-59be71fd49d0">|<img width="329" alt="image" src="https://github.com/sopt-makers/sopt-playground-frontend/assets/63948884/5b77e658-843e-4874-885a-fd3a18f34012">|
=> chore: 활동 정보 확인 모달 스타일링 수정

src/components/feed/list/FeedCard.tsx
=> fix: 솝커톤용 임시 게시물 hover 이벤트 추가

src/components/eventLogger/events.ts, src/pages/projects/upload/index.tsx
- close #1410 
- 공유하러 가기 버튼에 클릭 로깅을 달았어요.
- 기존 로깅방식과 동일하게 작업했습니다!
=> feat: 프로젝트 등록 후 팝업 공유하러 가기 클릭 이벤트 로깅

src/components/feed/list/FeedCard.tsx
=> fix: 388번 게시물에 대해 솝커톤용 UI 지정

src/components/feed/list/FeedCard.stories.tsx, src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedListItems.tsx
=> fix: 솝커톤용 UI 내리기

src/components/common/KakaoScript/index.tsx, src/hooks/useKakao.ts
=> chore: 카카오톡 채널 연동 테스트

src/hooks/useKakao.ts
=> chore: 카카오톡 앱 키 명칭 변경

src/components/wordchain/WordchainEntry/WordchainMessage.tsx
- close #
우승자의 경우 폰트 흰색 컬러 적용되도록 스타일드 컴포넌트에 prop을 내려주었어요.
=> chore: 우승자의 경우 폰트 흰색 컬러 적용되도록 prop 내려주기

src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx, src/components/feed/page/layout/MobileCommunityLayout.tsx, src/components/wordchain/WordchainEntry/WordChainEntry.tsx
=> feat: 끝말잇기 진입점 모바일 반응형

src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx
=> fix: 메뉴 클릭 영역 수정

src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx
=> feat: 모바일 메뉴 진입점 스타일링 수정

src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx, src/components/wordchain/WordchainEntry/WordChainEntry.tsx
=> feat: 모바일 메뉴 호버

playground-common/package.json
=> feat: DesktopHeader에서 끝말잇기를 제거한 수정본 배포

src/api/endpoint_LEGACY/members/type.ts, src/components/members/upload/FormSection/Basic/index.tsx, src/components/members/upload/constants.ts, src/components/members/upload/types.ts, src/pages/members/edit.tsx, src/pages/members/upload.tsx
=> chore: 이메일 마스킹 코드 제거

src/pages/index.tsx
- close #1464
메인 화면에 다짐메시지 테스트를 위해 띄워놨던 모달을 삭제했습니다.
=> fix: 다짐메시지 테스트 삭제

src/components/auth/register/verify/view/ByPhoneView.tsx, src/components/common/Banner/ActiveBannerSlot.tsx, src/components/wordchain/WordchainEntry/WordChainEntry.tsx, src/pages/remember/index.tsx
- close #1476
- 회원가입 전화번호 placeholder 수정
- placeholder를 수정했어요.
- dev에 묶여있는 기능들이 있어서 dev, main 브랜치를 정말 분기해야할 것 같아요..!
=> chore: 회원가입 전화번호 placeholder 수정

src/components/members/upload/FormSection/Basic/index.tsx, src/components/members/upload/schema.ts
=> feat: 전화번호 - 조건 삭제

src/components/auth/register/verify/useByPhone.ts, src/components/auth/reset/useResetLogin.ts, src/components/members/upload/schema.ts
=> feat: 전화번호 에러 메시지 수정

src/api/endpoint/remember/getReviews.ts, src/components/remember/reviews/index.tsx
- close #
- 무한스크롤을 위해 서버에서 내려주는 데이터에 hasNext가 추가되면서 타입 수정을 했습니다.
=> fix: 활동 후기 타입 에러 수정

src/api/endpoint/remember/getReviews.ts, src/components/remember/index.tsx
- close #1475
- 활동 후기 페이지 뒤로가기 구현
- 무한스크롤 코드 수정
- 기존 코드를 참고해서 구현했어요!
- 무한스크롤 관련해서 서버 수정이 필요한 것 같아, 서버 수정 후 재작업 들어가도록 하겠습니당
=> feat: 활동 후기 qa

src/components/common/Banner/ClosingCeremonyBanner/index.tsx, src/components/feed/page/layout/DesktopCommunityLayout.tsx, src/components/resolution/read/ResolutionReadModal.tsx, src/components/resolution/read/hooks/useImageDownload.ts
=> Feat: 다짐메시지 관련 QA 반영

src/api/endpoint/remember/getReviews.ts
- close #
- 무한스크롤에서 다음 페이지가 너무 빨리 불러와지는 것 같아서, 크기를 조금 크게 수정했어요.
=> chore: 무한스크롤 크기 수정

src/components/makers/AboutMakers.tsx, src/components/makers/Notifier.tsx
=> chore: 5기 모집 중 텍스트 변경

src/components/makers/AboutMakers.tsx
- close #
- sopt -> SOPT 로 텍스트를 변경했어요.
=> chore: 텍스트 변경

src/api/endpoint/members/putMemberProfile.ts, src/pages/members/upload.tsx
=> feat: 커피챗 활성화/비활성화시 커피챗 활성화 멤버 목록 invalidate

src/components/coffeechat/CoffeeChatCard/index.tsx, src/components/coffeechat/CoffeeChatList/index.tsx, src/components/members/detail/MessageSection/MessageModal.tsx
=> feat: 커피챗 기능 QA 대응

src/components/coffeechat/CoffeeChatCard/index.tsx, src/components/coffeechat/CoffeeChatList/index.tsx, src/components/eventLogger/events.ts, src/components/members/main/MemberCard/MessageButton.tsx, src/components/members/upload/FormSection/CoffeeChat.tsx
=> feat: 커피챗 기능 클릭 이벤트 로깅

src/components/members/detail/ActivitySection/MemberDetail.tsx, src/components/members/upload/FormSection/Career.tsx
=> feat: 상세 프로필 커피챗 아이콘 노출 및 직무 기간 변경 이슈 해결

src/components/coffeechat/CoffeeChatList/index.tsx
=> feat: 커피챗 활성화 유저 없을 경우 처리

src/components/common/Banner/AdsBanner/AdsBox/index.tsx, src/components/common/Banner/AdsBanner/constants/ads.ts, src/components/common/Banner/AdsBanner/index.tsx
- close #1515
- 광고 배너 qa를 반영했어요!
=> feat: 광고 배너 qa 반영

.github/actions/randomReviewer.js
- close #1528 
- 랜덤 리뷰어에 5기 신규회원을 추가했어요.
=> chore: 랜덤 리뷰어 리스트에 하윤, 도영 추가

README.md
- close #1543 
- 플그 소개글을 최신화했어요.
- 플그 스크린샷을 최신화했어요.
- 플그 멤버를 최신화했어요.
=> docs: README.md 프로젝트 소개 업데이트 및 멤버 변경

README.md
- close #1546
- `</div>`가 누락되어 레이아웃이 가운데 정렬로 틀어져있는 문제를 해결했어요.
- 사진 비율을 조정했어요.
=> docs: readme 레이아웃 수정

src/components/common/Banner/AdsBanner/constants/ads.ts
- close #1557
- 코드잇 광고 구좌 2차 광고로 변경했어요. (17일에서 18일 넘어가는 자정 배포)
- 이미지 변경
=> feat: 코드잇 2차 광고 구좌 변경

src/components/makers/data/generation35.ts, src/components/makers/data/index.ts, src/constants/generation.ts
- close #1530
- 메이커스 만든이 35기를 갱신했어요.
- 솝트 마지막 기수를 35기로 갱신했어요.
- 멤버 리스트 내용을 채워주었어요.
=> feat: 메이커스 35기 갱신

src/components/common/form/FormItem.tsx, src/components/resolution/submit/ResolutionSubmitModal.tsx, src/components/resolution/submit/useConfirmResolution.ts, src/components/resolution/submit/useOpenResolutionModal.ts, src/constants/generation.ts
>[!NOTE]
> 의존성이 있는 `환영배너`와 `다짐메시지` 작업을 서로 다른 PR로 작업하기 위해서, 아래와 같이 브랜치를 땄습니다. 
> 따라서 PR을 닫을 때, 이 PR(`feat/#1562-resolution`)을 먼저 `feat/#1562-welcomeBanner`에 병합한 후 [`환영배너` PR](https://github.com/sopt-makers/sopt-playground-frontend/pull/1563)을 병합해야함을 명시합니다.
```mermaid
gitGraph
commit
branch "feat/#1562"
checkout "feat/#1562"
commit
branch "feat/#1562-welcomeBanner"
checkout "feat/#1562-welcomeBanner"
commit
checkout "feat/#1562"
branch "feat/#1562-resolution"
checkout "feat/#1562-resolution"
commit
```
- close #1562
기존에 만들어두었던 모달을 그대로 사용하는 것이기때문에
특별히 새로 구현한 내용은 없고,
자잘한 스타일링과 라이팅 변경이 있습니다!
**dialog 관련**
도영이가 슬랙에서 언급해준대로 dialog MDS를 사용할 수 없는 문제가 있어서 여기서도 일단 기존 플그 내 dialog를 사용한 상태입니다. 따라서 MDS와 디자인이 다릅니다.
https://github.com/user-attachments/assets/7fa407f5-7d6d-4016-ab69-de42904d1bb2
한 번 밖에 제출할 …
=> feat: 다짐메시지 모달

src/components/common/Modal/parts/index.tsx, src/components/common/Modal/useCustomConfirm.tsx, src/components/members/detail/MessageSection/MessageModal.tsx
- close #1552 
Custom Confirm Dialog에 대해서 디자인 변경점들에 대해서 변경을 진행했습니다.
slack 이슈에서 확인할 수 있듯이, 현재 Custom Confirm은 Playground 공통 모달을 사용하지 않고 독자적 모달을 사용하고 있기에, 이 모달에 따로 mds 및 디자인 변경 사항을 직접 구현했습니다.
디자인 변경점 및 반응형 처리에 대해 스타일링 수정이 있었습니다. 이 과정에서 mds Dialog 디자인이 적용되었습니다!
스타일링 변경이 주이고, 간단한 변수명 변경이 있었습니다!
✨ 설명하기
=> fix: Custom Confirm 컴포넌트 디자인 변경점 적용

src/pages/auth/login.tsx
- close #1586 
애플 로그인 계정 재설정 유도 텍스트 수정을 진행했습니다.
=> fix: 애플 로그인 계정 재설정 유도 텍스트 수정

src/components/makers/data/generation35.ts
- close #1584 
백채영 -> 손혜정으로 변경
=> fix: 플랫폼 팀원 업데이트

src/components/common/Banner/AdsBanner/constants/ads.ts
- close #1591
- 광고 구좌 변경(10/13)
=> feat: 광고 구좌 변경

src/pages/test/image/index.tsx
- close #1602
- `test/image` url로 웹뷰에서 발생하는 이슈 재현된 페이지 제작했습니다.
- 느낌있고 간단하게
=> feat: test/image 페이지 제작

src/components/common/Banner/AdsBanner/constants/ads.ts
- close #1609
- 광고 구좌의 링크가 변경되어 수정하였습니다.
=> chore: 광고 구좌 변경

functions/coffeechat/[id].ts, functions/coffeechat/edit/[id].ts, functions/coffeechat/index.ts
- close #1626 
- 클라우드플레어 배포를 위한 경로 설정
=> feat: 클라우드플레어 배포를 위한 경로 설정

src/components/coffeechat/detail/index.tsx, src/components/members/detail/GroupSection/index.tsx, src/components/members/detail/ProjectSection/index.tsx
- close #1635
- 도영이가 미리 해준 작업이라서 롤백 진행했습니다, 
- 추가적으로 이쪽 뷰가 변경됨에 따라 여백값이 늘어나야해서 추가적으로 수정해주었어요.
=> revert: 프로젝트, 모임 공통 컴포넌트 롤백

src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx, src/components/coffeechat/detail/CoffeechatContents/index.tsx, src/components/coffeechat/detail/OpenerProfile/index.tsx, src/components/common/form/RHFControllerFormItem.tsx
- close #1638
- 커피챗 상세 qa
- [제안 모달] 플레이스 홀더 수정
- [제안 모달] 신청자가 프로필에 등록한 전화번호가 필드에 자동으로 채워지지 않음 수정
- [타인 상세] 상단 오픈 멤버 정보 - 이메일 길어질 경우 UI 수정
- [타인 상세] 상단 오픈 멤버 정보 - 진행방법 선택했을 경우 노출
- [제안 모달] 커피챗 제안 보내기 버튼 hover, press 상태 반영
=> feat: 커피챗 상세 2차 QA 반영

src/components/coffeechat/detail/RegisterCoffeechatButton/index.tsx, src/components/coffeechat/detail/SeemoreSelect/index.tsx, src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx, src/components/eventLogger/events.ts, src/pages/coffeechat/edit/[id].tsx, src/pages/coffeechat/upload.tsx
- close #1649 
- 커피챗 오픈, 상세 로깅
- 기존 로깅 방식과 동일하게 연결해주었습니다!
=> feat: 커피챗 오픈, 상세 로깅

src/components/coffeechat/CoffeeChatCard/index.tsx, src/components/coffeechat/CoffeeChatCategory/index.tsx, src/components/coffeechat/detail/index.tsx, src/components/members/detail/ProjectSection/index.tsx
- close #1661 
[홈] 최하단 마진 수정 
[홈] 숨김 상태의 내 커피챗 카드 UX writing 오탈자 수정
[타인 상세] (PC, MO 공통) 마진값 수정 / SOPT 활동 정보, 플젝, 모임 타이틀 폰트 크기 수정
=> fix: 커피챗 QA

src/components/coffeechat/Banner/CoffeeChatLottie.tsx, src/components/coffeechat/CoffeeChatCard/index.tsx, src/components/coffeechat/CoffeeChatCategory/index.tsx, src/components/coffeechat/CoffeeRecentChatList/index.tsx, src/components/coffeechat/detail/SeemoreSelect/index.tsx
=> fix: qa 적용

src/components/coffeechat/detail/SeemoreSelect/index.tsx, src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx, src/components/coffeechat/detail/index.tsx, src/components/coffeechat/page/CoffeechatUploadPage.tsx, src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx, src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.stories.tsx, src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.tsx, src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.tsx, src/pages/coffeechat/edit/[id].tsx, src/pages/coffeechat/upload.tsx
- close #1668
- qa 반영
- 쿼리키 무효화가 잘 적용되지 않는 것 같아, 각 쿼리키를 무효화하도록 분기처리
=> feat: 커피챗 qa

src/components/coffeechat/CoffeeChatCard/index.tsx, src/components/coffeechat/detail/SeemoreSelect/index.tsx
- close #
- 커피챗 카드 css를 수정했어요.
=> feat: css 수정

src/components/coffeechat/detail/SeemoreSelect/index.tsx
- close #
- 삭제 시, 쿼리키 무효화가 바로 반영되지 않는 이슈가 있었어요.
- 로컬에선 괜찮고, dev에서는 랜덤으로 재현되었어요... 
- try-catch Promise.all 이용해서 쿼리키 무효화되었을 때 토스트가 오픈되고 홈으로 이동하도록 했어요.
- 정확한 이슈를 찾기가 어려워서 동기적으로 처리해주었어요,
=> refactor: 쿼리키 무효화 반영되지 않는 이슈 수정

src/components/coffeechat/CoffeeChatCard/index.tsx, src/components/coffeechat/CoffeeRecentChatList/index.tsx
=> Hotfix: 커피챗 디자인 QA 수정

src/components/coffeechat/CoffeeChatCard/index.tsx, src/components/coffeechat/CoffeeChatCategory/index.tsx, src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx, src/components/coffeechat/CoffeeRecentChatList/index.tsx
=> hotfix: QA 적용

src/components/coffeechat/upload/CoffeechatForm/constants.ts
- close #1680 
- 커리어 옵션을 추가했어요.
- 공통으로 사용 중이던 constants에 창업 중 추가해주었습니다.
- 추후에 커피챗 홈의 select로 사용 중인 옵션값들을 활용해서 칩을 구현해도 좋을 것 같습니다! 중복되는 constant가 있어보여서요! 추후 작업해보겠습니다~
=> feat: 창업 중 경력 옵션 추가

src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx, src/components/members/detail/MessageSection/MessageModal.tsx, src/components/members/detail/MessageSection/Modal.tsx
- close #1682
- 멤버 탭 쪽지보내기 모달을 mds 디자인으로 변경했습니다.
- 320까지 커버할 수 있도록 반응형처리 했습니다.
430이하로는 모달이 width를 꽉채우고 padding만 유지한채로 화면 너비에 맞추어 줄어들도록 했습니다
https://github.com/user-attachments/assets/7b6357f5-ef6d-46f0-8c74-6b53e30ec827
=> feat: 쪽지 보내기 모달 mds로 변경 및 반응형 처리

src/components/common/Banner/AdsBanner/constants/ads.ts
- close #
- 11월 26일에 광고 종료인 광고를 삭제했어요.
=> feat: 11/26 광고 구좌 변경

src/components/coffeechat/Banner/CoffeeChatLottie.tsx, src/components/coffeechat/detail/OpenerProfile/index.tsx
- close #1698 
스프린트에서의 커피챗 상세 페이지 로직 변경
Link 사용해서 구현했고, mds 적용의 경우에는 현재는 Dialog랑 Select정도인데..Dialog는 현재의 구조에서는 이전에 발생했던 토스 라이브러리와의 충돌로 mds 사용이 불가한 상황이고, Select는 플폼팀이랑 좀 더 논의가 필요할 것 같아서 일단 제외하고 풀리퀘올립니다!
=> feat: 커피챗 상세 페이지 로직 변경 및 리패치

src/components/common/Banner/AdsBanner/constants/ads.ts
- close #1711 
- 광고 구좌 모바일 이미지를 수정했어요.
=> refactor: 광고 구좌 이미지 수정

src/components/common/HomePopup.tsx, src/components/makers/Notifier.tsx, src/components/makers/data/generation35.ts
- close #1736 
hotfix 사항으로 메이커스 36기 모집글을 플레이그라운드에 적용했습니다
=> hotfix: 36기 모집글 등록

src/components/coffeechat/CoffeeChatReview/CoffeeChatReviewCard.tsx, src/components/coffeechat/CoffeeChatReview/CoffeeChatReviewModal.tsx
=> fix: 커피챗 리뷰 등록 qa 적용

src/components/common/Banner/ClosingCeremonyBanner/index.tsx
- close #1753
배너 내 '마이 솝트 리포트 보기'에 /mySoptReport로 네비게이션 하는 로직을 연결했습니다.
=> feat: 종무식 배너에 마이 솝트 리포트 진입점 연결

src/components/mySoptReport/MyReport/index.tsx
- close #1729 
모바일뷰에서 카드가 보여서 보이지 않도록 수정했습니다!
=> hotfix: 카드 보이지 않게 변경

src/components/mySoptReport/MiniReportCard/index.tsx
- close #1729 
playCount -> winCount로 변경
winCount가 두자릿 수 일때의 폰트 크기 변경
=> hotfix: winCount 변경

src/components/common/Banner/ClosingCeremonyBanner/index.tsx
=> feat: 마이 솝트 리포트 오픈 예정 팝업 되돌리기

src/components/common/Banner/ClosingCeremonyBanner/index.tsx
=> feat: mySoptReport 진입점 오픈

src/components/mySoptReport/ReportCard/CardHeader/index.tsx
- image download -> base64로 가져오는 방식으로 변경
- close #1729 
IOS에서 이미지 다운로드가 되지 않는 오류를 수정합니다.
image src로 다운로드 -> base64로 가져오는 방식으로 변경하였습니다.
prod 환경에서 테스트 필요합니다..!
=> hotfix: 마이 플그 활동 유형 IOS에서 다운되지 않는 오류 수정

.github/actions/randomReviewer.js
- close #1774 
랜덤 리뷰어를 36기 회원으로 변경했습니다.
=> chore: 랜덤 리뷰어 리스트 36기 기준으로 변경

src/components/makers/Notifier.tsx, src/components/makers/data/generation36.ts, src/components/makers/data/index.ts
- close #1805 
- 36기 모집 공고 내리기
- 36기 메이커스 팀 정보 수정
=> feat: 36기 메이커스 페이지 업데이트

playground-common/package.json, src/components/common/Header/desktop/DesktopHeader.tsx, src/components/common/Header/index.tsx, src/components/common/Header/mobile/MobileSideBar.tsx, src/components/eventLogger/events.ts, src/constants/links.ts
- close #1826
npm 배포 후 머지하겠습니다!
=> feat: 솝티클 업로드에서 활동후기 업로드로 헤더 변경

src/components/common/HomePopup/HomePopupContainer.tsx
- close #1837
팝업을 보여줄 때 최신기수가 아니면 early return이 되었던 부분을 주석처리 했습니다.
=> fix: 최신 기수 얼리 리턴 해제

src/components/common/HomePopup/HomePopupContainer.tsx, src/pages/index.tsx
- close #1841
- 설문조사 마감기한에 맞춰서 팝업을 내리기 위해서 기존 팝업 노출 코드를 주석처리 했어요
=> feat: 홈팝업 제거

src/components/feed/home/PopularArea/PopularCard.tsx, src/components/feed/home/PopularArea/index.tsx, src/components/feed/home/QuestionArea/index.tsx, src/components/feed/home/SopticleArea/index.tsx
=> fix: 닉네임 말줄임표 추가

src/components/feed/home/PopularArea/PopularCard.tsx
- close #1868
- 모바일에서 데스크탑과 동일하게 말줄임표 기준이 되어있어서 공간이 있음에도 불구하고 말줄임표가 생기는 이슈를 수정했어요.
- 조회수가 4자리수를 넘어가면 밀리기 때문에, 4자리에 크기를 맞춰주었어요,
모바일에서는 width를 남는 모든 공간을 할당해주었습니다.
=> fix: 커뮤니티 홈 모바일 인기글 카드 배치 수정

src/api/endpoint/feed/getPost.ts, src/api/endpoint/feed/getPosts.ts, src/api/endpoint/feed/postVote.ts, src/components/feed/detail/DetailFeedCard.stories.tsx, src/components/feed/detail/DetailFeedCard.tsx, src/components/feed/detail/FeedDetailContent.tsx, src/components/feed/list/FeedListItems.tsx, src/components/vote/RadioBox.tsx, src/components/vote/index.stories.tsx, src/components/vote/index.tsx
=> feat: 투표 조회 및 선택 구현

src/components/feed/page/FeedUploadPage.tsx
- close #1890
- 게시글 작성시 솝티클 카테고리일 경우 이미지 및 투표 미리보기를 제거했어요
- 이전 pr에서 qa를 반영해서 여기서는 하나밖에 안했네요,, 이럴줄 알았으면 이슈 안파는건데 ㅎㅎ
=> fix: sp3 qa반영

src/api/endpoint/feed/postComment.ts, src/components/common/HomePopup/index.tsx, src/components/feed/common/MentionDropdown.tsx, src/components/feed/common/utils/parseMention.tsx, src/components/feed/detail/FeedDetailInput.tsx, src/components/feed/home/PopularArea/PopularCard.tsx, src/components/feed/page/FeedUploadPage.tsx, src/components/feed/upload/types.ts, src/pages/feed/edit/[id].tsx, src/pages/feed/upload.tsx
=> fix: 커뮤니티 언급 필드 누락 해결

src/components/feed/detail/FeedDetailInput.tsx, src/components/feed/page/FeedUploadPage.tsx
=> fix: 언급 알림 정보 필드 추가

src/api/endpoint/feed/getComment.ts, src/api/endpoint/feed/getPost.ts, src/api/endpoint/feed/getPosts.ts, src/api/endpoint/feed/getRecentSopticle.ts
Reverts sopt-makers/sopt-playground-frontend#1915
=> Revert "fix: 커뮤니티 조회 멤버 필드 타입 검증 수정"

src/api/endpoint/resolution/getResolution.ts, src/components/resolution/read/ResolutionReadModal.tsx, src/pages/lucky/index.tsx
=> refactor: 행운뽑기 여부 캐시 업데이트 순서 변경

src/api/endpoint/feed/getComment.ts, src/api/endpoint/feed/getPost.ts, src/api/endpoint/feed/getPosts.ts, src/api/endpoint/feed/getRecentSopticle.ts
Reverts sopt-makers/sopt-playground-frontend#1918
=> Revert "Revert "fix: 커뮤니티 조회 멤버 필드 타입 검증 수정""

src/components/common/Banner/ActiveBannerSlot.tsx, src/components/common/HomePopup/HomePopupContainer.tsx, src/components/common/HomePopup/index.tsx
- close #1928
- 타임캡솝 이벤트가 종료되어 일반 광고 배너로 변경했습니다.
- 추후 다짐메세지 작성 모달을 사용할 가능성이 있어 팝업 코드에서 타임캡솝 관련 코드를 주석처리하였습니다.
=> feat: 타임캡솝 이벤트 종료

src/components/auth/AuthRequired.tsx, src/components/auth/useAuth.ts, src/constants/env.ts, src/constants/links.ts
- close #1939
- prod에서는 인증 없을 시 intro가 아닌 accounts로 리다이렉트
=> feat: fix redirect intro > accounts

src/api/index.ts
=> fix: playground api credentials 삭제

src/api/endpoint/feed/getComment.ts, src/api/endpoint/feed/getPost.ts, src/api/endpoint/feed/getPosts.ts, src/api/endpoint/feed/getRecentSopticle.ts, src/constants/links.ts
- close #1946
- 인증 중앙화를 진행하면서 변경된 member 관련한 response type들을 변경했어요
=> fix: member 정보 관련 zod type 에러 수정

src/components/members/main/MemberList/filters/constants.ts, src/components/members/main/MemberList/index.tsx
- close #1954
인증중앙화로 바뀐 검색 request를 반영했어요
https://www.notion.so/sopt-makers/internal-21476042aac2804e85f3cbbcb150bf98
해당 노션에 정리된 enum으로 변경했어요
정렬순서는 플그에서 따로 처리하고 있기 때문에 기존 값 유지했어요
=> fix: 변경된 멤버 검색 request 반영

src/constants/links.ts
=> fix: 인증중앙화, 플레이그라운드 링크 최신화

src/api/crew/CrewQueryKey.ts, src/api/crew/getCrewPost.ts, src/api/crew/toggleCrewPostLike.ts, src/api/endpoint/feed/getPosts.ts, src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx, src/components/feed/list/CrewFeedList/CrewMeetingLinkRow.tsx, src/components/feed/list/CrewFeedList/index.tsx, src/components/feed/list/FeedCard.tsx, src/components/feed/list/FeedList.tsx, src/constants/links.ts
- close #1953 
- getCrewPost API 연결
- crewFeedList 구현
- CrewMeetingLinkRow 구현 
- CrewPostLike 토글 구현
- 댓글 아이콘 클릭 연결
=> 모임 피드 리스트 구현

.github/workflows/chromatic.yml, .github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml
- close #1962
- development deploy브랜치 main -> develop으로 변경
=> fix: development deploy브랜치 develop으로 변경

src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx
=> 크루 피드 리스트에 공유 링크 변경

src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx
meetingId 를 연결해야하는데 실수로 id를 연결했습니다.
meetingTitle 필드가 새로 생겨서 title 대신에 meetingTItle 필드 연결합니다!
=> Crew 모임 meetingId, meetingTitle 데이터 연결
