sopt-makers/sopt-playground-frontend

- .env.development
- components/auth/identityProvider/useFacebookAuth.ts
- close #69 
저번에 #61 에서 리팩터링 할 때 디렉터리 이름이 바뀌면서 API Route도 같이 바뀌었는데, 이게 반영이 안되어서 페이스북 로그인이 실패하는 현상을 수정했습니다.
추가로 .env.development 파일의 내용이 최신이 아니어서 이것도 수정했습니다.
페이스북 로그인 페이지로 이동할 때 들어가는 콜백 인자의 주소를 변경했습니다.
> fix: 로그인 오류 수정

- components/projects/upload/ProjectGeneration.tsx
- components/projects/upload/ProjectImageSection.tsx
- components/projects/upload/constants.ts
- pages/projects/upload/index.tsx
- close #66 
- 기수 정보는 필수 정보로, 썸네일 이미지는 옵셔널 정보로 수정합니다.
- 기수정보는 체크박스가 체크되어있을 경우 `generation` 기수 값을 서버로 전송하지 않습니다. (`undefined`) 결국 의미상으로만 필수정보라는 뜻만 전달되면 될 것이라고 생각하여 ui 상으로만 필수값으로 표시를 해두고, 실제 로직은 변경하지 않았어요. (`generation?: number, checked: boolean`)
- 썸네일 이미지 쪽은 단순 실수 오타라서.. 수정했습니당
> chore: 프로젝트 업로드 항목 필수 항목 여부 수정

- components/common/Header/Menu.tsx
- next.config.js
- close #44
- `MenuItem`들을 상수화한 다음 map으로 뿌리도록 변경했어요.
- <a>태그 안에 <a>태그를 중첩으로 사용해서 생기는 문제였어요..!! (https://github.com/vercel/next.js/issues/36765)
~- 사실 왜 해결된지 정확히 잘 모르겠어요..😭 기존엔 `router.pathname`이 서버에서 정의되기 이전에의 ui `(isSelected === false)`와 hydration 이후의 ui `(isSelected === true)` 여서 렌더링되는 색상이 달라서 생기는 문제인 줄 알았으나, 바뀐 코드도 사실 원래의 코드와 다를게 없지 않나..? 하는 생각이에요. (코드 정리하려고 저렇게 바꾸고 보니 해당 이슈가 해결되었어요,, 흠)~
- `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.`와 같은 에러가 발생하고 있었는데요([a 태그를 중첩해서 사용하지 않는 이유](https://stackoverflow.com/questions/18666915/why-are-nested-anchor-tags-illegal)), 이 때문에 서버에서 html을 생성할 땐 정상적인 html의 구조대로 렌더링하지만, 브라우저에서 생성할 땐 정상으로 판단하여 그대로 파싱해와서 이 둘의 ui 구조가 달라져서 생기는 이슈입니다.
> fix: next.js hydration ui diff 문제 수정

- components/projects/upload/SignupLink/index.tsx
- components/projects/upload/ToastProvider/index.tsx
- close #59
- https://github.com/sopt-makers/sopt-internal-frontend/pull/54 에서 임의로 했던 부분들 수정
- 복사될 텍스트를 실제 회원가입 링크로 적용
- 디자인 없이 만들었던 토스트 디자인 적용
- 복사될 텍스트를 실제 회원가입 링크로 적용
- 지금 배포돼있는 링크로 했음
- 디자인 없이 만들었던 토스트 디자인 적용 
- 전반적인 스타일 및 애니메이션 예린이가 디자인 해준 것으로 수정
- 복사될 텍스트를 실제 회원가입 링크로 적용
- 건영이가 https://github.com/sopt-makers/sopt-internal-frontend/issues/62 하고 나면 경로 자체가 바뀔수도 있을 것 같고, 도메인 구매하면 또 바꾸어야 합니다
- 도메인 확정되고 나면 상수로 빼면 좋을 것 같어요
스토리북에서 보셔요 ~ !
> 복사될 회원가입 링크 및 토스트 디자인 적용

- components/common/Input/index.tsx
- components/common/TextArea/index.tsx
- components/common/form/RHFControllerFormItem.tsx
- close #84
1. **Input, TextArea 컴포넌트의 count 값이 UI에 업데이트 되지 않는 버그를 고쳤어요**
props가 InputHTMLAttributes을 extends하고 있어서 value와 onChange가 undefined로 덮어씌워지는 것이 문제였습니다
그래서 아래와 같이 Omit으로 props에서 InputHTMLAttributes의 value와 onChange를 빼주는 방식으로 해봤는데 안됐습니다ㅠ
```tsx
export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'> {
error?: boolean;
count?: boolean;
maxCount?: number;
}
export const Input = forwardRef<HTMLInputElement, InputProps>(({ error, count, maxCount, ...props }, ref) => {
const [value, setValue] = useState<string>('');
return (
<>
<StyledInput value={value} onChange={(e) => setValue(e.target.value)} error={error} ref={ref} {...props} />
{count && (
<StyledCountValue>
<Text color={colors.gray100} typography='SUIT_12_M'> …
```
> 프로젝트 업로드 폼 자잘한 버그 fix

- pages/index.tsx
- close #131
- 메인페이지로 접속하면 `/members` 페이지로 리다이렉트 시키도록 했습니다.
- csr에서 useRouter로 구현했는뎅, https://nextjs.org/docs/api-reference/next.config.js/redirects 이 방법은 우리 배포방식엔 맞지 않아 그렇게 작업했습니당
> feat: 메인페이지로 접속 시 member 페이지로 redirect

- pages/members/detail.tsx
- close #142 
프로필 상세 이름 옆에 파트 정보가 뜨도록 했어요
part가 빈 string으로 들어가는 경우가 있는지 uniq 결과물에 빈 string이 있어서 일단 걸러줬습니다
시간 없어서 일단 이대로 배포하는데 요 케이스 원인 나중에 찾아내야 할 것 같아요
> fix: 이름 옆 전공 대신 파트 정보 뜨도록

- apiHooks/members.ts
- pages/members/detail.tsx
- pages/members/index.tsx
- utils/index.ts
- close #151 
멤버 프로필을 누르면 기존에는 사이트가 새로고침 되는 현상이 있었는데, 이 현상을 수정했습니다!
- 기존에 a 태그로만 구현했던 링크를, [next/link](https://nextjs.org/docs/api-reference/next/link) 로 감쌌어요.
- query의 변화를 잘 감지하도록 이전 PR에서 만들었던 `useStringRouterQuery` 훅을 사용해서 쿼리를 가져왔어요.
- id가 다른 쿼리 요청이 캐싱되지 않도록 `useQuery`의 첫번째 인자에 id를 추가했어요.
> fix: 멤버 프로필 링크에서 새로고침되는 현상 수정

- components/common/EditableSelect.tsx
- components/common/Select/index.tsx
- components/members/upload/AddableItem.tsx
- components/members/upload/AdditionalInfoFormSection.tsx
- components/members/upload/forms/EditableSelect.tsx
- close #156 
프로필 업로드 페이지의 링크 카테고리 select에 '직접입력' 옵션을 추가하고, 해당 옵션 선택 시 직접 편집 가능하도록 했어요
EditableSelect 컴포넌트 구현하여 적용
대략적인 컨셉은 아래와 같고 더 자세한 동작 방식은 코드 봐주세요!
- 마지막 옵션이 기본적으로 '직접입력'
- select 위에 input을 올려, select의 value가 input에 보이도록 함 (혹시 모를 스타일 깨짐 방지를 위해 select의 글씨는 투명색으로 설정)
- '직접입력' 옵션 선택 시 input의 `readonly`가 `false`, 그 외는 `true`
아무래도 select가 바뀌면 실제로 보여지는 input value를 set하다 보니 일반 select에 비해 딜레이가 조오오금 있어요
그리고 혹시 EditableSelect 컴포넌트를 더 개선해볼 수 있지 않을까 생각이 들긴 하는데 일단 동작은 잘해서 시간 관계상 이렇게 올려요 ,,
(현재 이 컴포넌트를 사용 중인 곳이랑 독립성이 보장 됐는지, 좋은 인터페이스를 가지고 있는지 고민을 덜 해본 것 같아요
나중에 개선 시도 해서 성공하면 아예 common으로 빼도 좋지 않을까 생각합니당)
\+ 커밋 몇 개 더 해서 조금씩 개선해보긴 했습니다!
UI 로직이랑 state 관리 둘 다 잘댑니다
https://user-images.githubusercontent.com/73823388/201295916-b15f93cf-5e31-4ff8-a19a-e28f24829be5.mov
EditableSelect 아이디어 얻음 …
> feat: 프로필 업로드 폼 > 링크 카테고리 select > '직접입력' 옵션 선택 시 편집 가능하도록

- components/members/upload/AdditionalInfoFormSection.tsx
- pages/members/upload.tsx
- close #
- 멤버 업로드 이슈 대응하다가 코드를 날려먹어서 다시 복구합니당..ㅎ
- 링크쪽 `placeholder`가 인스타그램이 선택된줄 착각하는 유저들이 있어서 수정했어요(예린, 주영과 싱크맞춤)
> fix: 누락되었던 멤버 수정 코드 복원

- components/auth/register/VerifyByEmail.tsx
- components/common/SquareLink/index.tsx
- components/common/SquareLink/style.ts
- components/debug/SideToggleButton.tsx
- pages/auth/verify.tsx
- close #207 
- 가입 이메일 인증 화면에서 탭 포커스가 이상해지는 현상을 수정했어요.
- 디버그 패널 버튼이 포커스 잡히는 현상을 수정했어요.
- (겸사겸사) 가입 이메일 인증 화면이 모바일에서 가운데 나오지 않는 현상을 수정했어요.
- (겸사겸사) 버튼과 링크의 hover 트랜지션을 추가했어요.
a 태그에 href가 없으면 포커스가 잡히지 않는 특징이 있다고 해요.
https://ask.metafilter.com/359769/Why-is-the-tab-key-skipping-these-links
이 특징때문에 제대로 포커스가 잡히지 않았어서, button 태그로 바꿀 수 있게 만들었어요.
> fix: 회원 인증 화면 포커스 문제 수정

- components/auth/AuthRequired.tsx
- pages/index.tsx
- close #219
- members 리다이렉트를 else 문으로 옮겼습니다.
> fix: 토큰 없을 때 리다이렉트 시 멤버 페이지가 잠깐 나왔다 로그인 페이지로 가는 버그 수정

- components/common/Header/index.tsx
- close #201 
- 데스크톱 화면에서 드롭다운 바깥을 누를시 닫히지 않는 현상을 수정했어요.
- 모바일 화면에서 메뉴 바깥을 누를시 닫히지 않는 현상을 수정했어요.
- route가 이동할 때 자동으로 메뉴와 드롭다운이 닫히도록 수정했어요.
- 모바일 화면에서 헤더의 사용자 버튼이 보이지 않도록 수정했어요.
- ![image](https://user-images.githubusercontent.com/36122585/203557712-9f6c9e46-0420-4c8a-83c1-cd1f9d1d3302.png)
- (겸사겸사) 드롭다운과 헤더에 애니메이션을 추가했어요.
- 드롭다운이나 메뉴 바깥의 어디든지 눌러도 닫힐 수 있도록 window에 클릭 핸들러를 붙였어요.
> fix: 드롭다운과 메뉴 닫히지 않는 버그 수정

- components/members/upload/BasicFormSection.tsx
- components/members/upload/constants.ts
- components/members/upload/schema.ts
- close #204 
yup schema에 생일 필드 유효성 검사를 추가해서 잘못된 형식일 경우 유저에게 알려줄 수 있도록 했어요
(기존에는 노티 없이 올바른 형식으로 알아서 변환 후 submit)
년, 월, 일 중 값 하나라도 있는 경우에(생일이 필수 항목이 아니기 때문에) 아래처럼 동작하도록 스키마를 수정했습니다
- 나머지 두 가지 값 모두 required
- 각각에 맞는 정규표현식에 맞는지 검사
https://user-images.githubusercontent.com/73823388/203329100-25d6f350-6324-4af1-a080-f6f2c6325ba2.mov
> feat: 프로필 업로드 > 생일 유효성 검사 추가

- components/members/upload/AdditionalInfoFormSection.tsx
- components/members/upload/schema.ts
- close #223 
링크 유효성 검사를 추가했습니다
title과 url 중 하나라도 값이 채워져 있으면 나머지 값을 required로 만들어줬고,
url은 url 형식을 지키도록 했습니다
yup schema를 수정했는데,
특이 사항은 EditableSelect가 register의 onChange를 이용하지 않아서 errors 객체에 바로 반영이 안되고 새로 submit을 해야만 반영이 되는 현상이 있었습니다
이를 useForm(useFormContext)의 trigger를 이용해 해결했습니다
참고 링크 - https://github.com/react-hook-form/react-hook-form/discussions/4110
\* EditableSelect는 '직접 입력'외의 옵션들은 select event, '직접 입력'은 input event를 통해 value를 set합니다. 따라서 한 가지 타입의 이벤트를 파라미터로 받는 register의 onChange는 활용할 수 없습니다
https://user-images.githubusercontent.com/73823388/203732506-7a20c4b3-c959-4eca-bd56-b91b39607d9d.mov
> feat: 프로필 업로드 > 링크 유효성 검사 추가

- components/projects/upload/utils.ts
- close #
- 기존 클라에서의 날짜 형식(`YYYY.MM`)과 마이그레이션 한 서버의 날짜 형식(`YYYY-MM-DD`)이 상이해서 따로 유틸함수를 이용해서 형식을 맞춰주고 있었어요.
- 이 과정에서 `YYYY.MM`은 dayjs의 기본 format이 아니어서 변환하는 과정에서 `2021-01-01`로 넘어가고 있더라구요 ㅠ
- dayjs playground에선 잘 테스트가 됐었는데, 요게 [플러그인](https://day.js.org/docs/en/plugin/custom-parse-format)이 있어서 그런거였어서 이를 추가했어요. (`customParseFormat`)
> fix: dayjs custom format 추가

- components/makers/data/generation1.ts
메이커스 멤버 정보가 잘못 들어가서 잘못된 사진이 노출되었던걸 수정했어요.
> fix: 잘못된 메이커스 멤버 정보 수정

- components/auth/AuthRequired.tsx
- components/auth/register/RegisterFinished.tsx
- components/auth/register/VerifyByEmail.tsx
- components/auth/useAuth.ts
- components/common/Footer/index.tsx
- components/common/Header/index.tsx
- components/common/LegacyHeader/index.tsx
- components/debug/panels/NavigationPanel.tsx
- components/makers/MakersMembers.tsx
- components/members/main/MemberDetail/index.tsx
- components/members/main/MemberList/index.tsx
- components/projects/main/ProjectCard.tsx
- components/users/detail/MemberProjectCard.tsx
- constants/links.ts
- pages/auth/callback/facebook/login.tsx
- pages/auth/callback/facebook/register.tsx
- pages/auth/login.tsx
- pages/index.tsx
- pages/makers/index.tsx
- pages/members/detail.tsx
- pages/members/upload.tsx
- pages/projects/detail.tsx
- pages/projects/upload/index.tsx
- close #243 
기존에 매번 리터럴로 사용하던 Playground 내부 URL 주소들을 한곳에 모았어요!
`constants/links.ts` 파일에 사이트 내부 URL 정보를 반환하는 함수들을 모아놓은 `playgroundLink` 객체를 생성했어요.
> refactor: 사이트 내 URL 모으기

- components/auth/identityProvider/google/useGoogleAuth.ts
- components/auth/register/Register.tsx
- pages/auth/login.tsx
아직 완성되지 않은 구글 로그인을 숨기는 기능을 구현했어요. 
env 값에서 `NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID` 값을 빈 문자열로 만들면 구글 로그인을 숨길 수 있어요!
> feat: 구글 로그인 숨김 추가

- components/members/main/MemberList/index.tsx
멤버 프로필을 아직 등록하지 않았을 때 표시하는 환영 메세지의 하단 여백 버그를 수정했어요!
@juno7803 가 작업했던 부분이지만, 수정에 필요한 작업량이 많지 않아서 빠르게 대신 수정했어요!
**Before**
**After**
> fix: 환영 메시지 밑 여백 수정

- api/members/index.ts
- apiHooks/members.ts
- components/common/ResizedImage/index.tsx
- components/makers/MakersMembers.tsx
- components/members/main/MemberList/index.tsx
- hooks/useEnterScreen.ts
- hooks/useIntersectionObserver.ts
- close #279 
- close #291 
- 무한스크롤을 구현했어요! 근데 서버쪽 cursor에 잘라온 마지막 멤버의 id를 넣어주어야 정상적으로 동작을 해서 이렇게 구현했어요.
- useIntersectionObserver를 추가했구, 마지막 요소가 뷰포트에 들어오게 되면 url을 바꿔주고, url의 searchParam을 읽어와서 서버쪽으로 요청하도록 했어요.
- url로 컨트롤 하는 이유는 브라우저 스택에 쌓아서 #291 와 같은 문제를 해결하기 위함입니당
- 데이터가 좀 더 많은 곳에서 테스트해보고 싶은데, 유저가 적은 시간대에 프로덕션에 배포해서 테스트 해보던가 하려구 해용..
- => 요 부분 커비가 알려준 방법으로 로컬에서 프로덕션 바라보도록 수정하여 테스트 했음! [참고 스레드](https://sopt-makers.slack.com/archives/C044JFKAE2X/p1672074217173429?thread_ts=1672073631.347749&cid=C044JFKAE2X)
요거 마지막에 api 호출을 한번 더 하는데, 서버쪽에 마지막 페이지인걸 알려달라는 값을 요청해둔 상태라서
그게 추가되면 마지막 api 호출도 막을 수 있도록 변경할게요! @Tekiter 
https://user-images.githubusercontent.com/26808056/209898739-66347598-1178-4bde-9427-a2c8e5f8506f.mov
> feat: 무한스크롤 구현, 필터 queryParams로 교체

- components/members/main/MemberDetail/index.tsx
- close #329
경력이 없을 수 있는데, 없는 경우 빈 사각형 필드가 보이는 버그를 해결했습니다.
> fix: 경력 없을 경우 빈 필드 안보이게

- components/projects/upload/MemberForm/MemberSearch.tsx
- close #
- `imageUrl`이 `null | string` 타입인데, 빈 스트링이 들어간 경우가 있어서 이를 대응합니다.
> fix: 이미지가 빈 값일 경우 기본 이미지 보여지도록 대응

- styles/global.ts
- close #340 
글로벌 스타일에 type="number"인 input 화살표, 스피너 뜨지 않도록 하는 코드를 추가했어요
[참고](https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp)
크롬
사파리
> fix: type="number"인 input 화살표, 스피너 뜨지 않도록

- components/makers/MakersMembers.tsx
- pages/makers/index.tsx
- close #379 
- clode #362 
기존에는 메이커스 소개 페이지에서 멤버들에 대한 프로필사진, 기수, 직장 정보를 프론트엔드에서 CSR로 처리하고 있었어요. 그런데 플레이그라운드에 등록된 멤버의 수가 점점 많아지면서, 이 데이터를 불러오는 게 점점 더 큰 오버헤드가 되어갔어요. 이 문제를 궁극적으로 처리하기 위해서는 메이커스 멤버 정보를 주는 서버 API가 만들어지면 되는데, 현 상황상 새로운 API가 생기는 데에는 시간이 좀 걸릴 예정이에요. 
그래서 이 문제를 프론트엔드 쪽에서만 처리하려고 해요. Next.js에서는 [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props)라는 기능을 제공하는데, 이를 활용하면 데이터를 페이지를 빌드할 때 가져와서 미리 집어넣을 수 있어요. 따라서 이 PR에서는 클라이언트에서 멤버의 정보를 가져오지 않고, 빌드 타임에 가져와 미리 집어 넣음으로써 로딩 속도를 최적화 하고 있어요.
이 방식을 사용했을 때, 데이터가 변경되면 매번 새로 빌드하고 배포해야 정보가 반영된다는 단점이 있어요. 그러나 메이커스에 소속된 멤버들의 정보는 아주 가끔 바뀌고, 그마저도 현재 구조 상 멤버 정보를 변경하면 어차피 새로 빌드하고 배포해야 해요. 따라서 이 단점을 상쇄할 수 있어요. 또한 멤버들의 프로필 사진, 기수, 직장 정보가 바뀌었을 때 바로 반영이 안된다는 단점이 있어요. 그러나 이 상황이 자주 일어나지도 않고, 만약 그렇다고 해도 슬랙으로 메이커스 멤버의 요청을 받아 바로 …
> feat: 메이커스 멤버 소개 최적화

- components/common/Header/mobile/MobileSideBar.tsx
모바일에서 사이드바 프로필 이미지가 넘치게 나오던 현상을 수정해요.
->
> fix: 모바일 프로필 사진 오류

- components/auth/register/Stepper.tsx
- components/auth/register/VerifyByEmail.tsx
- components/layout/FullScreenLayout.stories.tsx
- components/layout/FullScreenLayout.tsx
- components/layout/index.tsx
- pages/auth/login.tsx
- pages/auth/register-finished.tsx
- pages/auth/register.tsx
- pages/auth/verify.tsx
인증 화면에서 컴포넌트가 위로 딱 붙는 현상을 수정해요.
> fix: 인증 화면 여백 수정

- components/members/upload/BasicFormSection.tsx
ㅠㅠ 휴대폰 번호 input에 https://github.com/sopt-makers/sopt-playground-frontend/pull/328 에서 넣었던 type=number를 삭제했어요
저는.. 이 설정 하면 숫자 아닌 값은 안 들어가는지 몰랐습니다 .......
`-`가 들어가야 하는데 `-` 넣으면 value가 바로 빈 값이 돼요 (UI 상으로는 문제 없어서 발견 못했습니다 ..)
참고로 프로젝트에도 하나 type=number로 했는데 거기는 `.` 하나가 들어가야 하고, 소수점 겨냥인지 `.` 하나는 들어간다고 하더라구요
그래서 문제가 없습니다 실제로 수정도 잘 돼요!
> fix: 프로필 수정 > 휴대폰 번호 수정 안되는 버그 fix

- components/members/main/MemberDetail/index.tsx
- close #388
프로필 상세페이지에서 빈 항목일 경우 해당 영역이 보이지 않도록 했어요.
- 빈 항목일 경우 라벨 숨기기
- 섹션 전체가 빈 항목일 경우 섹션 자체를 삭제하기
- 전화번호와 이메일 사이 디바이더 둘 중 하나라도 빈 값이면 보이지 않도록 하기
- 열심히 &&로 조건부렌더링 해주었어요. 그런데 중복 코드가 많아지고 코드가 좀 더러워져서 추후에 infoContainer와 infoItem을 활용해 빈 항목일 경우 숨기는 로직은 컴포넌트 내부로 숨기도록 리팩토링 하면 좋을 것 같아요.
> fix: 프로필 상세 > 빈 항목일 경우 해당 영역 없애기

- components/members/detail/MemberProjectCard.tsx
- close #418 
프로필 상세 > 프로젝트 카드 이미지 스타일 변경
object-fit: cover 추가
before
after
> fix: 프로필 상세 > 프로젝트 카드 이미지 비율 깨지지 않도록

- components/common/Banner/RecruitingBanner/index.tsx
- components/common/Header/index.tsx
- components/common/Responsive/Responsive.stories.tsx
- components/common/Responsive/Responsive.tsx
- components/common/Responsive/ResponsiveProvider.tsx
- components/common/Responsive/context.ts
- components/common/Responsive/index.tsx
- components/layout/HeaderFooterLayout.tsx
- hooks/useMediaQuery.ts
- package.json
- pages/_app.tsx
- yarn.lock
기존에 모바일에서 새로고침 하거나 접속하면 데스크톱에서만 보여야 할 컴포넌트가 잠깐 노출되는 문제가 있었어요.
원인은 `useMediaQuery` 훅이었는데요, 이 훅은 useEffect에서 현재 화면 사이즈를 검사한 뒤 boolean 값을 반환하는 함수에요. 그런데 이 부분이 SSR/SSG 환경인 Next.js에서 문제가 되었어요. 서버 사이드에서는 useEffect를 실행시키지 않기 때문에 `useMediaQuery` 훅의 반환값은 항상 false 에요. 따라서 만약 `isMobile = useMediaQuery(...)` 형태로 사용했을 시, 페이지에 처음 접속 시엔 항상 데스크톱 화면의 컴포넌트가 먼저 렌더링돼요. 그래서 클라이언트에서 hydration이 일어나고 useEffect가 실행되고 변경된 state로 다시 렌더링 할 때 까지 데스크톱 화면의 컴포넌트가 노출돼요.
그런데 서버에서는 (당연히) 브라우저 화면 크기 정보가 없기 때문에 무엇을 먼저 렌더링 해 놓을지 판단할 수 없어요. 따라서 이를 해결하기 위해서는 서버 사이드에서 모든 화면에 대한 컴포넌트를 미리 렌더링 시켜놓을 필요가 있어요. 그리고 적절한 CSS 미디어 쿼리를 해당 렌더링된 두 버전의 컴포넌트에 적용해놓으면, 초기 렌더링시 유저 눈에는 알맞는 버전의 컴포넌트만 보일거에요.
그래서 이 동작을 구현하는 `Responsive` 컴포넌트를 만들었어요.
그런데 여전히 실제로는 두 버전의 컴포넌트가 DOM 트리에 존재해요. 하나는 필요 없기 때문에 useEffect가 실행될 때 다시 제거해 주면 돼요. 이때 안쓰는 컴포넌트를 제거하는 …
> fix: 모바일 접속시 깜빡임 수정

- pages/makers/index.tsx
기존에 메이커스 멤버의 정보를 빌드 시점에 가져와서 메이커스 소개 페이지를 SSG하고 있었어요. 그런데 이 과정에서 의도치 않게 모든 멤버의 목록을 가져와 페이지의 용량을 증가시키는 문제가 있어 이를 해결했어요.
prop에 멤버 정보를 넘기기 전에, 메이커스 멤버들의 정보만 필터링한 후 전달해요.
> fix: 메이커스 멤버 정보 데이터 최적화

- functions/members/[id].ts
- functions/projects/[id].ts
- tsconfig.json
- close #455
#440 에서 한 작업에 약간의 버그가 있었어요. projects/* 에 대한 경로를 모두 projects/[id].html 로 보내주도록 했는데, projects/upload 경로가 있을 수 있다는 것을 생각하지 못했어요. 따라서 projects/ 뒤에 오는 param 이 숫자 문자열 일때만 projects/[id].html 로 보내주도록 변경했어요. members 에 대해서도 동일해요.
> fix: 다이나믹 라우트 버그 수정

- components/members/main/MemberList/index.tsx
무한 스크롤이 안되는 버그를 긴급 수정했어요.
이전 PR의 스크롤을 항상 보이게 하는 코드때문에 화면 내림을 감지하는 div가 화면 밖으로 넘어가버리는 문제가 발생했어요. 이를 해결하기 위해 감지 div의 높이를 키웠어요.
> fix: 무한 스크롤 버그 수정

- components/eventLogger/providers/AmplitudeProvider.tsx
- close #458 
초기 JS 번들에 불필요하게 들어있던 Amplitude 를 Lazy Load 되도록 변경했어요. 그 결과, 초기 JS 크기를 21KB 줄일 수 있었어요.
AmplitudeProvider 에서 실제 amplitude 모듈을 await import 구문을 사용해서, 클라이언트 타이밍에 로드해요.
**Before**
**After**
> refactor: Amplitude 지연 로딩

- components/projects/form/ProjectForm.tsx
- components/projects/form/fields/GenerationField.stories.tsx
- components/projects/form/fields/GenerationField.tsx
- components/projects/form/schema.ts
- close #
- 기수 폼을 추가했어요!
- 기존엔 `generation`, `checked`를 프로퍼티로 가진 object로 검사했지만, `string` 타입의 `generation` 을 받도록 간단하게 변경했어요.
- `Select` 컴포넌트의 기본 값은 `''` 빈 스트링을 줘야 하기 때문에 (https://developer.mozilla.org/ko/docs/Web/HTML/Element/select) `generation`을 **선택 안함** 상태로 초기화 해주기 위해 string 타입으로 두었고, 서버로 전송할 땐 기존처럼 `number | undefined` 타입으로 변환해서 보낼거에요.
> refactor: GenerationForm 리팩토링

- api/makers/index.ts
- api/makers/types.ts
- pages/makers/index.tsx
메이커스 정보를 가져오는 엔드포인트를 새로 생성된 `/makers/profile` 엔드포인트로 변경했어요.
> feat: 메이커스 정보 엔드포인트 변경

- components/common/Header/mobile/MobileSideBar.tsx
- close #477
모임 페이지에서 모바일 헤더 프로필 사진이 이상하게 나오는 오류를 해결했어요.
**AS-IS**
**TO-BE**
> fix: 모바일 헤더 프로필 이미지 수정

- components/members/detail/ActivityBadge.tsx
- components/members/detail/CareerItem.tsx
- components/members/detail/MemberProjectCard.tsx
- components/members/detail/constants.ts
- components/members/detail/types.ts
- close #494
프로필 업로드와 디테일 타입 의존성을 분리했어요
디테일 쪽에서 가져다 쓰고 있던 업로드 타입을 디테일 폴더 내부에 재선언 했습니다
아무래도 api 타입 의존성까지 해결해야 저희가 원하는 완벽히 관심사가 분리되어 변경 용이한 구조를 가질 수 있을 것 같네요 ㅠ!!
해당 작업 하면서 types.ts 파일이 복잡해지면 types/index.ts, types/project.ts 이런 식으로 프로젝트 타입과 프로필 디테일 자체의 타입을 분리해 선언하면 좋을 것 같습니당
> refactor: 프로필 업로드와 디테일 타입 의존성 분리

- components/members/upload/BasicFormSection.tsx
이미지 업로더에 프리뷰가 안 뜨던 이슈 해결입니다!
isEdit(업로드 페이지에 합쳐져 있던 수정 관련 로직)의 잔재가 남아있던 것이 문제였습니다 ~
> fix: 업로드 페이지에서 수정 로직 분리 덜 된 작업 추가

- components/members/upload/TmiSection/FavorToggle.tsx
- components/members/upload/TmiSection/index.tsx
- components/members/upload/TmiSection/types.ts
- components/members/upload/types.ts
- #508
TMI 섹션에 '나는 어느 쪽?' 항목 추가
MBTI 항목에 비해 의존성 없이 잘 만든 것 같은데 요 비슷한 방식으로 MBTI 항목 리팩토링 하면 좋을 것 같습니다 ㅎㅎ
TMI 섹션에 항목 하나씩 채워가는 중이고 페이지 컴포넌트에는 아직 안 올렸습니다 
스토리북 `members/upload/TmiSection` 고고링
> feat: 프로필 업로드 > TMI 섹션에 '나는 어느 쪽?' 항목 추가

- components/auth/states/lastLoginMethodAtom.ts
- pages/auth/callback/facebook/login.tsx
- pages/auth/callback/facebook/register.tsx
- pages/auth/callback/google/login.tsx
- pages/auth/callback/google/register.tsx
- pages/auth/login.tsx
- close #526 
마지막으로 로그인한 방법을 표시하도록 만들었어요!
로그인이나 회원가입 성공시에 로컬스토리지에 어느 방법으로 했는지를 저장하고, 로그인 화면에서 띄워주도록 만들었어요.
> feat: 마지막 로그인 메시지 추가

- components/members/main/MemberDetail/index.tsx
- close #544 
프로필 상세 페이지에서 이메일을 등록하지 않은 유저는 쪽지 영역이 안 보이도록 했어요
- 작업 배경 이슈에 써놨습니다 ~
- 개발 서버에 이메일 없는 유저가 없어서 테스트를 못해봤어요 그래서 로컬에서 임의로 스키마 조작해서 개발 서버의 제 프로필 이메일 없애놨으니까 머지하고 개발 환경에서 다른 유저가 제 프로필 확인해봐주면 될 것 같습니당
> feat: 프로필 상세 > 이메일이 있어야 쪽지 보낼 수 있도록 하기

- components/members/main/MemberDetail/InterestSection.tsx
- components/members/upload/forms/CountableTextArea.tsx
- components/members/upload/sections/TmiSection/index.tsx
- close #555
상세는 line height 추가했고
수정/업로드는 textarea를 CountableTextarea 컴포넌트로 바꿨어요
CountableTextarea 컴포넌트 스타일 설정 방법 좋은 방법 같진 않은데 더 고민할 체력이 없어서 일단 이렇게 했습니다 쉬고 싶허요 ... 머지하기 전까지 더 좋은 방법 떠오르면 고치러 올게요
before
after
> fix: 프로필 자유로운 자기소개 > 상세 스타일 버그 fix, 수정/업로드 글자수 제한

- components/common/form/FormCollapsible.tsx
- components/members/upload/sections/CareerFormSection.tsx
- pages/members/upload.tsx
- close #557
- 디자인을 잘못봐서 `<FormAccordion />`쪽에 border-bottom을 추가했다가, 그냥 `<Divider />`를 추가하는 것으로 바꿨어요.
- header를 받도록 변경해서 바깥에서 주입하는 식으로 모바일 분기처리를 추가했어요.
https://user-images.githubusercontent.com/26808056/227706717-4bc10395-c114-4586-9a4a-2fdd17b58b5a.mov
> feat: FormAccordion 이용해서 커리어 섹션 모바일 접기 대응

- components/members/detail/InfoItem.tsx
- components/members/main/MemberDetail/InterestSection.tsx
- close #586
아래처럼 생긴 프로필 항목의 값들을 모두 여러 줄을 고려한 line-height로 통일했어요
현재 대부분의 프로필 항목이 여러 줄이 되도록 길게 입력할 수 있는 상태인데 '자유로운 자기소개' 항목만 여러 줄을 고려한 line-height 값이 적용돼있는 것이 어색하여 디자이너와 상의하여 수정했어요
> fix: 프로필 상세 > line-height 통일

- components/members/detail/PartItem.tsx
- close #610 
멤버프로필의 SOPT 활동 정보의 활동한 프로젝트가 모바일에서 화면을 넘어가버리는 문제를 수정했어요.
flex-wrap을 줬어요!
> fix: 활동정보 모바일 스타일 수정

- components/common/Toast/providers/ToastProvider.tsx
- close #652 
푸터가 없을 때 만들어진 토스트라 푸터와 너무 붙어있어서 bottom 값을 조정했습니다!
간단한 스타일 변경이라 그냥 바로 머지할게용
https://user-images.githubusercontent.com/73823388/233240898-dd238b82-ceed-4d80-8e2c-42a4be83626f.mov
> fix: 푸터에 맞춰 토스트 위치 변경

- components/members/detail/InterestSection/index.stories.tsx
- components/members/detail/InterestSection/index.tsx
- components/members/detail/MemberDetail.tsx
- components/members/detail/MessageSection/index.tsx
- close #655 
다른 섹션처럼 MemberDetailSection 스타일 컴포넌트를 베이스로 사용하도록 했어요!
(InfoContainer는 MemberDetailSection의 옛버전입니당)
> refactor: 프로필 디테일 > InterestSection 다른 섹션과 구조 통일

- components/members/detail/constants.ts
- components/projects/form/fields/CategoryField.tsx
- components/projects/upload/ProjectCategory.tsx
- components/projects/upload/constants.ts
- close #662 
[작업 배경 슬랙 스레드](https://sopt-makers.slack.com/archives/C04RVNVRLLA/p1682402898459319)
프로덕션에 기타 카테고리로 올라간 프로젝트가 없어서 간단히 상수만 수정했습니다~
관련 상수가 여기 저기 흩어져 있는데 싱글 소스로 관리돼야 하는 것 아닌지 고민이 되네용
요번 작업은 직접 굉장히 꼼꼼히 빠진 곳이 없는지 확인했습니다
> chore: 프로젝트 카테고리 기타 -> 사이드 프로젝트 워딩 변경

- api/members/type.ts
- api/projects/type.ts
- components/members/detail/MemberDetail.tsx
- components/projects/upload/constants.ts
- close #664 
기존 코드가 솝커톤, 앱잼 외의 카테고리는 표시가 안되도록 돼있어서 모든 카테고리를 반영하도록 수정했습니다!
convertProjectType 함수를 수정했어요.
현재 api 타입과 컴포넌트 타입의 의존성으로 인해 타입의 신뢰성이 좀 떨어져서 타입 가드를 만들어서 검사해줬어요 (isCategory)
혹시 카테고리가 추가됐을 때에 빠뜨릴까봐 never 타입으로 exhaustive check도 해줬습니다!
> fix: 프로필 상세 > 프로젝트 뱃지에 프로젝트 카테고리 모두 표시되도록

- api/members/type.ts
- components/members/detail/types.ts
- components/members/upload/constants.ts
- components/members/upload/types.ts
- pages/members/edit.tsx
- close #658 
Career 타입의 endDate 필드가 string | null 이었는데, 이는 boolean 타입의 isCurrent 필드에 의해 정해지는 것이었는데,
isCurrent - true, endDate - null / isCurrent - false, endDate - string
위 2가지 외의 쌍은 존재하면 안됐습니다.
따라서 기존처럼 endDate 필드를 유니온 처리하는 것이 아닌, Career 타입 자체를 구별된 유니온으로 처리하여 타입의 정확도를 높였습니다.
> refactor: Career 타입 구별된 유니온으로 정확한 타이핑 할 수 있도록 하기

- components/members/detail/InterestSection/index.tsx
- components/members/detail/MemberDetail.tsx
- close #687
- 프로필 상세 > 나는 어느 쪽? 항목 디자인을 기존 디바이더로 텍스트가 나뉜 형태에서 블록 형태로 바꾸었어요.
- 디자인 요구 사항: 모바일에서는 한 줄에 최대 4개가 기본 값, viewport가 4개 너비보다 작아지면 그에 맞춰 한 줄에 들어가는 개수도 줄어들어야 함. => max-width 설정
- 해당 디자인이 주소 뱃지랑 같은 형태인데 스타일 요소가 다른 것들이 있어서 디자이너와 얘기해서 맞추었어요. (AddressBedge)
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/54764619-42ee-4cae-a459-9feb01f02032
> feat: 프로필 상세 > 나는 어느 쪽? 항목 디자인 변경 대응

- api/endpoint_LEGACY/members/index.ts
- components/members/main/MemberList/index.tsx
- close #
- 무한스크롤을 할 때 다음 커서를 지정하는 방식이 마지막 사람의 id를 기반으로 동작하도록 했어요. (id를 기반으로 커서를 동작시킨다 그랬었나..? 서버쪽 구현에 맞춰서 id가 incremental인 것을 이용해 hacky하게 구현했었습니다.)
- 그래서 일단 등록순 필터는 제거하고 orderBy=2(예전등록순)으로 고정하여 임시 배포합니다.
> fix: 등록순 필터 주석처리

- components/common/Carousel/Body.tsx
- components/common/Carousel/index.stories.tsx
- components/common/Carousel/index.tsx
- components/common/Carousel/useCarousel.ts
- components/mentoring/MentoringCard/index.stories.tsx
- components/mentoring/MentoringCard/index.tsx
- hooks/usePagination.ts
- public/icons/icon-arrow-purple.svg
- close #703
1. 멘토링 카드 마크업
2. 캐러셀 구현
캐러셀 구현 방식
- usePagination과 useCarousel로 관련 로직을 모듈화 함.
- 애니메이션은 framer-motion의 AnimatePresence를 활용했는데, 다음 페이지로 넘어가는 과정에서 이전 컴포넌트와 현재 컴포넌트가 둘 다 마운트 돼있어 레이아웃이 깨지는 현상이 있었음. 이를 framer-motion의 usePresence를 활용하여 exit 될 때 position: absoulte로 만들어 해결함. (참고로 이 훅을 사용하지 않고 useEffect만을 이용해서 스타일을 변경하는 방법은 의도대로 동작하지 않았음.)
캐러셀 관련하여 고민했던 요소들입니다
- 캐러셀을 직접 구현할 것이냐, UI 라이브러리를 사용할 것이냐
일단은 각종 까다로운 처리를 최적화 해서 해주고 있는 UI 라이브러리를 사용하는 것이 효율적일 것 같아서 찾아봄.
but 요구 사항에 맞추어 커스텀 하기 쉬운 라이브러리를 찾지 못함.
따라서 애니메이션만 현재 잘 활용하고 있는 framer-motion을 통해 구현하고 그 외는 직접 구현하기로 함.
- 캐러셀 컴포넌트를 완전히 headless로 구현할 것이냐, 현재 나온 디자인 의존성 있게 구현할 것이냐
고민을 정말 많이 했지만 일단은 후자로 구현했으며, 필요한 경우 최대한 모듈화 하여 재구성하기 좋도록 구현함.
추후 headless로 개선할 의지 있음.
\+
arrow icon svg 파일을 새로 추가하지 않고 기존 파일을 활용하려고 했는데
`안 그래도 아래와 같은 논의가 있어서 대대적으로 svg …
> feat: 멘토링 카드 및 캐러셀 구현

- api/endpoint_LEGACY/members/index.ts
- components/members/main/MemberList/index.tsx
- components/members/main/hooks/useMemberProfileQuery.ts
- close #
- 서버에서 cursor로 구현된 부분이 page의 lastMember의 Id를 받는식으로 되어있어서 (id가 incremental이고, 정렬이 있기 이전이라 가능) 이를 서버에서 수정해주었어요.
- 받아온 데이터의 총 갯수를 다음 커서로 보내주도록 개선되었고, 이를 대응하는 PR입니다! (`page.length * limitCount`)
- 따라서 이전에 하드코딩 해두었던 `orderBy=2` 필터를 제거하고, 등록순 필터의 주석을 해제합니다.
- [관련 스레드](https://sopt-makers.slack.com/archives/C04326AHDRT/p1684903947792499)
- 중요한 피처를 다 치고, 해당 페이지의 로직들을 좀 리팩토링 해보려 해요.. (FE 안건에 올렸던 그것!)
> chore: 등록순 필터 서버이슈 대응

- components/members/main/MemberList/index.tsx
- components/mentoring/MentoringCard/index.tsx
- components/mentoring/MentoringList/index.tsx
- pages/members/index.tsx
- utils/index.ts
- close #
멘토링 리스트 마크업을 했어요
- 각종 브레이크 포인트에 따라 다른 형태를 취하도록 했어요
디바운스 때문에 조금씩 늦게 반응하지만, 사용자가 화면 크기를 바꾸는 일이 해당 뷰의 메인 동작이 아니니까 한 번 바꿀 때 조금의 딜레이는 괜찮다고 생각했어요
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/02e1f2ec-55dd-46fc-8326-9d27cdd4b13d
> feat: 멘토링 리스트 마크업

- api/endpoint_LEGACY/image/index.ts
- close #701 
한글 파일명일 때 aws에서 인코딩한 문자열과 fe에서 인코딩한 문자열이 달라서 생긴 이슈 => fe에서 인코딩을 해서 보냅니다
> fix: 한글 파일명 이미지 깨지는 버그 fix

- components/common/Carousel/useCarousel.ts
- close #748
리사이징 등의 이유로 limit가 늘어나면 마지막 페이지 근방은 존재하지 않는 페이지가 될 수 있어요 이 경우에 현재의 마지막 페이지로 바꾸어 줍니다
> fix: 캐러셀 > 스크린 리사이징으로 인해 존재하지 않는 페이지 넘버가 된 경우 대응

- components/common/Loading/index.tsx
- components/members/detail/MessageSection/MessageModal.tsx
- close #640 
쪽지 보낼 때 버튼 텍스트가 사라지길래 고치려고 했는데 알고 보니 로딩 스피너가 들어가 있었고 그것이 버튼 색상과 같아서 보이지 않았던 것이었습니다
따라서 로딩 스피너를 흰색으로 바꾸었습니다
Loading 컴포넌트에 color prop을 추가했어요
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/a453d471-f945-461f-9cbf-64e08a88e37e
> fix: 쪽지 모달 > 쪽지 보내기 버튼 로딩 스피너 보이지 않는 버그 fix

- components/mentoring/MentoringCard/index.tsx
- close #756 
height 설정이 잘못돼있어서 고쳤어요
코드는 아주 사소한 변경이지만 메인 화면이라 너무나 크게 거슬리는 버그여서 바로 머지하겠습니다 ..
전
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/2167750b-f8c0-40bc-bb98-82a0034b684a
후 (전과 같은 데이터로 테스트 해보기 위해 프로덕션 데이터를 넣어서 모두 프로필 이미지를 못 불러옴.)
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/ba572fb0-566e-4b0e-86b4-355e13eaf533
> fix: 멘토링 리스트 > 캐러셀 페이지 이동 시 layout shift fix

- api/endpoint/members/getMemberOfMe.ts
- api/endpoint_LEGACY/hooks/members.ts
- api/endpoint_LEGACY/members/index.ts
- components/common/Header/index.tsx
- components/eventLogger/providers/AmplitudeProvider.tsx
- components/members/detail/MemberDetail.tsx
- components/projects/main/ProjectDetail.tsx
- pages/members/index.tsx
- pages/projects/upload/index.tsx
- close #769 
- 프로젝트 업로드 넛지 영역이 내 프로필에서만 보이도록 수정했어요.
- 하는 김에 `endpoint_LAGECY`도 수정했어요!
- 관련 hook을 같은 파일에 만들었는데, 관련해서 의견 있으시면 말씀해주세요! (기존엔 `endpoint_legacy/hooks`) FE 회의때 얘기해봐도 좋겠습니당
> fix: 내 프로필일 경우에만 업로드 넛지 영역 보이도록 수정

- components/common/Footer/index.tsx
- components/common/Header/index.tsx
- components/eventLogger/controllers/amplitude.ts
- components/eventLogger/controllers/consoleLog.ts
- components/eventLogger/controllers/storybookAction.ts
- components/eventLogger/events.ts
- components/eventLogger/types.ts
- components/members/detail/MemberDetail.tsx
- components/members/main/MemberList/OnBoardingBanner.tsx
- components/members/main/MemberList/index.tsx
- components/mentoring/MentoringList/index.tsx
- pages/auth/login.tsx
- pages/members/edit.tsx
기존에 파라미터 없는 이벤트도 `logClickEvent('myProfile', {})` 와 같이 빈 객체를 넣어줘야하는 불편함이 있었는데, 이제 파라미터 타입을 undefined 로 선언하면 빈 객체를 넣지 않아도 되도록 개선했어요!
components/eventLogger/types.ts 파일이 핵심인데요, 그저께 새로 알아낸 기법을 활용하여 이벤트 파라미터 타입이 undefined 인경우 함수의 spread된 인자를 빈 튜플로 줘서 인자를 받지 않도록 하고, 아닐 경우 원래의 이벤트 파라미터를 받도록 했어요.
> refactor: 파라미터 없는 이벤트 사용 개선

- components/members/upload/forms/Form.tsx
- pages/members/edit.tsx
- pages/members/upload.tsx
- close #779
1. 프로필 수정/업로드 버튼에 disable 상태 추가
2. submit 버튼 관련 잔잔바리 리팩토링
2-1. 레거시인 pc-only/desktop-only 클래스를 걷어내고 Responsive 컴포넌트를 적용했어요
2-2. @juno7803 가 예전에 제기해주었던 submit 버튼이 form 바깥에 있는 이슈를 해결했어요 
1. 프로필 수정/업로드 버튼에 disable 상태 추가
react hook form의 isValid state를 활용했어요
폼 컴포넌트에 RHF의 의존성이 생기지 않도록 isValid는 useFormContext를 활용하지 않고 prop으로 넘겨줬어요
> feat: 프로필 수정/업로드 버튼에 disable 상태 추가

- components/mentoring/MentoringList/index.tsx
- close #738 
멘토링 리스트 layout shift를 개선하기 위해 리스트의 렌더링 방식을 바꾸었어요
[문제]
기존 코드는 useEffect를 통해 결정되는 `listType` state가 서버 사이드에서 undefined이기 때문에 리스트가 올 자리에 아무것도 렌더링이 되지 않아 layout shift가 발생했어요
현재 멘토링 리스트가 있는 members 페이지가 메인 페이지로 쓰이고 있고, 심지어 멘토링 리스트가 페이지의 상단에 있기 때문에 이는 우리 서비스에 접속하는 유저의 첫 경험을 해쳐 다소 크리티컬한 문제라 판단이 됐어요
[솔루션]
따라서 이를 해결하기 위해 서버 사이드에서는 각 브레이크 포인트 별 UI를 모두 만들어지게 하고 className을 통해 각 스크린 사이즈 별 css display 속성을 설정해놓았어요
따라서 브라우저에 서버에서 받은 html이 그려질 때에 바로 미디어 쿼리가 적용되어 의도한 UI가 보이게 돼요
하지만 모든 브레이크 포인트 별 컴포넌트가 내내 마운트 되어 있을 필요는 없기 때문에 기존의 방식인 `listType`을 통해 조건부 렌더링 하는 코드도 삭제하지 않았어요
또한 resize 이벤트를 MediaQueryList 이벤트로 바꾸었어요
기존에는 resize 이벤트에 디바운스를 적용해놓았는데 이렇게 display: none; 코드가 추가되고 나서는 디바운스로 인한 딜레이 시간 동안 아무것도 렌더링되지 않아 새로운 원인의 layout shift 문제가 발생했어요
디바운스를 제거하는 것보다는 MediaQueryList 이벤트로 변경하는 게 성능 상 더 나을 것 …
> feat: 멘토링 리스트 layout shift 개선

- pages/members/edit.tsx
- close #794
프로필 수정 페이지 > 수정 사항 없을 시 submit 버튼 눌러도 put 요청 보내지지 않도록
submit 함수에 useForm formState의 isDirty를 이용해서 수정 여부를 판단하고 얼리 리턴 하는 코드를 추가했어요
> feat: 프로필 수정 페이지 > 수정 사항 없을 시 submit 버튼 눌러도 put 요청 보내지지 않도록

- api/endpoint/wordchain/getWordchain.ts
- api/endpoint/wordchain/postWord.ts
- components/wordchain/WordchainChatting/index.tsx
- close #807 
setQueryData로 낙관적 업데이트를 적용시켜 보았는데요
유지보수 안될 코드가 나와버렸네요 ..
이렇게 복잡한 타입의 캐시 데이터를 업데이트 할 땐 어떻게 해야 깔끔한 코드가 나올까요?..
일단 머지하고 좋은 생각 안 나면 추후에 invalidateQueries로 바꾸겠습니다ㅜ 
스크롤 가장 하단으로 고정하는 거 다음 작업에 하겠습니다
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/0fb831e4-12e8-44af-ab0f-870b94b0fdba
> feat: 끝말잇기 단어 추가 post api 연결

- api/endpoint/wordchain/getWordchain.ts
- components/wordchain/WordchainChatting/Wordchain/index.tsx
- close #824 
- words 빈 배열일 경우 대응
- initial word 및 유저가 startUser startWord로 바뀐 것 대응
- startUser null 대응
words 빈 배열인 경우
> fix: words 없는 경우 대응 및 initial 정보에 api 변경 대응

- components/members/main/MemberList/index.tsx
- close #835 
- 모바일 돋보기 포지셔닝 이슈 (`as-is`: 돋보기 랑 겹쳐서 왼쪽에 존재하고 있었음)
- 검색 결과 시 가운데로 오는 이슈
- Empty view 보이지 않던 이슈
- 간단한 작업인데 수정하는덴 시간이 좀 걸렸습니다 😂 유지보수 기간에 해당 페이지 코드를 좀 줄이는게 목표입니다
- 스타일 관련 코드도, 로직도 너무 많이 정리되지 않은 채 섞여있어 파악하기 쉽지 않더라구요
https://github.com/sopt-makers/sopt-playground-frontend/assets/26808056/65b2155e-d156-44c7-9f62-c5147b5c3040
> feat: 멤버리스트 페이지 노운,자잘 이슈 수정

- api/endpoint/wordchain/getWordchain.ts
- components/wordchain/WordchainChatting/Wordchain/index.tsx
- components/wordchain/WordchainEntry/WordChainEntry.tsx
- components/wordchain/WordchainEntry/WordchainMessage.stories.tsx
- components/wordchain/WordchainEntry/WordchainMessage.tsx
- close #
- 끝말잇기 진입점 새 게임 시작 케이스를 대응했어요.
- `WordchainMessage` 컴포넌트를 리팩토링 했어요. 기존엔 `helper`, `word` 두가지 케이스여서 boolean으로 빠르게 작업했는데요, `startWord` 케이스가 추가되어 변경에 대응하기 쉽게 유효한 상태만 뽑아서 `type`별로 다르게 형태를 분기했어요.
- 진입점의 경우도 비슷한 방식으로 `status`가 `start` 일 때와 `progress` 일 때를 구분하여 수정했어요.
> feat: 끝말잇기 진입점 새 게임 시작 case 대응

- api/endpoint/wordchain/getWordchain.ts
- components/wordchain/WordchainChatting/index.tsx
- close #
1. 낙관적 업데이트 하지 않기로 함 (애초에 실수로 onSuccess에서 해버려서 효과가 없기도 했지만 ,,)
이유: 생각해보니 좋아요 기능처럼 낙관적으로 업데이트 할 수 있는 구조가 아님. 끝말잇기 특성 상 예외 케이스가 많은데, 그 검증을 서버에서 하기 때문.
추후 낙관적 업데이트 대신 로딩 애니메이션을 넣거나, 검증 API를 따로 파기로 함.
2. 변경된 쿼리에 따라 이펙트 정리
스크롤을 최하단으로 옮겨주는 로직을 적절한 곳으로 이동시켰습니다
> fix: 끝말잇기 채팅 쿼리 이펙트 정리

- components/wordchain/WordchainChatting/index.tsx
- close #839
끝말잇기 채팅 > 새 페이지 fetch 시 스크롤을 fetch 전의 위치로 이동
정확히 어떤 문제였는지는 이슈 참고해주세요!
- scroll height를 저장해놓은 뒤 새 페이지가 fetch 되면 기존 scroll height를 통해 옮겨갈 위치를 계산함
- 렌더링이 완료된 후의 정확한 scroll height를 얻기 위해 setTimeout으로 관련 로직의 실행 순서를 미룸
여기까지 구현하고 보니 해당 컴포넌트 복잡성이 높아져서 추후에 리팩토링을 하면 좋을 것 같아 보입니당
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/bc39b469-d90e-4122-a85c-fe8d2622e642
> feat: 끝말잇기 채팅 > 새 페이지 fetch 시 스크롤을 fetch 전의 위치로 이동

- components/wordchain/WordchainChatting/index.tsx
- close #865
초기 진입 시 스크롤이 가장 하단으로 이동되어야 하는데 사용자 눈에 해당 움직임이 그대로 보여 버벅이는 것처럼 보이는 현상이 있었습니다
이를 감추기 위해 스크롤이 초기화 되기 전까지 로딩뷰를 띄웠습니다
`isLoading` 상태를 추가하여 로딩뷰를 조건부 렌더링 했습니다
`isLoading`은 최초 진입 시 스크롤을 초기화 한 후에 false가 되도록 했습니다
AS-IS
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/e212f93e-0290-4c42-bdcc-32b1cc070a6f
TO-BE
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/dd43bd7a-5e33-4569-b317-cc665c8c1478
> feat: 끝말잇기 채팅 초기 진입 시 스크롤 초기화 되기 전까지 로딩뷰 띄우기

- components/wordchain/WordchainChatting/Wordchain/index.tsx
- close #875
마지막 단어를 보낸 유저가 본인이면 새 게임 시작 버튼이 보이지 않도록 했습니다
유저 id 체크
> feat: 마지막 단어를 보낸 유저가 본인이면 새 게임 시작 못하도록

- components/projects/main/ProjectCard.tsx
- close #890 
- 변경된 디자인에 맞게 프로젝트 카드 호버뷰를 수정했어요.
- 호버 시 보이던 링크들을 제거하고 이미지가 scale up 되도록 변경했어요.
https://github.com/sopt-makers/sopt-playground-frontend/assets/26808056/fd58ea6c-4220-40be-98da-054992017c36
> feat: 프로젝트 카드 호버시 디자인 수정

- components/projects/edit/ProjectEdit.tsx
- components/projects/utils.ts
- close #
- 프로젝트 수정페이지로 진입할 시 추가적으로 프로젝트 이미지를 더 추가할 수 없던 문제를 수정했어요.
- 프로젝트 수정 시 해당 프로젝트의 상세페이지로 이동시키는게 더 자연스러워 보여서 이를 수정했어요. (기존엔 리스트 페이지)
> fix: ProjectEdit 수정사항 반영

- components/debug/SideToggleButton.tsx
- pages/soulmate/index.tsx
- close #899 
기존에 프리뷰 환경에서 디버그 패널 버튼이 채널톡과 겹치던 문제가 있었어요.
그런데 그렇다고 버튼을 다른데 옮기자니 위치가 애매해서 겹치치 않도록 버튼 크기를 줄였어요.
> feat: 디버그 패널 버튼 크기 변경

- components/auth/register/RegisterFinished.tsx
- pages/auth/register-finished.tsx
- close #903
1. 컨텐츠 중앙 정렬하기
2. 모바일 대응
1. justifiy content center
2. width: 420px 제거 -> 데스크탑 UI에는 변화가 없으면서 모바일에서 뷰포트를 넘어가 UI가 깨지는 현상 사라짐
> chore: 회원가입 완료 페이지 스타일링 수정

- components/common/Footer/index.tsx
- constants/links.ts
- close #908
푸터에 '메이커스 소개'를 추가해요
@Tekiter 저는 팀 페이지라고 표현하면 잘 와닿을 것 같아서 링크 url 상수 이름을 `MAKERS_TEAM_URL`이라고 지었는데 혹시 다른 이름이 나을 것 같으면 말해주세요 or 자유롭게 수정 커밋 올려주세요
> feat: 푸터에 메이커스 소개 추가

- components/projects/form/ProjectForm.tsx
- components/projects/form/UploadProjectProgress.tsx
- components/projects/form/fields/GenerationField.tsx
- components/projects/form/schema.ts
- close #930
- 기수쪽에 `defaultValue` 그대로일 경우 (최신기수인 32기) 진행상황 체크가 되지 않던 버그를 수정했습니당. 근데 그럼 결국 채우지 못할 경우의 수가 없으니 뺄까도 고민했는데, 필수 필드들은 다 체크하는 느낌이니 이렇게 대응했어요.
- 프로젝트 이미지를 누락해서, 이것도 추가했습니다.(사실 원래 플젝 이미지 선택이었는데 필수값으로 몰래 바꿨어요 -> 이미지 많이 올려줄 수록 좋을 것 같아서!) 
- 이전에 건영이와 오히려 32기 기수가 기본 설정으로 되어있는게 편할 것 같다고 의견 나눠서 이렇게 됐었는데, https://github.com/sopt-makers/sopt-playground-frontend/pull/931#issuecomment-1666842047 요기에서 주영이가 문제 제기 해주어서 다시 고민해본 결과 기존대로 돌아가도록 변경
- [bc19b03](https://github.com/sopt-makers/sopt-playground-frontend/pull/931/commits/bc19b0327e6b1cf668a2424d36f22feff973bdc2) 해당 커밋으로 변경!
> fix: 프로젝트 진행상황 - 기수 버그 수정, 프로젝트 이미지 추가

- components/members/upload/FormSection/Basic/index.tsx
- components/members/upload/schema.ts
- pages/members/index.tsx
This reverts commit a1a2287f0679caa499b1dc054f969b3dacc2a22a.
- close #955
회원가입 하면 바로 프로필 등록이 되도록 변경했기 때문에 프로필을 등록하라는 내용의 온보딩 배너를 삭제했었어요 (https://github.com/sopt-makers/sopt-playground-frontend/pull/921)
그러나 당분간은 모든 회원이 프로필이 있을 거라는 보장이 없기 때문에 다시 추가했어요
참고로 해당 이슈가 해결되더라도 어차피 프로필이 없는 유저에만 보여지기 때문에 바로 삭제 조치 하지 않아도 돼요
> Revert "feat: 온보딩 배너 삭제"

- src/pages/members/edit.tsx
- src/pages/members/upload.tsx
- close #953 
기존에 `isValid`로 수정하기 버튼의 활성화 여부를 조정하고 있었어요
그런데 `errors`가 비었는데도 `isValid`가 `false`여서 수정하기 버튼을 이용할 수 없는 이슈가 있어서 활성화 여부에 `errors`를 사용하는 방식으로 변경했어요
\* `isValid`와 `errors`는 React Hook Form의 `useForm`의 `formState` 속성
기존 방식이 왜 안되는지는 살펴볼 시간이 부족했어요
일단은 이렇게 하면 잘 동작해서 요렇게 가봅니다
> fix: 프로필 수정 페이지 > 수정하기 버튼 활성화 방식 변경

- src/components/members/upload/schema.ts
- close #959 
공홈 공개 여부(`allowOfficial`)를 nullable로 변경했습니다
서버에서는 null이 오는데 스키마는 nullable이 아니어서 수정하기가 안되는 버그가 있었습니다
boolean인데도 null이 올 줄 몰랐어용
\+ 아직 api 타입과 컴포넌트 타입의 레이어 분리를 하지 않은 이슈
\+ 서버 api 명세에 nullable이 명시 되지 않은 이슈
> fix: 프로필 업로드 스키마 > 공홈 공개 여부 nullable로 수정

- src/pages/_app.tsx
- src/pages/members/[id].tsx
- src/pages/projects/[id].tsx
- close #
- 공통의 `meta tag`를 주입하기 위해서 `_app.tsx`에 우선 주입하고, 개별 페이지에서 추가로 주입하면 override 되길 기대했으나, 중복으로 태그가 주입되고, 크롤러 봇은 먼저 주입된 `_app.tsx`의 메타태그를 읽는 문제가 있었어요.
- meta 태그에 property와 똑같은 key를 주입함으로써 해결했는데, 그러면 <Head> 태그 내부에서 같은 key를 가진 컴포넌트가 있으면 나중에 들어온 컴포넌트로 override 되도록 구현이 되어있다고 해요. 그래서 key를 주입하여 해결했습니다.
(feat. G교수님)
> fix: meta tag에 key를 부여해 페이지에서 override 되도록 수정

- src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
- src/components/wordchain/WordchainWinners/index.stories.tsx
- src/components/wordchain/WordchainWinners/index.tsx
최신 우승자의 이름색이 안보이는 이슈
- 명예의 전당 우승자 클릭 시 프로필로 넘어가도록 해줬어요.
- 최신 우승자의 이름색이 안보이는 이슈가 있어 글자색을 추가했어요.
> feat: 명예의 전당 우승자 클릭 시 프로필로 넘어가도록 & 글자색 수정

- src/components/wordchain/WordchainWinners/index.tsx
- close #1008 
- 13인치 노트북 화면배율 90%에서 명예의 전당 무한스크롤이 안되는 이슈를 해결했어요.
- 명예의전당 데이터 + 무한스크롤Target 을 감싸는 박스 태그에 overflow:hidden을 먹여두었더니, Target에 접근하지 못했던 것 같아요.
- 위의 박스 태그에 padding-bottom을 주었더니 해결되었습니다.
> fix: 무한스크롤 안되는 이슈 해결

- src/components/wordchain/WordchainEntry/WordChainEntry.tsx
> chore: 끝말잇기 배너에 불필요한 margin 제거

- src/components/mentoring/MentoringCard/index.tsx
- close #1013 
- 간소화한 모바일뷰의 멘토링카드 중 더이상 멘토링을 받지 않는 멘토링카드의 border-radius를 수정했어요. 
- border-radius를 수정했어요.
> fix: 모바일 뷰 멘토링 카드 radius 수정

- src/components/debug/Panel.tsx
- src/components/debug/SideBar.tsx
- src/components/debug/panels/AccessTokenPanel.tsx
- src/components/debug/panels/NavigationPanel.tsx
- src/components/debug/styles.ts
- close #1016
- 토큰 복사 버튼 추가
- 스타일 개선
제가 옛날에 야무지게 만들어놓은 copyToClipboard 유틸을 사용함ㅎ
스타일 개선은 하는 김에 해봤는데 의견 주세요 ㅎ.ㅎ
주요 개선: 타이틀 크기 위계 정리, 버튼 박스 스타일 통일, 각종 마진 패딩 정리
- 토큰 복사 기능
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/69ac3154-cddb-4138-9613-0e3808c6f033
- 스타일 개선
전
후
> chore: 디버그 패널 > 토큰 복사 기능 추가 및 스타일 개선

- src/components/makers/MakersMembers.tsx
메이커스 소개 페이지의 기수 탭이 스크롤이 안생기고 뭉개지는 오류를 해결했습니다.
> fix: 메이커스 소개 기수 탭 스크롤 수정

- playground-common/package.json
- yarn.lock
- close #1035 
- 기존 colors를 makers-colors로 옮기면서 헤더쪽에 의존성을 누락하여 이를 추가하고 버전을 올립니다.
> feat: playground-commons 헤더에 @sopt-makers/colors 의존성 추가

- .storybook/preview.tsx
- package.json
- src/components/community/layout/DesktopCommunityLayout.tsx
- src/components/community/layout/MobileCommunityLayout.tsx
- src/components/community/page.tsx
- src/components/community/queryParam.tsx
- src/components/layout/FullScreenLayout.tsx
- src/components/layout/HeaderFooterLayout.tsx
- src/components/layout/HeaderLayout.tsx
- src/components/layout/utils.ts
- src/pages/_app.tsx
- src/pages/community/index.tsx
- yarn.lock
커뮤니티 페이지의 기본 레이아웃을 구현했습니다.
쿼리 파라미터와 연동되는 상태와, 그 상태에 기반해 상세보기를 여는 기능을 구현했습니다.
https://github.com/sopt-makers/sopt-playground-frontend/assets/36122585/260a726f-bfe4-4f38-a1d2-4ccb86fa2ec3
https://github.com/sopt-makers/sopt-playground-frontend/assets/36122585/93249649-2f28-421c-91e0-8648aab2fcf5
> feat: 커뮤니티 레이아웃 구현

- src/components/community/layout/DesktopCommunityLayout.tsx
- src/components/community/layout/MobileCommunityLayout.tsx
기존 구현은 피드 리스트에 내부 스크롤을 만드는 방식이라, 페이지를 이동하고 다시 올 때 스크롤이 날아가는 문제가 있었어요.
이 문제를 해결하기 위해 피드 리스트는 전역 스크롤을 사용하도록 수정했어요.
> feat: 스크롤 정책 변경

- src/components/common/ImageUploader/index.tsx
- close #1044
1. 이미지가 없을 시에는 수정/삭제 버튼이 안 뜨고 바로 파일 선택기가 뜨도록
2. 파일 선택기 2번 뜨는 버그 fix
> fix: 이미지 업로더 버그 fix

- src/pages/_app.tsx
- 모바일 브라우저에선 input에 focus 시 글자 크기나 위치에 따라 화면을 알아서 확대해주는게 있어요. 이게 웹 접근성이긴 하지만 디자이너의 의도와 다른 경우가 많고 예측하기 어렵다보니 UX를 해치는 경우가 더 많아요. (ex. 아래 이미지처럼 채팅 전송 버튼이 가려짐)
- 따라서 모바일 환경에서는 input focus 시 화면 확대가 되지 않도록 작업해줬어요.
- 이게 유저가 직접 화면을 확대/축소하는 것을 제한할 수 있어요. (아이폰, 맥북에선 확대/축소되고, 안드로이드 일부화면에서 확대/축소가 안되는 것 확인 with @Tekiter) 대부분 문제가 없을 것으로 생각되지만 안전하게 모바일 환경에만 주입해줬어요.
- Next.js에서 `<meta name="viewport" content="width=device-width">`를 기본으로 넣어주기 때문에, 이미 viewport meta 태그가 있으면 `attribute`를 추가해주도록 처리했어요.
- @Tekiter 가 플그 클라이언트에서 `isMobile` 사용을 지양한다고 해서, 공통 변수로 두진 않았어요.
> feat: 모바일에서 input focus 시 화면이 확대되는 현상 막기

- src/components/feed/detail/FeedDetail.tsx
- src/components/feed/page/FeedHomePage.tsx
- src/pages/feed/[id].tsx
- close #1132
- 쓰레드에서 논의한 대로 모바일 / 데탑 구분하여 뒤로가기 정책을 적용했어요.
- 스크롤 복원도 처리하고 싶었는데 왜 안될까요 흑흑 일단 논이슈
- [논의한 쓰레드](https://sopt-makers.slack.com/archives/C04326AHDRT/p1700545244944029?thread_ts=1700406661.390089&cid=C04326AHDRT)
> feat: 뒤로가기 정책 적용

- src/components/common/BottomSheet/index.tsx
- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/CodeUploadButton/index.tsx
- src/components/feed/upload/Input/ContentsInput/index.tsx
- src/components/feed/upload/Input/TitleInput/index.tsx
- src/components/feed/upload/hooks/useUploadFeedData.ts
- close #1098
- css 수정
- 타이틀 input에서 엔터 클릭 시, 콘텐츠 input으로 자동 이동하도록 했어요.
- onKeyDown 이벤트로 ref.current.focus() 되도록 구현했어요. 
- 타이틀 인풋에서 엔터를 치면 \n이 함께 넘어가는 문제를 해결하기 위해, e.preventDefault()를 사용했어요.
- 한글인 경우, 제목을 `안녕하세요` 라고 입력한 뒤 엔터를 치면 콘텐츠 인풋에 `요\n`가 딸려 들어가는 문제가 있었어요. 
- !e.nativeEvent.isComposing인지를 체크해주어 문제를 해결했어요. 
https://github.com/sopt-makers/sopt-playground-frontend/assets/76681519/e591706a-35ad-4e21-afb9-d0bf1f28a607
> feat: 피드 업로드 디테일 수정

- src/components/feed/page/FeedUploadPage.tsx
- close #1125
- 업로드 페이지에서 뒤로가기 로직을 구현했어요. 
```
const hanldeQuitUpload = () => {
resetFeedData();
router.push('/community');
};
```
다음과 같이 라우터에 커뮤니티를 쌓아주었습니다.
> fix: 업로드 피드 뒤로가기 구현

- functions/feed/[id].ts
- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/Category/CategoryHeader/index.tsx
- src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
- src/components/feed/upload/Category/TagSelector/index.tsx
- src/components/feed/upload/Category/index.tsx
- src/components/feed/upload/UsingRules/UsingRulesPreview/index.tsx
- src/components/feed/upload/UsingRules/index.tsx
- src/components/feed/upload/hooks/useCategorySelect.ts
- src/components/feed/upload/hooks/useUploadFeedData.ts
- src/components/feed/upload/types.ts
- close #1099
- 피드 업로드시 카테고리 선택창이 자동으로 닫히는 문제를 해결했어요.
- 동시에 뒤로가기 로직을 수정했어요.(태그셀렉터에서 딤드 누르면, 카테고리셀렉터로 뒤로가기 =>태그셀렉터 닫기)
- 원래는 단계별로 isSelectorOpen의 값을 openCategory->openTag->openUsingRules->closeAll과 같이 관리했었는데요, 이렇게 하다보니, 원하지 않는때에 closeAll이 발생해버리는 이슈가 있었습니다. 
- 카테고리 셀렉터는 isSelectorOpen<'openCategory' | 'openTag' | 'closeAll'>으로, 커뮤니티 이용규칙 프리뷰는 isPreviewOpen<boolean> 으로 값을 따로 관리해주었습니다. 
- 원래는 카테고리 셀렉터 로직이 끝나면(=카테고리, 태그 선택이 끝나면) 프리뷰 모달이 열리고 5초 뒤에 닫히는 내용을 useEffect에서 관리했는데요, 그러다보니 원하지 않을 때에도 5초 뒤에 닫혀버려서.... useEffect를 없애고, 이벤트핸들링 함수에서 해당 내용이 이루어지도록 했습니다. 
- 커뮤니티 이용규칙 프리뷰가 열리면 5초 뒤에 닫히고, 클린업해주었습니다. 
```
openUsingRules();
const timer = setTimeout(() => {
closeUsingRules();
}, 5000);
return () => {
clearTimeout(timer);
};
```
> fix: 피드 업로드시 카테고리 선택창이 자동으로 닫히는 문제 해결

- src/components/sopticle/Success.tsx
- src/components/sopticle/UploadSopticle.tsx
- close #1153
[해당 스레드](https://sopt-makers.slack.com/archives/C042T81PW80/p1699861773937109)
- 공홈에서도 리다이렉트 되어있어서 유저가 사용하는데에는 문제없긴 하겠만, https://sopt.org/sopticle 주소가 더이상 유효하지 않아서, 변경해주었습니다!
- 링크만 변경해주었어요!
> chore: 솝티클 링크 변경

- src/api/endpoint/feed/getPosts.ts
- src/components/feed/list/FeedList.tsx
- close #1151 
- 서버 타입 검증에 실패했습니다. 오류에 대응했어요. 
- getPost에서 빠져있던 `writerId: z.number().nullable()` 필드를 추가해주었어요. 
- getPost의 member필드가 getPost.ts에서는 필수값인데, 실제 서버에서는 null로 내려오는 데이터가 있었어요.(익명일 때 이렇게 보내준 것 같아요.)
- member필드가 nullable해지면서 발생하는 이슈들을 수정했어요, FeedCard에 내려지는 값으로 post.member가 쓰이고 있어서 우선은 이렇게 대응했습니다. 
```
<FeedCard
name={post.member?.name ?? '익명'}
...
profileImage={post.member?.profileImage ?? null}
...
info={getMemberInfo({
...
member: {
activity: post.member?.activity ?? { generation: 0, part: '' },
careers: post.member?.careers ?? null,
},
})} 
/>
```
- 먼가 익명로직을 위해 서버를 수정하면서 타입이 수정되고, 그게 클라 쪽에 반영이 되지 않아서 생긴 문제같아요! 
- 특히 member가 nullable한 것이 실제로 가능한 것인지 잘 모르겠어서(isBlindWriter로 익명인지 아닌지 판단하는 것 같은데, 혹시나 이전에는 member를 null로 보내서 익명으로 판단하게 한 것인지 히스토리를 잘 모르겠어서요!!!) 확인부탁드립니다!
- 위와 같이 …
> fix: 서버 타입 검증 에러 대응

- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/list/CategorySelect.tsx
- src/components/feed/page/layout/DesktopCommunityLayout.tsx
- close #
리스트 왼쪽과 카테고리 아래 구분선을 추가하고, 리스트의 구분선 렌더링을 밖으로 뺍니다.
> feat: 데스크톱 레이아웃 구분선 추가

- src/components/common/Modal/parts/ModalButton.tsx
- src/components/common/Modal/useAlert.tsx
- src/components/feed/common/hooks/useBlindWriterPromise.tsx
- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/upload/hooks/useUploadFeedData.ts
- close #1157
- 익명 서약 모달 로직을 구현했어요. 
- 기존에 있는 useAlert를 이용했어요, 
- 업로드 부분과, 피드 댓글 부분 두 곳에 적용했습니다.
- 기존 alert에서       
```
hideCloseButton?: boolean;
buttonText?: string;
buttonColor?: string;
buttonTextColor?: string;
```
를 추가적으로 받도록 수정했어요. 다른 alert로직에 영향이 가지 않도록 설계를 수정하려고 노력했는데, 실제로 다른 로직에 영향이 가지 않을지 확인해주시면 감사하겠습니다! hideCloseButton은, 모달에 따로 확인 버튼이 있다보니까 x버튼이 없어서 내려주어야했고, alert버튼의 text가 확인이 아닐 수 있어서 내려주었고, 확인버튼이 지금은 회색 디폴트 색인데 이 경우는 흰색이라 buttonColor와 textColor를 내려주었습니다. 
https://github.com/sopt-makers/sopt-playground-frontend/assets/76681519/402bb330-e524-4f89-af2a-9e66b3bf1020
https://github.com/sopt-makers/sopt-playground-frontend/assets/76681519/3c4899d1-cc36-4d7b-8395-8fc2a0492c89
> feat: 익명 서약 모달 구현

- src/api/endpoint/feed/uploadFeed.ts
- close #
- post후, 추가된 데이터가 반영되지 않는 문제를 해결했어요. 
```
onSuccess: async () => {
queryClient.invalidateQueries({ queryKey: useGetPostsInfiniteQuery.getKey('') });
await router.push(playgroundLink.feedList());
},
```
- 원래는
```
queryClient.invalidateQueries({ queryKey: useGetPostsInfiniteQuery.getKey('') });
router.push(playgroundLink.feedList());
```
이렇게만 해주었는데, invalidate가 되지 않고, 바로 커뮤니티 페이지로 이동하는 이슈가 있었어요. 
- [router.push는 Promise를 리턴하는 비동기 함수](https://stackoverflow.com/questions/76501168/should-i-await-a-router-push-in-nextjs)라고 해요, 그래서, async await을 이용해서 원하는 순서대로 동작하도록 했습니다!
- 커비 선상님 🚀🚀🚀🚀🚀
> fix: post후 데이터가 바로 get되도록

- src/components/common/Modal/index.tsx
- src/components/common/Modal/useAlert.tsx
- src/components/common/Modal/useConfirm.tsx
- src/components/feed/common/hooks/useDeleteComment.ts
- src/components/feed/common/hooks/useReportComment.ts
- src/components/feed/page/layout/MobileCommunityLayout.tsx
- src/styles/zIndex.ts
- close #
- 썩 맘에드는 방법은 아니지만.. 레이아웃의 zIndex를 제거할 순 없고, 모달에 zIndex를 부여하면 또 다른 사이드 이펙트가 일어날까봐 prop으로 받도록 대응했어요.
> fix: 레이아웃 zIndex로 인해 Modal이 뜨지 않는 이슈 수정

- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/CheckboxFormItem/BlindWriterWarning/index.tsx
- src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
- close #1192
- 이미지 부분과 커뮤니티 이용규칙 프리뷰 겹치는 문제를 해결했어요. 
- content에 적은 내용이 없을만 footer가 fixed되도록 content가 null인지 아닌지를 isWriting으로 내려주었습니다. 
- 콘텐츠에 적힌 내용이 있으면 footer가 fixed되지 않고, 스크롤되면서 같이 내려가져요. 
https://github.com/sopt-makers/sopt-playground-frontend/assets/76681519/c45e80c2-6462-4595-9b28-55c4c5c1ece0
> chore: 이미지 부분과 커뮤니티 이용규칙 프리뷰 겹치는 문제 해결

- src/components/feed/common/utils.ts
- src/components/feed/list/FeedCard.stories.tsx
- src/components/feed/list/FeedCard.tsx
- src/components/feed/list/FeedListItems.tsx
- close #1195
- 전체 뷰에서 업로드된 게시글 카테고리가 표기되도록 했어요. 
- FeedCard에 prop으로 info를 내려주신 것으로 보아,,, 이름 옆에 들어가는 내용을 추상적으로 내려주려고 하신 것 같아서, prop으로 내려주는 info값을 수정했습니다. 
- 이렇게 categoryId가 빈값인 경우=전체를 보고 있는 경우이기 때문에, categoryId가 있으면 기존의 getMemberInfo로 가고, 없으면 ~님이 ~에 남김 이 뜨도록 했어요. 
- 이렇게 받아진 categoryId로 부모카테고리를 찾아서 반환해주었습니다. 파트 카테고리의 경우는 어느 파트인지까지 보내줘야해서 다음과 같이 짰습니다!
- 생각보다........복잡하게 있어가지고, switch-case 문으로 모든 경우의 수를 대응해주었습니다........
> feat: 전체 뷰에서 게시글 카테고리 표기하기

- src/components/common/Toast/ToastEntry.tsx
- close #
- 모바일에서 토스트가 가운데 뜨도록 위치를 수정했어요.
- 기존 토스트를 StyledToastWrapper로 감싸서 justify-content:center 해주었습니다.
> chore: 모바일에서 토스트 가운데 뜨도록 위치 수정

- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/hooks/useCategorySelect.ts
- close #
- 커뮤니티 이용규칙 프리뷰가, 카테고리를 선택할 때마다 매번 등장했는데요, 최초 진입시에만 뜨도록 수정했습니다. 
- 로컬스토리지에 isFirst라는 값으로 저장해주었어요, 
- 최초 진입시 
```
useEffect(() => {
localStorage.setItem('isFirst', 'true');
}, []);
```
- isFirst가 true인 경우에만 open되고, close될 때는 isFirst값을 false로 변경해주었어요. 
```
const openUsingRules = () => {
const isFirst = localStorage.getItem('isFirst') ?? 'true';
JSON.parse(isFirst) && setIsPreviewOpen(true);
};
const closeUsingRules = () => {
localStorage.setItem('isFirst', 'false');
setIsPreviewOpen(false);
};
```
- 페이지에 진입하자마자 isFirst값을 변경해주어야해서 useEffect를 사용했숩니다....
> feat: 커뮤니티 이용규칙 프리뷰 최초 진입시에만 뜨도록 수정

- src/components/feed/common/hooks/useCategory.ts
- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/detail/FeedDetail.tsx
- close #
- tag가 없는 카테고리(ex.자유)인 경우, detail feed에서 표기되지 않도록 구현했어요. 
- boolean값인 hasChildren을 내려주었어요, 
```
const children = findParentCategory(postData.posts.categoryId)?.children ?? [];
<DetailFeedCard.Header
...
hasChildren={children.length > 0} 
```
```
{hasChildren && (
<>
<IconChevronRight />
<Text typography='SUIT_13_M'>{tag}</Text>
</>
)}
```
- hasChildren이 true일 때에만 `>tag` 가 보이게 했어요. 
- 여기서 쓰인 findParentCategory를 훅으로 뺐는데요, 카테고리 아이디 하나로 부모 카테고리를 찾는 로직이 꽤 반복적으로 사용되어서, 훅으로 뺐고, 기존에 쓰인 코드는 후에 리팩토링하겠씁니다!(근데 슬랙보니까, 이제 부모 카테고리아이디&네임/현재 카테고리아이디&네임 둘 다 내려주는 방식으로 변경하기로 된 것 같기도 하네요...)
> feat: tag가 없는 카테고리인 경우, 표시하지 않기

- public/icons/check_box_field.svg
- src/components/common/Modal/usePopup.tsx
- src/components/feed/common/hooks/useReportFeed.ts
- close #1207
- 신고 후 확인 모달이 피그마 디자인과 달라서 변경해주었어요. 
- 기존 alert를 이용하기에는,,, 확인 버튼도 없고, 체크 아이콘이 있으며, 콘텐츠들이 가운데 정렬이에요. 
- 특히 확인 버튼이 없다는 점에서, 모달과는 다른 로직이라고 생각했고, useAlert코드를 참고하여 usePopup을 만들었어요. usePopup에서는 확인버튼에 대한 정보를 내려받지 않는 대신, 아이콘을 내려받는 로직입니다. 
- 아이콘을 svg자체로 내려주고 싶었는데, 잘 적용되지 않아서... 이렇게 링크를 직접 내려주고, usePopup에서는 css의 content 속성을 이용해 보여주었어요..!
```
popup({
icon: '/icons/check_box_field.svg',
title: '신고해주셔서 감사해요',
description:
'메이커스에서 빠르게 검토 후 적절한 조치를 취할게요 :) 건전한 커뮤니티를 만드는데 기여해주셔서 감사해요!',
maxWidth: 324,
});
```
> feat: 신고 후 확인 모달 구현

- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/list/FeedCard.tsx
- close #
- 818c7b5a4ad5ab021d8b774edcfb0d7f47621881 인포 길어지면 ellipsis 처리 리스트의 카드에서도 적용
- [21f1655](https://github.com/sopt-makers/sopt-playground-frontend/pull/1215/commits/21f1655746cde3aee00eb840242fe4c5d1909743) 댓글 textArea resize none 추가
> chore: 소소한 css 수정 (댓글 resize none, 인포 ellipsis 처리)

- src/components/feed/detail/slider/FeedImageSlider.tsx
- close #
이미지가 길 경우 버튼이 가려져 닫을 수 없는 문제를 z-index로 해결했어요
z-index 잘못 쓰면 이리저리 관리하기 어렵지만 포탈 내부라 크게 고민 안 하고 갈겼습니다
as-is
to-be
> fix: 피드 이미지 슬라이더 > 이미지 닫기 버튼이 사진보다 위로 올라오도록

- package.json
- src/components/eventLogger/components/LoggingClick.tsx
- src/components/eventLogger/components/LoggingImpression.tsx
- src/components/eventLogger/components/LoggingPageView.tsx
- src/components/eventLogger/controllers/amplitude.ts
- src/components/eventLogger/controllers/consoleLog.ts
- src/components/eventLogger/controllers/storybookAction.ts
- src/components/eventLogger/events.ts
- src/components/eventLogger/hooks/useEventLogger.ts
- src/components/eventLogger/types.ts
- src/components/feed/list/CategorySelect.tsx
- src/components/feed/list/FeedList.tsx
- yarn.lock
- close #1224
- pageView, impression, click에 해당하는 headless 로깅 컴포넌트를 만들었어요.
- 이때 LoggingClick의 경우에는 React.cloneElement 를 통해 동작하기 때문에 onClick이 정의되지 않은 커스텀 컴포넌트에는 사용할 수 없어요. 건영이가 LinkWithLog를 말해줬는데요, 요건 생각해보면 얘로 구현 자체를 갈아끼워야 해서 뭔가 취지랑 조곰 맞지 않을수도 있겠다 해서 이렇게 제공해보려고 해요..!
> feat: 로깅 전용 headless 컴포넌트 추가

- src/api/endpoint/feed/uploadFeed.ts
- src/components/eventLogger/events.ts
- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/CodeUploadButton/index.tsx
- src/components/feed/upload/UsingRules/UsingRulesButton/index.tsx
- close #1227
- 피드 업로드 페이지에 로그를 추가했어요. 
- 코드 버튼 클릭시, 커뮤니티 이용규칙 버튼 클릭 시, submit, 뒤로가기했을 시, 로그를 추가했어요. 
- 코드버튼, 커뮤니티 이용규칙 버튼 클릭 시, submit은 기존 코드를 참고했어요!
- 뒤로가기 시에는 (1) 우리가 구현한 뒤로가기 버튼을 클릭했거나 (2) 브라우저 뒤로가기를 클릭했거나의 경우가 있는데요, (1)은 onclick이벤트에 로그 붙였구, (2)의 경우는 원래 useEffect의 클린업함수로 구현했지만 이 경우는 FeedUploadPage가 언마운트될때마다 실행이 되어서 원하지 않을 때에도 실행이 되었어요. 예를 들면, submit해서 커뮤니티 홈으로 돌아갈 때에도 실행되고, 뒤로가기 했을 때 빈데이터들이 전송되더라구요. 그래서 useEffect의존성배열에 feedData를 넣어주면, 만약 아무 입력없이 업로드 페이지에 접속했다가 뒤로가기를 한 경우는 트래킹이 되지 않는 이슈가 있었습니다. 
- 그래서 다음과 같이 next의 뒤로가기 감지를 이용했어요.
```
useEffect(() => {
// MEMO: 뒤로가기 감지 시, quitUploading 수행
const handleBack = () => {
quitUploading();
};
window.addEventListener('popstate', handleBack);
return () => window.removeEventListener('popstate', handleBack);
}, [feedData]);
```
> feat: 피드 업로드 페이지 로깅 구현

- src/components/feed/list/FeedCard.tsx
- src/components/feed/list/FeedListItems.tsx
- src/components/feed/page/FeedHomePage.tsx
- src/components/layout/HeaderOnlyDesktopLayout.tsx
- src/components/layout/index.tsx
- src/components/navigation/NavigationProvider.tsx
- src/components/navigation/navigationContext.ts
- src/components/navigation/useNavigateBack.ts
- src/pages/_app.tsx
- src/pages/feed/[id].tsx
- close #
뒤로가기를 할 때 커뮤니티 리스트의 스크롤이 복원되도록 만들었어요.
뒤로가기로 접근할 시 호출되는 훅인 `useNavigationBack` 을 만들고, 거기에서 [virtuoso의 scrollToIndex 기능](https://virtuoso.dev/scroll-to-index/)을 활용해 스크롤 복원을 구현했어요.
> feat: 커뮤니티 스크롤 복원 구현

- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/list/FeedCard.tsx
- close #1252
제곧내
- 수정했었는데, Link 태그 감싸면서 스타일 깨짐. 굳이 정보 클릭했을때 멤버로 넘어갈 필요는 없어보여서 제거
> feat: 본문 줄바꿈 안됨으로 스크롤 생기는 이슈 수정, info ellipsis 되도록 수정

- src/components/feed/list/FeedCard.tsx
- close #
- 아래 문제 수정하면서 기명이면서 프로필 이미지 없는 경우엔 링킹이 빠져있어서 그것도 수정했어요
- [관련 쓰레드](https://sopt-makers.slack.com/archives/C042T81PW80/p1702192406593709)
> fix: 클릭 영역 수정, 프로필 이미지 없을때 프로필 연결 안되는 문제 수정

- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/Category/DropDown/index.tsx
- src/components/feed/upload/Input/ContentsInput/index.tsx
- src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
- src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
- close #1258
- 콘텐츠 input과 푸터 겹치는 문제 해결했어요. 
- height:dvh를 주고, align-items: flex-end; 로 해결했어요!
- 처음에는 flex-grow를 이용하려고 했으나, flex-grow는 사파리와 사파리 ios에서 적용이 안된다고 체크되어있더라구요,,!([flex-grow 문서](https://developer.mozilla.org/ko/docs/Web/CSS/flex-grow)) => 확인해보니 아니네요ㅎㅎ 제가 잘 못 읽엇숩니다..ㅎㅎ flex-grow를 사용했을 때 원하는 구현이 잘 안 되었는데 아래의 방법으로 해결이 되어서 이렇게 최종 수정했습니다!
- `align-items: flex-end;` 로도 충분히 해결가능해서 align-items: flex-end; 를 사용했고, height:dvh를 주었습니다! 
https://github.com/sopt-makers/sopt-playground-frontend/assets/76681519/fefab4c9-d25a-4bda-98a7-19f8e782a660
> fix: 콘텐츠 input과 푸터 겹치는 문제 해결

- .vscode/settings.json
- src/api/endpoint/feed/editFeed.ts
- src/api/endpoint/feed/getPost.ts
- src/api/endpoint/feed/uploadFeed.ts
- src/components/eventLogger/events.ts
- src/components/feed/common/hooks/useCategory.ts
- src/components/feed/detail/FeedDetail.tsx
- src/components/feed/edit/EditImpossibleModal.tsx
- src/components/feed/list/FeedListItems.tsx
- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/Category/CategoryHeader/index.tsx
- src/components/feed/upload/Category/index.tsx
- src/components/feed/upload/Input/ContentsInput/index.tsx
- src/components/feed/upload/hooks/useUploadFeedData.ts
- src/components/feed/upload/types.ts
- src/constants/links.ts
- src/pages/feed/edit/[id].tsx
- src/pages/feed/upload.tsx
- close #1262 
- 피드 수정을 구현했어요. 
- 기존의 FeedUploadPage를 재활용하려고 했어요, 그래서 isEdit을 prop으로 내려받도록 했습니다.(isEdit true이면 PUT, 아니면 POST가 되도록이요!) 
- 또한 feed/edit/[id]로 라우팅해서 query.id를 prop으로 내려주었어요. 그 값을 이용해 `const { data: postData } = useGetPostQuery(feedId);` 로 데이터를 가져왔어요. 만일 postData가 없으면(1.실제로 값이 없거나 2. 수정이 아닌 업로드인 경우) null이나 빈값이 되도록 다음과 같이 initialData를 선언해주었어요. 
```
const initialData = {
mainCategoryId: postData?.posts.categoryId ?? null,
categoryId: postData?.posts.categoryId ?? null,
title: postData?.posts.title ?? '',
content: postData?.posts.content ?? '',
isQuestion: postData?.posts.isQuestion ?? false,
isBlindWriter: postData?.posts.isBlindWriter ?? false,
images: postData?.posts.images ?? [],
};
```
`const [feedData, setFeedData] = useState(initialForm);`
- 만일, 수정을 눌러서 수정페이지로 들어오면 …
> feat: 피드 수정 구현

- functions/feed/edit/[id].ts
- close #1282 
- 수정 페이지에서 새로고침을 하면 404페이지가 뜨는 이슈를 해결했어요. 
https://github.com/sopt-makers/sopt-playground-frontend/pull/456 이 PR을 참고했어요!!!
- 멘토링이나 프로젝트 수정 url과의 통일성을 위해 feed/edit/[id] 라우팅은 유지하고, PR을 참고하여 function을 추가해주었어요.
> fix: feed edit 페이지 라우팅 이슈 해결

- src/components/feed/common/hooks/useCategory.ts
- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/Category/CategoryHeader/index.tsx
- src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
- src/components/feed/upload/Category/CategorySelector/index.stories.tsx
- src/components/feed/upload/Category/CategorySelector/index.tsx
- src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
- src/components/feed/upload/Category/TagSelector/index.stories.tsx
- src/components/feed/upload/Category/TagSelector/index.tsx
- src/components/feed/upload/Category/index.tsx
- src/components/feed/upload/hooks/useUploadFeedData.ts
- src/components/feed/upload/types.ts
- src/pages/feed/edit/[id].tsx
- src/pages/feed/upload.tsx
- close #1085 
- 피드 업로드에서, mainCategoryId와 categoryId를 두 번 저장하는 로직이 비효율적이라는 생각이 들었어요. categoryId는 실제로 서버에 들어가는 데이터이고, mainCategoryId는 피드 업로드에서 임시로 저장하던 데이터였습니다. categoryId만 저장하고, parentCategory를 찾는 함수를 통해 충분히 부모 카테고리 id를 찾을 수 있기 때문에 이를 따로 저장하는 로직이 불필요하다고 느껴져서 리팩토링하였습니다!
- mainCategoryId관련된 내용을 모두 걷어냈습니다. 
- mainCategoryId를 저장하던 곳은 모두 categoryId를 저장하는 로직으로 변경, mainCategoryId를 참조하던 곳은 모두 categoryId를 기반으로 부모 카테고리 id값을 찾는 로직으로 변경했어요. 
- mainCategoryId를 걷어내면서 발생될 이슈가 없을지, 여러번 확인했을 때 이슈는 없었고 원하는대로 잘 동작합니다! 하지만 혹시 모르니, 한 번씩 확인해주시면 좋을 것 같아요~!
> refactor: mainCategoryId 따로 저장하는 로직 걷어내기

- src/api/endpoint/wordchain/getWordchain.ts
- close #1302
- 끝말잇기 가장 최근 데이터가 불러와지지 않는 이슈가 있었어요. 
- limit이 0으로 설정되어서 0개의 데이터가 왔고, 이에, limit을 1로 수정해주었습니다.
> fix: 최근 끝말잇기 limit 조정

- src/api/endpoint_LEGACY/members/type.ts
- src/components/members/CheckSoptActivity.tsx
- src/components/members/detail/MemberDetail.tsx
- src/components/members/detail/SoptActivitySection/index.stories.tsx
- src/components/members/detail/SoptActivitySection/index.tsx
- src/components/members/upload/FormSection/SoptActivity.tsx
- src/constants/links.ts
- src/pages/auth/callback/apple/register.tsx
- src/pages/auth/callback/google/register.tsx
- src/pages/members/checkSoptActivity.tsx
- #1263
[기능 배경 및 요구 사항 정리한 문서](https://www.notion.so/sopt-makers/839cc91ec6044952a367cbb46afe9220?pvs=4) 
미완이어서 베이스 브랜치 만들어서 거기 타겟으로 올려놨구요
submit 로직, 스타일링, 이대로 수정 누를 시 로직(컨펌 모달 띄우고 프로필 업로드 페이지로 라우팅), 폼 validation 미완입니다!
https://github.com/sopt-makers/sopt-playground-frontend/assets/73823388/b1a1b757-f885-479d-aba8-b16bc29770fc
> feat: 활동 정보 확인 페이지 구현 (1)

- src/api/endpoint/members/getMemberCrew.ts
- src/api/endpoint_LEGACY/hooks/members.ts
- src/components/members/detail/ActivitySection/MemberDetail.tsx
- src/components/members/detail/ActivitySection/MemberMeetingCard.tsx
- close #1317
제 PR은 왜이렇게 길어지는 것일까여,, 죄송합니다흑 모르는게 많아 궁금한 것에 대한 주저리들이니 일단 돌아가는 것 먼저 확인해주시면 되겠습니다...!!!
- 나눠서 구현한 API와 UI 부를 합쳐 완전한 기능으로 마무리했습니다.
- 존재하지 않는 유저 id에 대해 요청시 서버에서 에러코드 400을 추가해줘서 이에 대한 에러처리를 추가했습니다.
- 무한스크롤에 사용한 `useIntersectionObserver` 훅을 `useEnterScreen` 훅으로 대체했습니다.
지난 리뷰에서 지수언니가 `useIntersectionObserver`를 이용한 무한스크롤 구현을 위해 `useEffect`를 쓴 이유에 대해 질문해줘서 많이 고민해봤는데...
일단 `useIntersectionObserver` (커스텀훅) 은 `IntersectionObserver`라는 Web API를 이용한 훅이고, 관찰할 노드에 대한 `ref`와 뷰포트에 들어왔는지 여부를 반환하는 boolean값인 `isVisible`을 return하고 있습니다. 따라서 이 훅을 사용할 때 isVisible값의 변화에 따라 무한스크롤에서 다음 값을 불러올지 여부를 판단해야 했는데요. 즉 특정 요소가 화면에 들어왔는지 아닌지에 대해 브라우저라는 외부세계와 통신하며 값을 동기화해주는 것이 필요하기 때문에 useEffect가 필요하다는 판단을 내리게 되었습니다.
그러나 이게 이미 만들어져있던 커스텀훅이기 때문에 .. 이미 내려진 정답에 이유를 끼워맞추는 느낌이 들어서 좀 찜찜했는데요ㅜㅜ
히스토리를 좀 더 찾아보니 이런 …
> feat: 프로필 내 모임 기능 구현 완료

- src/pages/members/complete.tsx
- close #1336 
- 프로필 등록 완료 페이지 cta에서도 다짐메시지를 작성하도록 했어요.
- 자잘한 css를 수정했어요.
환영배너에서 사용되는 다음의 로직을 동일하게 members/complete.tsx에도 적용했습니다.
```ts
const {
isOpen: isOpenResolutionModal,
onOpen: onOpenResolutionModal,
onClose: onCloseResolutionModal,
} = useModalState();
const { alert } = useAlert();
const { data: { memberProfileImgUrl, isRegistration } = {} } = useGetResolutionValidation();
const handleResolutionModalOpen = () => {
if (isRegistration) {
alert({
title: '편지는 한번만 전송할 수 있어요',
description: '전송된 편지는 종무식 때 열어볼 수 있어요!',
buttonText: '확인',
maxWidth: 400,
zIndex: zIndex.헤더,
buttonColor: colors.white,
buttonTextColor: colors.black,
hideCloseButton: true,
});
} else {
onOpenResolutionModal();
}
};
```
https://github.com/sopt-makers/sopt-playground-frontend/assets/55528304/7bae64d2-c01c-4428-964b- …
> feat: 프로필 등록 완료 페이지 cta에 다짐메시지 모달 로직 연결

- src/components/common/Banner/WelcomeBanner/index.tsx
- src/components/common/Footer/index.tsx
- src/components/resolution/ResolutionModal.tsx
- src/components/resolution/useOpenResolutionModal.ts
- src/pages/members/complete.tsx
- close #1338 
- 다짐 메시지 모달 로직을 모듈화 했어요.
- 다짐 메시지 모달에 필요한 프로필 이미지를 가져오는 api를 변경했어요.
- 다짐 메시지 모달을 열기 위해 사용되는 useModalState 반환값들, alert, 재확인 모달 로직 등을 새로운 파일로 분리하여 커스텀훅을 만들었습니다. 이를 1. 환영배너 cta 2. 프로필 등록 완료 페이지 cta 에서 가져다 사용합니다.
- 메시지를 제출할 때 validation api를 refetch하는 로직으로 바꿨더니 생기는 문제를 발견했어요! 이렇게 하면 사용자가 처음으로 다짐 메시지를 쓸 때는 validation api가 한번도 호출되지 않게 되는데, validation api에서 이미 등록했는지 여부뿐만아니라 프로필 이미지도 가져오고 있기 때문에 처음 쓰는 유저는 프로필 이미지가 뜨지 않는 문제가 발생했습니다. 처음 쓰는 유저뿐아니라 메시지를 남기기 전에 프로필을 변경했다면 이 변경된 프로필이 모달에는 반영되지 않는 문제가 생기는 것입니다. 그래서 프로필 등록/수정 api에도 validation api를 refetch하도록 추가해야하나 생각했다가, 기존 api를 건드는 것 보단 resolution 피쳐 관련 파일내에서 해결하는게 좋을 것 같아서, 프로필 이미지를 validation api가 아니라 getMemberOfMe() api에서 가져오는 것으로 수정했습니다.
- 이슈와 관련없는 변경사항 죄송하지만 공통 컴포넌트 footer가 모달을 가려서, zIndex.헤더 값(100) 을 이용하여 zIndex를 변경했습니다.
기존 zIndex …
> refactor: 다짐 메시지 모달 로직 개선 및 자잘한 UI 수정

- src/api/endpoint/members/getMemberCrew.ts
- src/components/members/detail/ActivitySection/MemberDetail.tsx
- close #1341 
참여한 모임이 없을 때도 무한스크롤이 트리거되는 문제를 발견했습니다.
무한 스크롤을 트리거하는 Target 컴포넌트를, 참여한 모임이 존재할 때만 노출되도록 변경하였습니다.
> fix: 프로필 내 모임 카드 무한 스크롤 트리거 수정

- src/components/members/detail/EmptyProfile.tsx
- close #1351
- 프로필 등록 페이지에서 강제이탈하여 프로필 등록이 안 되어있는 경우, 버튼 추가하기
- 공통 컴포넌트 버튼을 추가해주었어요.
> feat: 프로필 등록이 안 되어있는 경우, 버튼 추가하기

- src/components/members/main/MemberCard/index.tsx
- src/components/members/main/MemberList/index.tsx
- close #
- 태그가 아주 많을 경우, 프로필 카드의 내용이 넘치는 문제를 해결했어요. 
- grid minmax값을 auto가 아닌 값을 부여하고, min-width:0을 주었어요.
> fix: 태그가 아주 많을 경우의 프로필 카드 수정

- src/components/members/detail/ActivitySection/MemberDetail.tsx
- close #1363 
프로필 이미지 사이즈랑 gap 사이즈도 조금 줄이고, 프로필 수정 버튼 윗 부분이 헤더에서 가려지지 않게 하였습니다. 
|전|후|
|--|--|
|<img width="368" alt="image" src="https://github.com/sopt-makers/sopt-playground-frontend/assets/63948884/f9854db5-e26a-4ef2-9607-dadca5726345">|<img width="364" alt="image" src="https://github.com/sopt-makers/sopt-playground-frontend/assets/63948884/993e56d8-ef3d-4130-8d48-00e5bec4fda7">|
> fix: 모바일 프로필 상세 스타일링 수정

- src/components/common/ResizedImage/index.tsx
- src/components/projects/main/card/MobileProjectCard.tsx
- src/components/projects/main/card/ProjectCard.tsx
- src/components/projects/main/card/ProjectCardMemberList.tsx
- close #1365
- 프로젝트 이미지들을 모두 `ResizedImage`로 변경했어요. 요게 건영이가 커뮤니티때 만들어준 멋진 친구였군요.. webp로 바꿔주는걸 넣고싶었는데 딱 이게 있었군뇨..
- 그것과 더불어 엑박뜨는 이미지가 많아서 엑박뜰때 기본이미지로 보여지도록 변경했어요.
https://github.com/sopt-makers/sopt-playground-frontend/assets/26808056/6826f97a-e890-420b-bb19-6b7541ea2649
> feat: 프로젝트 이미지 ResizedImage로 변경, 엑박 이미지 대응

- src/pages/members/complete.tsx
- close #1373
해당페이지가 AuthRequired로 감싸지지 않아서 로그인 없이 접속했을 시 intro로 redirect되지 않는 문제를 발견하였습니다.
https://github.com/sopt-makers/sopt-playground-frontend/assets/55528304/d73118c7-a1f7-469b-88d0-23a6bf87fea7
> fix: 프로필 등록 완료 페이지에 AuthRequired 추가

- src/components/wordchain/WordchainRules.tsx
- src/pages/members/complete.tsx
- close #1375
끝말잇기 이용규칙 디자인의 패딩 등을 올바르게 적용했습니다.
> fix: 끝말잇기 이용규칙 디자인 수정

- src/api/endpoint/feed/getComment.ts
- src/api/endpoint/feed/getPost.ts
- src/api/endpoint/feed/getPosts.ts
- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/detail/FeedDetailComments.tsx
- src/components/feed/detail/FeedDetailContent.tsx
- src/components/feed/list/FeedCard.stories.tsx
- src/components/feed/list/FeedCard.tsx
- src/components/feed/list/FeedListItems.tsx
- close #1383
- 커뮤니티 게시글, 댓글의 익명 프로필을 구현했어요.
- 기존 api에서 추가된 anonymousProfile의 타입을 추가하고, 익명과 기본프로필을 보내던 부분들을 anonymousProfile로 변경했어요.
- isBlindWriter가 true면 anonymousProfile값은 객체로 오고, isBlindWriter가 false면 anonymousProfile가 null로 오게됩니다. 그래서 이 부분을 zod에서부터 검증되게 하고 싶었어요. 
- 하지만! 아래와 같이 유니온(A타입 or B타입)을 만들고, object끼리 합치는 방식으로 구현을 하였는데, zod와 흘러가는 타입 자체는 문제가 없었으나, 현재 서버에서 내려주는 데이터들 중에 isBlindWriter가 true인데도, anonymousProfile가 null인 데이터들이 존재해요ㅠ 
```
const anonymous = z.union([
z.object({
isBlindWriter: z.literal(true),
anonymousProfile: z.object({
nickname: z.string(),
profileImgUrl: z.string(),
}),
}),
z.object({ isBlindWriter: z.literal(false), anonymousProfile: z.null() }),
]);
```
- 그래서 결국와 아래와  같이 타입을 짰고... 컴포넌트 안에서  anonymousProfile가 null인지 아닌지 검증해주었어요.
```
isBlindWriter: z.boolean(), …
```
> feat: 익명프로필 구현하기

- src/components/eventLogger/events.ts
- src/components/feed/list/FeedListItems.tsx
- close #1391
좋아요 클릭에 로깅을 추가했습니다.
좋아요 취소(FeedUnlike)와 좋아요(FeedLike)을 나누어 로깅했습니다.
> feat: 좋아요 클릭에 로깅 추가

- src/components/feed/detail/DetailFeedCard.tsx
- close #1397
게시글 및 댓글 생성날짜 (createdAt)의 렌더링에 대해 `createdAt &&` 조건부를 추가했어요.
> fix: 게시글 및 댓글 생성날짜 null 예외처리

- src/components/members/upload/AddableWrapper.tsx
- close #
- [누락회원 정보 대응](https://github.com/sopt-makers/sopt-playground-frontend/pull/1324)하면서 AddableWrapper에 isCheckPage를 prop으로 내려주게 수정되었더라구용! AddableWrapper가 공통컴포넌트인데, isCheckPage가 옵셔널로 받아지는 prop이어서 AddableWrapper를 사용하고 있던 기존 커리어&링크 부분에서 isCheckPage가 내려지지 않으면서 추가 버튼이 보이지 않게 되었어요!
-  props에`isCheckPage = true`를 추가해주어서 만일 isCheckPage가 null이면 true값으로 디폴트되게 고쳐주었습니다.
- 혜준 언니가 작업해주었던 누락회원 정보 대응의 코드와 상충되는 부분일지 확인부탁드려요~
> fix: 프로필 추가 버튼 보이지 않는 문제 해결

- src/components/feed/common/FeedLike.tsx
- src/components/feed/list/FeedCard.tsx
- close #1401
- 게시글 텍스트 영역이 댓글 개수 표시 영역과 묶이도록 수정
- 좋아요, 댓글 텍스트를 mds에 맞게 디자인 수정
> fix: 피드 레이아웃과 좋아요/댓글 텍스트 디자인 수정

- src/components/members/common/select/Select.tsx
- src/components/members/main/MemberList/index.tsx
- close #1421
https://github.com/sopt-makers/sopt-playground-frontend/assets/55528304/711c378d-2f47-4ace-a26d-e0a1ffd647ed
멤버 목록을 필터링 할 때 발생하는 문제점이 있었습니다.
영상에서 보시다시피
1. 특정 값을 선택하고(ex. `34기`)
2. `전체 기수`를 선택한 뒤
3. 다시 특정 값(ex. `34기`)을 선택하면 → ⚠️ **아무런 동작도 발생하지 않습니다**
한번 더 `전체 기수`를 선택하고 다시 `34기`를 선택해야만 합니다.
기존에는 이런식으로 동작시키는게 흔치 않아서 그대로 남아있었던 것 같은데,
셀렉트 옵션이 '재직 중이에요' 1개 뿐인 재직 상태 필터링을 추가하면서 버그를 고쳐야겠다는 생각이 들었습니다!
기존에, 전체 기수를 비롯한 모든 필터링 박스의 '전체' 옵션을 누르면 해당 셀렉트 박스의 value로 undefined가 넘어가는 것을 확인했습니다.
그러나 undefined로 넘기면 위와 같이 비정상적인 동작이 발생해서, undefined 대신 빈 문자열('')을 넘김으로써 해결했습니다.
+ 문제의 원인을 좀더 알아보고있습니다
https://github.com/sopt-makers/sopt-playground-frontend/assets/55528304/02cd2683-624a-4438-b8a4-91ca84a54db4
해결완룡!!!
> fix: 멤버 프로필 필터링 오류 해결

- src/api/endpoint/members/getMembersSearchByName.ts
- src/components/eventLogger/events.ts
- src/components/feed/list/FeedCard.tsx
- src/components/members/main/MemberCard/MessageButton.tsx
- src/components/members/main/MemberList/filters/MemberListFilter.tsx
- src/components/members/main/MemberList/filters/constants.ts
- src/components/members/main/MemberList/index.tsx
- src/components/projects/upload/hooks/useGetMembersByNameQuery.ts
- src/pages/projects/upload/index.tsx
- close #1414
- 기존 이름 검색을 이름, 학교, 회사 검색으로 변경
- 주량 필터링 제거하고 재직 상태 필터링 추가
- UX라이팅 변경(정렬 필터, 파트 네이밍, 쪽지 버튼 호버 툴팁)
재직 상태를 검색하는 employed=1 파라미터를 추가하였습니다
기존에 이름을 검색하던 name 파라미터의 명칭을 cond로 변경하였습니다
피그마는 mds로 디자인이 구현되어 있는데, 다음에 한번에 바꾸는게 나을 것 같아서
다른 사용처에서 문제 안생길 정도로 최소한의 것만 수정하였습니다.
+ 셀렉트 컴포넌트에서 문제가 발견되어서 열심히 파헤쳐보고있습니당...
1. 옵션을 선택한 다음에
2. '전체' 옵션을 누르고
3. 1번에서 누른 옵션을 다시 누르면 적용이 안되는 문제예요 ㅜㅜ
https://github.com/sopt-makers/sopt-playground-frontend/assets/55528304/aa011da7-7eeb-48e9-8a58-4307918305d4
> feat: 멤버 프로필 필터링 수정

- src/components/common/Footer/index.tsx
- src/components/common/Header/mobile/MobileSideBar.tsx
- src/components/common/KakaoScript/index.tsx
- src/hooks/useKakao.ts
- src/kakao.d.ts
- src/pages/_app.tsx
- close #1404 
- 구글폼으로 이루어졌던 의견 제안하기를 카카오톡 버튼으로 수정하였어요.
- 카카오 SDK 로드 및 초기화 
<KakaoScript/> 라는 컴포넌트를 만들어서, SDK를 로드하고 초기화하였어요. 
해당 컴포넌트가 적용이 안되어서 애를 먹었는데, 알고보니 Next에서는 Head에 script를 넣으면 안된다고 하더라구요! Head바깥으로 KakaoScript를 넣어주어서 해결했습니다. 
- SDK 초기화되었는지 확인하는 로직
초기화되었는지를 확인하고, 그렇지 않다면 100밀리초마다 반복하여 초기화 작업을 진행했습니다. 
- onClick이벤트
메이커스 채널 고유 id인 _sxaIWG를 통해 채팅을 시작하도록 하고, 문제가 발생한다면 에러를 뱉도록 했습니다.
- env에 새로운 키가 추가되었습니다! 해당 내용은 카카오톡으로 전달드릴게요~
- cloudFlare에 키 추가 필요
- 배포 후, 사이트 도메인 테스트 필요
- 모바일에서는 헤더에 의견 제안하기가 들어가있어서, 헤더 배포가 필요합니다. 배포 후 크루에서도 문제없는지 확인하기
> feat: 카카오톡 채팅 기능 추가

- src/api/endpoint/members/getMembersSearchByName.ts
- close #1448
멤버 프로필 기능을 수정하면서, 관련 없는 getMembersSearchByName api의 파라미터 명이 name에서 search로 변경되는 실수가있었습니다. 이를 name으로 다시 되돌렸습니다.
프로젝트 업로드시 getMembersSearchByName를 사용하는 기능과
멤버 프로필 내 검색 모두 정상 작동 확인하였습니다!
> fix: getMembersSearchByName parameter 네이밍 수정

- src/components/common/Header/desktop/DesktopHeader.tsx
- close #1446
playground-common에 해당하는 DesktopHeader에서 끝말잇기 탭을 제거했습니다.
이 PR은 크루쪽이랑 시간 맞춰서 배포 하겠습니다!
> fix: 끝말잇기 탭 제거

- package.json
- src/api/endpoint/remember/getReviews.ts
- src/api/endpoint/remember/uploadReview.ts
- src/components/remember/index.tsx
- src/components/remember/mocks/handlers.ts
- src/components/remember/reviews/ReviewCard/index.stories.tsx
- src/components/remember/reviews/ReviewCard/index.tsx
- src/components/remember/reviews/index.tsx
- src/pages/remember/index.tsx
- yarn.lock
- close #1458
- 목서버로 받아온 데이터를 기반으로, 활동 후기 메시지 전시를 구현했어요. 
- masonryInfiniteGrid 라이브러리를 이용했어요. 
- 핀터레스트와 같은 스타일을 위해 많이 사용되는 라이브러리이고, 크루에서도 해당 라이브러리를 이용하길래 선택해보았습니다!
- 겉을 감싸는 태그의 width값을 꼭 주어야 문제없이 보여지더라고요!
> feat: 활동 후기 메시지 전시 구현

- src/api/endpoint/remember/uploadReview.ts
- src/components/remember/ReviewInput/index.tsx
- src/components/remember/index.tsx
- close #1461 
- 활동 후기 메시지 input을 구현했어요. 
- 목서버를 연결해서 input 내용이 넘어가도록 구현했어요.
- 2번째 줄까지는 늘어나고 그 이상은 스크롤 되는 점, \n까지 인식해야한다는 점에서 기존에 커뮤니티 업로드에서 사용하던 TextareaAutosize를 사용했어요.
- focus와 error를 상태값으로 포괄하여 생각하여 status라는 변수를 이용했어요.
> feat: 활동 후기 메시지 input 구현

- src/api/endpoint/remember/getReviews.ts
- src/api/endpoint/remember/uploadReview.ts
- src/components/remember/ReviewInput/index.tsx
- src/components/remember/index.tsx
- src/components/remember/reviews/index.tsx
- src/pages/remember/index.tsx
- close #1471
- 활동 후기 페이지 실 서버 연결
- 활동 후기 페이지 레이아웃 조정
- 목서버에서 실서버 url로 갈아끼워주었어요.
- 무한스크롤의 nextParams가 잘 불러와지지 않는 이슈...가 있어요.
- masonryInfiniteGrid를 사용하려면 카드의 width값이 있어야해서, max-width를 주긴 했는데 반응형으로 줄어들게 하고 싶어서 조금 더 수정 보겠습니다!
> feat: 활동 후기 페이지 수정

- src/api/endpoint/remember/getReviews.ts
- src/components/remember/reviews/index.tsx
- close #
- 무한스크롤을 수정했어요!
- 20개씩 받아오도록 되어있어서, 값이 받아와질 때마다 pages에 들어가져요. 즉 page 0으로 부른 20개의 값은 pages의 인덱스0에 들어가기 때문에 다음에 부를 nextpage는 현재 pages 배열에 들어있는 길이값과 동일하다고 생각했고, 그래서 return pages.length해주었습니다!
- 믕서의 도움으로 옵저버를 세팅해주었어요!
https://github.com/user-attachments/assets/171faee3-ee83-4ef6-aff0-f6fe6d351d8a
> fix: 무한스크롤 수정

- src/components/common/Banner/ActiveBannerSlot.tsx
- src/components/wordchain/WordchainEntry/WordChainEntry.tsx
- close #1495 
- 배너 노출부에서 다짐메시지 배너 제거
- 끝말잇기를 원래 상태로 되돌림
- ActiveBannerSlot에 넣어놨던 다짐메시지 배너를 제거했어요.
- 끝말잇기 배너에서 desktop 반응형을 제거했던 것을 원래대로 되돌렸어요.
8/4->8/5로 넘어가는 자정에 prod 배포 예정입니다!
> fix: 다짐메시지 배너 내리기

- src/components/feed/page/layout/DesktopCommunityLayout.tsx
- close #1497
- home에서 끝말잇기 진입점의 max-width 변경
이렇게 들어가야하는데
이렇게 되어있는 것이 문제였어요.
지난번에 다짐 메시지 배너를 넣으면서, 끝말잇기 진입점의 max-width를 변경해야 했거든요..!
해당 부분을 되돌리는 작업을 했습니다.
> fix: 끝말잇기 max-width 변경

- src/components/common/Banner/AdsBanner/constants/ads.ts
- src/components/feed/page/layout/DesktopCommunityLayout.tsx
- src/components/wordchain/WordchainEntry/WordChainEntry.tsx
- close #1514
- 광고 배너 유무에 따라 끝말잇기 배너를 변경해주었어요.
- 광고 배너가 담긴 배열의 길이가 0보다 큰 경우를 배너가 있는 경우로 판단하여, isBanner를 props로 내려주었어요. 
- 미디어 쿼리랑 Responsive 태그가 중복으로 쓰이면서 반응형이 구현되어서, isBanner를 기점으로 분기처리가 많이 된 점이 아쉽구만요..
- ADS의 길이가 0이더라도, 다짐메시지 배너 등이 들어가게 되면 배너가 존재하는 상황이라서 이 경우에는 isBanner값에 
`const isBanner = ADS && ADS.length > 0||true;` 이런식으로 isBanner가 true값이 되도록 해주어야할 것 같아요
> feat: 광고 배너 유무에 따른 끝말잇기 배너 변경

- src/pages/members/edit.tsx
- close #1525 
skill 값이 null이나 undefined일시 빈 문자열로 초기화하도록 처리했습니다.
`skill: myProfile.skill ?? '',`
edit 페이지에 들어가면 useEffect로 작성된 프로필 항목들을 초기화하는데, 그 과정에서 skill이 null일 때 문제가 발생하고 있었습니다. 따라서 null이라면 빈 문자열로 들어가도록 처리했습니다.
> fix: 프로필 수정 페이지에서 skill 항목 null safety 처리

- src/api/endpoint_LEGACY/projects/type.ts
- src/components/projects/main/ProjectList.tsx
- src/components/projects/upload/hooks/useGetProjectListQuery.ts
- close #1533 
- 프로젝트 탭에서의 검색 결과가 없을 때 empty view 추가했어요.
- 검색값을 입력하거나 칩을 선택했다가 지우면 url에 query string이 남아있던 것을 제거했어요.
- 검색 결과가 없을 때도, 검색창 넓이가 반응형이 되도록 추가했어요.
- 페이지에 처음 들어오게 될 때, Loading 컴포넌트를 볼 수 있게 했어요.
- 입력값이 빈 string일 때, 칩을 선택하지 않은 경우에 대해서 조건문으로 undefined 처리를 추가했어요.
- 프로젝트 전체 조회 API에서 캐싱되지 않은 데이터를 가져올 때 마다, data가 undefined 상태가 되어서 깜박거리는 이슈가 있었어요!
따라서 UX를 개선하기 위해 `placeholderData: keepPreviousData` 를 추가했어요.
- empty view
- Loading 컴포넌트, url에 query string 제거, 검색창의 넓이 반응형이 되도록 추가
https://github.com/user-attachments/assets/a1072bcf-0056-4488-b25f-b5b2da908a6f
> fix: 프로젝트 필터링 결과 없을때 예외처리 및 반응형 작업

- src/components/makers/Notifier.tsx
- close #1548
- '35기 모집 중'멘트를 내리고, 진행 중 멘트를 추가했어요.
- '만든 사람들' 페이지에 5기 목록을 추가하는 작업이 필요해보입니다.
> fix: '만든 사람들' 페이지에서 35기 모집 멘트 내리기

- src/components/makers/Notifier.tsx
- close #1550
35기 모집은 2025년 1-2월 중에 진행될 예정이에요.
-> 36기 모집은~ 으로 수정했어요 
사소한 내용으로 PR 두번 올려서 죄송합니다!!!!! 머지 전에 한번 더 확인하기 ㅠ_ㅎ
> fix: makers 페이지 멘트 오타 수정

- package.json
- public/icons/icon-dots-vertical.svg
- src/api/endpoint/members/postBlockMember.ts
- src/api/endpoint/members/postReportMember.ts
- src/components/common/Modal/parts/index.tsx
- src/components/common/Modal/useConfirm.tsx
- src/components/feed/common/FeedDropdown.tsx
- src/components/feed/common/hooks/useReportFeed.ts
- src/components/feed/detail/FeedDetail.tsx
- src/components/feed/list/FeedListItems.tsx
- src/components/members/detail/ActivitySection/MemberDetail.tsx
- src/components/members/hooks/useBlockMember.ts
- src/components/members/hooks/useReportMember.ts
- yarn.lock
- close #1545 
- 게시글 신고 성공시, Toast mds로 변경
- 멤버 페이지의 드롭다운 메뉴로 신고/차단 UI 및 기능 추가 
- 신고/차단 API 및 hook 추가
- 모달의 Title, Descripction 을 반응형에 따라 font 수정
- FeedDropdown 컴포넌트에 커스텀 스타일링 가능하도록 style props 넣을 수 있도록 추가
- `@sopt-makers/icons` 패키지 추가
dropdownOpenStyle 상태를 추가해 반응형으로 모달 사이즈 수정
```typescript
onSuccess: async () => {
queryClient.invalidateQueries({
predicate: (query) => query.queryKey.some((key) => String(key).includes('community')),
});
```
차단 성공시 커뮤니티의 게시글, 댓글 등을 모두 다시 조회할 수 있도록 
위와 같은 로직을 통해서 `community`가 포함된 쿼리키들을 모두 `invalidate`해 다시 가져올 수 있도록 하였어요!
어떤 게시글이 차단된 멤버의 댓글이 포함되어 있는지를 모르고, 이를 다시 불러와야하기 때문에 이런 식으로 구현하였는데! 
혹시 더 효율적인 방법이 있는지 리뷰 부탁드립니다!
- 게시글 신고 성공
- 유저 신고
- 유저 신고 성공
- 유저 차단
- 유저 차단 성공
> feat: 게시글 신고 Toast mds로 변경 및 멤버 신고/차단 기능 추가

- src/components/common/Banner/WelcomeBanner/Welcome35.tsx
- src/components/common/Banner/WelcomeBanner/index.tsx
- src/components/common/Skeleton/index.tsx
- src/components/feed/list/CategorySkeleton.tsx
- src/components/feed/list/FeedList.tsx
- src/components/feed/list/FeedListItems.tsx
- src/components/feed/list/FeedSkeleton.tsx
- src/components/wordchain/WordchainEntry/WordChainEntry.tsx
- src/components/wordchain/WordchainEntry/WordchainSkeleton.tsx
- close #1569
Skeleton 공통 컴포넌트를 만들고, 이걸 조합해서 사용했습니다.
```ts
//Skeleton/index.ts
const Skeleton = ({ width, height, borderRadius, color, margin, children, ...props }: SkeletonProps) => {
return (
<StyledSkeleton width={width} height={height} borderRadius={borderRadius} margin={margin} color={color} {...props}>
{children}
</StyledSkeleton>
);
};
export default Skeleton;
const StyledSkeleton = styled.div<{
width?: number;
height?: number;
borderRadius?: number;
margin?: string;
color?: string;
}>`
margin: ${({ margin }) => margin && margin};
border-radius: ${({ borderRadius }) => borderRadius && `${borderRadius}px`};
background-color: ${({ color }) => color ?? colors.gray900};
width: ${({ width }) => (width ? `${width}px` : '100%')};
height: ${({ height }) => (height ? `${height}px` : …
```
> feat: 홈 로딩 스켈레톤 적용

- src/components/debug/SideBar.tsx
- src/components/projects/upload/form/fields/LinkField.tsx
- src/styles/reset.ts
- close #1567 
- 버튼에 적용되어있던 color 스타일을 지워주었어요. 
```
button,
[type='button'],
[type='reset'],
[type='submit'] {
appearance: button;
/* color: ${colors.gray10}; */
}
```
- reset.ts 의 스타일을 삭제 후 발생할 사이드 이펙트가 없는지, button 태그를 사용한 모든 컴포넌트를 훑었어요!
- 거의 다 버튼에 color값을 한 번 더 부여하여서, 큰 사이드 이펙트는 없더라구요..!
> fix: mds 와의 스타일 충돌 해결

- src/components/members/upload/schema.ts
- close #1578
- 프로필 업로드 시, 스킬 input은 필수 입력 항목인데, 이 인풋을 공백으로 입력하는 경우에도 프로필이 등록되는 오류가 있어서 해결했어요. 
- yup 내장기능을 이용, trim() 을 추가해주어서 공백이 있는 경우를 자르는 내용을 추가해주었어요.
> fix: skill이 공백인 경우 예외처리

- src/components/feed/common/utils.ts
- close #1580 
특수임원List를 업데이트해서, 현재 발생하고 있는 메이커스 임원진 표기 오류에 대해서 수정을 진행했습니다.
관련 쓰레드 링크: https://sopt-makers.slack.com/archives/C042T81PW80/p1727615461338179?thread_ts=1727614217.483179&cid=C042T81PW80
```
const 특수임원List = [
'메이커스 리드',
'메이커스 팀장',
'기획 파트장',
'디자인 파트장',
'웹 파트장',
'서버 파트장',
'안드로이드 파트장',
'iOS 파트장',
'운영 팀장',
'미디어 팀장',
'회장',
'부회장',
'총무',
] as const;
```
메이커스 팀장 직책을 추가했습니당
> fix: 커뮤니티 임원진 파트 표기 수정

- src/components/makers/Notifier.tsx
- close #1582
[관련 스레드](https://sopt-makers.slack.com/archives/C042T81PW80/p1727785987100689?thread_ts=1726912132.305009&cid=C042T81PW80)
makers 35기 -> 35기 makers로 표기 변경
> fix: makers 35기 -> 35기 makers로 표기 변경

- src/components/common/Banner/ActiveBannerSlot.tsx
- src/components/common/Banner/WelcomeBanner/Welcome35.tsx
- src/components/common/Banner/WelcomeBanner/index.tsx
- src/components/members/upload/complete/CardBack.tsx
- src/pages/members/complete.tsx
- close #1588
- ActiveBannerSlot에서 Welcome35 컴포넌트를 내리고, AdsBanner 컴포넌트를 삽입하였습니다.
- 환영 배너와 프로필 등록 완료 페이지에서 `is35`라는 변수를 반복적으로 사용하고 있었는데, 매번 워딩을 고쳐줘야하는게 불필요하다고 생각해서 `isLastGeneration`으로 변경하였습니다.
- 스켈레톤 작업시에 디자인 쪽에서 광고구좌까지 작업을 해주었었는데요! 광고구좌가 현재 서버에서 받아오는게 아니어서 스켈레톤이 불필요한 상황입니다. 혹시 나중에 서버에서 받아오는 방식으로 변경이 된다면 스켈레톤이 추가되어야 합니다.
https://github.com/user-attachments/assets/46c77691-cde0-4d6e-9f45-0039c90f52dc
> feat: 환영배너 내리기 및 프로필 등록 완료 기존 버전으로 롤백

- src/components/coffeechat/mediaQuery.ts
- src/components/coffeechat/upload/UploadHeader/index.stories.tsx
- src/components/coffeechat/upload/UploadHeader/index.tsx
- close #
- 커피챗 오픈/수정 뷰의 헤더를 구현했어요.
- 오픈인지 수정인지를 props로 받도록 구현했어요.
- mds callout 처음 써봤는데 편리하네요!
- 커피챗 뷰의 반응형 break point가 기존 뷰의 break point와는 좀 달라서, 따로 mediaQuery라는 파일을 만들어서 선언해주었습니다!
> feat: 커피챗 오픈 뷰 헤더 구현

- src/components/coffeechat/upload/ProgressBox/index.stories.tsx
- src/components/coffeechat/upload/ProgressBox/index.tsx
- close #
- 커피챗 오픈/수정 뷰의 progress 박스를 구현했어요.
- 커피챗 오픈인지 수정인지, 내 정보 수정 중인지, 커피챗 정보 수정 중인지에 대한 정보를 props로 받았어요.
- width를 100%로 구현했둔 상태에요! 추후에 progress 박스가 자식으로 들어가는 Layout 컴포넌트를 구축할 예정이에요.
> feat: 커피챗 입력 progress 박스 구현

- src/components/coffeechat/page/CoffeechatUploadPage.tsx
- src/components/coffeechat/page/layout/DesktopCoffeechatUploadLayout.tsx
- src/components/coffeechat/page/layout/MobileCoffeechatUploadLayout.tsx
- src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.tsx
- src/components/coffeechat/upload/ProgressBox/index.tsx
- src/components/common/form/TextFieldLineBreak/index.tsx
- src/pages/coffeechat/upload.tsx
- close #
- 업로드 페이지의 레이아웃을 구현했어요. 
- layout 폴더 안에 컴포넌트를 구현했고, main, aside, submitButton 각 컴포넌트를 children으로 받아서 구현했어요.
- 이제 업로드 쪽 로직 구현할 예정입니다! 로직 구현하면서 임시로 넣어둔 defaultForm은 지울게요!
> feat: 커피챗 업로드 뷰 데스크탑, 모바일 레이아웃 구현

- src/components/common/Banner/AdsBanner/AdsBox/index.tsx
- src/components/common/Banner/AdsBanner/constants/ads.ts
- src/components/common/Banner/AdsBanner/index.tsx
- close #1605
- 10.27 광고 구좌 변경했어요.
- 광고 반응형 css도 좀 수정했습니다.
- 불필요한 css 삭제
- 여러 이미지가 있는 경우 가장 height가 긴 이미지로 비율이 맞춰져서, 그보다 height이 짧은 이미지는 아래쪽에 여백이 생기는 문제가 있어 수정했어요.  
- 광고에 url이 없는 경우 분기처리도 추가해주었습니다.
- 처음 써보는데, `aspect-ratio: 340 / 168;` 이런식으로 이미지를 감싸는 박스에 직접 비율을 부여해주었습니다.
> feat: 10/27 광고 구좌 변경

- src/api/endpoint/members/getMemberCrew.ts
- src/components/members/detail/ActivitySection/MemberDetail.tsx
- src/components/members/detail/CareerSection/index.tsx
- src/components/members/detail/DetailinfoSection/index.stories.tsx
- src/components/members/detail/DetailinfoSection/index.tsx
- src/components/members/detail/GroupSection/index.stories.tsx
- src/components/members/detail/GroupSection/index.tsx
- src/components/members/detail/MessageSection/index.tsx
- src/components/members/detail/ProfileSection/index.stories.tsx
- src/components/members/detail/ProfileSection/index.tsx
- src/components/members/detail/ProjectSection/index.stories.tsx
- src/components/members/detail/ProjectSection/index.tsx
- close #1596 
멤버 프로필, 상세 정보, 프로젝트, 모임 정보를 컴포넌트로 분리했습니다!
CareerSection은 이미 컴포넌트로 분리되어 있어서, 스토리북에서 발생하는 오류만 수정했어요!
기존의 하나의 컴포넌트에 있던 뷰 로직을 분리했습니다.
상위에서 profile을 인자를 통해서 주면 각 Section에 해당하는 뷰에서 데이터를 보여줄 수 있도록 수정했습니다.
커피챗 페이지 상세조회 API 명세서에서 profile과 관련된 부분이 없어서, `useGetMemberProfileById`을 추가로 작성해서 프로필 정보를 가져와야할 것 같아요!
커피챗 상세 뷰에서 사용되는 부분은 아래 순서로 사용하시면 됩니다.
```typescript
<CareerSection
careers={profile.careers}
links={profile.links}
skill={profile.skill}
name={profile.name}
email={profile.email}
profileImage={profile.profileImage}
memberId={memberId}
isMine={profile.isMine}
/>
<DetailInfoSection profile={profile} />
<SoptActivitySection soptActivities={sortedSoptActivities} />
<ProjectSection profile={profile} memberId={memberId} meId={me?.id} />
```
MemberDetail.tsx에서 뷰들을 다 분리했어요! 
코드가 삭제된 부분이 …
> feat: 멤버 프로필, 상세 정보, 프로젝트, 모임 정보 컴포넌트 분리

- package.json
- src/components/members/common/select/OrderBySelect.tsx
- src/components/members/main/MemberCard/CoffeeChatButton.tsx
- src/components/members/main/MemberCard/MessageButton.tsx
- src/components/members/main/MemberCard/index.tsx
- src/components/members/main/MemberList/filters/MemberListFilter.tsx
- src/components/members/main/MemberList/filters/MemberListFilterSheet.tsx
- src/components/members/main/MemberList/filters/constants.ts
- src/components/members/main/MemberList/index.tsx
- src/components/members/main/hooks/useVisibleBadges.ts
- src/pages/members/index.tsx
- yarn.lock
- close #1597
생각했던 것보다 고난이 많은 작업이었습니다...
특히 mds에서 요구하는 데이터 구조와 type을 일치시키기 위해 기존 코드를 바꾸는 과정이 쉽지 않더라구요!
그리고 기존에 Member 탭 관련 코드 (특히 `<MemberList/>`)가 컴포넌트 분리가 안되어있고 많은 로직이 통합되어있었어요.
갈아엎기에는 시간이 부족해서, 이 부분은 **추후 다시 리팩토링**을 해야할 것 같습니다. (반드시..!)
그래서 코드가 지저분한데 이 부분은 양해 부탁드립니다 ㅠㅠ
그리고 프로필 카드에서 뱃지가 넘치면 생략처리 하는 부분이 있는데,
추가되어야하는 뱃지 크기를 동적으로 계산해주어야해서 상당히 복잡한 과정이었습니다.
ref로 width를 동적으로 계산하여 최대 들어갈 수 있는 뱃지를 확인하는 방식으로 구현을 했구요.
이 [트러블 슈팅 과정](https://simeunseo.notion.site/SP1-125599a6f0d280d78b3ede8e98ccac48?pvs=4)을 기록해놨는데 혹시 궁금하시면 읽어보셔요! (진짜 그냥 기록용으로 일단 적어놓은거라서 글이 엉망이긴합니다)
실제 구현 내용은 [useVisibleBadges.ts](https://github.com/sopt-makers/sopt-playground-frontend/pull/1600/files#diff-d5a14176fe3d710d4bb53b19bdae14f295335c4e975b946b58a851b3f6fb5f1c)확인 부탁드립니다
flag을 두어서 이 계산은 첫 마운트시에만 실행되도록 했고,
뱃지가 2개 이하인 경우는 …
> feat: 멤버 탭 커피챗 관련 수정 + mds 적용

- package.json
- src/api/endpoint/coffeechat/editCoffeechat.ts
- src/api/endpoint/coffeechat/uploadCoffeechat.ts
- src/components/coffeechat/page/CoffeechatUploadPage.tsx
- src/components/coffeechat/page/layout/DesktopCoffeechatUploadLayout.tsx
- src/components/coffeechat/page/layout/MobileCoffeechatUploadLayout.tsx
- src/components/coffeechat/upload/CoffeechatForm/ChipField/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/CoffeechatInfoForm/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.stories.tsx
- src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/constants.ts
- src/components/coffeechat/upload/CoffeechatForm/index.stories.tsx
- src/components/coffeechat/upload/CoffeechatForm/schema.ts
- src/components/coffeechat/upload/CoffeechatForm/types.ts
- src/components/coffeechat/upload/ProgressBox/index.tsx
- src/components/coffeechat/upload/UploadHeader/index.tsx
- src/components/common/form/TextFieldLineBreak/index.tsx
- src/constants/links.ts
- src/pages/coffeechat/edit/[id].tsx
- src/pages/coffeechat/upload.tsx
- yarn.lock
- close #
- 커피챗 오픈/수정 로직을 구현했어요.
> react-hook-form 사용
- yup으로 작성한 스키마의 에러 메시지가 자동으로 잡힐 수 있도록 methods의 handleSubmit을 사용하기 위해, 각 필드에 다 Controller를 붙여주었어요.
> 에러 발생 시, 인풋 필드 자동 포커싱
- 에러가 발생한 필드 중에서 가장 첫번째 필드로 포커싱되도록 스크롤 이벤트를 넣어주었습니다. (onError)
> 커피챗 업로드 여부를 묻는 모달 구현
- 모든 필드에 에러가 없다면 모달이 띄워지는 onOpen함수를 실행하도록 했어요, 원래는 mds의 open(option) useDialog 훅을 사용하려고 했는데, open(option) 함수가 submit 타입과 맞지 않는다는 에러가 나서 mds 다이얼로그 컴포넌트를 조합해 다이얼로그를 직접 구현해주었습니다.
- [수정완료됨] 필드에 넣을 수 있는 값이 백엔드와 싱크가 맞지 않아서 지금 400에러가 납니다...! 이 부분은 예준이에게 요청해두었어요. 
- ex. 프론트에서 주는 값 : 주니어 (0~3년) / 서버에서 받을 수 있는 값 : 주니어 
- 업로드 후 리패치 및 라우터 이동, 커피챗 수정 시의 데이터 패칭 작업이 TODO 로 남아있습니다! 이 부분은 커피챗 홈이랑 상세 페이지 연결하면서 채워둘게요!
- select v2가 다른 필드보다 위계가 뒤로 잡혀서 가려지는 현상이 있어 mds 측에 문의했어요!
- 로직 구현하면서도 스토리북에 이슈없도록 신경썼어요!
> feat: 커피챗 오픈/수정 로직 구현

- package.json
- src/api/endpoint/coffeechat/changeIsBlindCoffeechat.ts
- src/api/endpoint/coffeechat/getCoffeechatDetail.ts
- src/api/endpoint/coffeechat/postCoffeechatIsBlind.ts
- src/components/coffeechat/detail/CoffeechatContents/index.tsx
- src/components/coffeechat/detail/OpenerProfile/index.tsx
- src/components/coffeechat/detail/RegisterCoffeechatButton/index.tsx
- src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
- src/components/coffeechat/detail/index.tsx
- src/components/members/detail/CareerSection/index.tsx
- src/components/members/detail/ProjectSection/index.tsx
- src/constants/links.ts
- src/pages/coffeechat/[id].tsx
- yarn.lock
- close #1606
- 커피챗 상세 구현하기
- 페이지의 memberId를 읽어온 뒤, 해당값을 props로 내려주었어요. 분리한 컴포넌트마다 파라미터를 읽고 status 처리하는 게 불편할 것 같아서, 부모 컴포넌트에서 선언 후 props로 내려주었습니다.
- 커피챗 정보는 각 컴포넌트마다 훅으로 호출했습니다.
- mds 태그 이용했고, 도영이가 분리해준 공통 컴포넌트 잘 사용했습니다!
- 커피챗 프로필 쪽에서 데스크탑/모바일의 레이아웃이 다른 경우가 있어서 grid를 이용하여 위치를 조정해주었어요
> feat: 커피챗 상세 페이지 구현

- src/components/members/main/MemberList/index.tsx
- close #1622
handleSearchSubmit 함수에 blur() 추가 및 debounce 적용
검색 이후 blur되는 부분은 mds의 SearchField 컴포넌트에서 적용되어야 할 부분,,,? 같긴 한데 일단 저희 쪽에서 blur처리 하도록 수정했습니다!
debounce는 검색 이후 마지막 한글이 추가되서 queryString에 들어가서 Enter처리가 추가로 되지 않도록 적용했습니다.
[문제 상황]
input에 focus가 되어있을 시, 멤버 프로필 상세 페이지로 리다이렉트가 되지 않았습니다.
https://github.com/user-attachments/assets/e2e5c0a6-be18-4be4-b492-427d1fe59af9
[blur() 추가 및 debounce 미적용시]
https://github.com/user-attachments/assets/b9884957-ed24-4346-b188-14afccc46d10
[blur() 추가 및 debounce 적용 후]
https://github.com/user-attachments/assets/7ebec28a-5bf4-4b39-81bb-7cf4079ed1c6
> fix: 멤버 검색 이후 프로필로 들어가지지 않는 오류 수정

- src/components/members/main/MemberCard/index.tsx
- close #1642
커피챗 버튼 클릭시 멤버 카드의 link 동작을 막기 위해 e.preventDefault 추가
멤버 카드가 Link태그로 이루어져있어서, 그 내부에 있는 커피챗 버튼을 누를 때도 a태그의 href동작이 발생하게 됩니다.
이 동작을 방지하고 커피챗 상세로만 이동시키기 위해, 커피챗 버튼 onClick에 e.preventDefault()를 추가했습니다.
https://github.com/user-attachments/assets/9ded0388-ff30-481d-afe3-f8a5060ba0cf
https://github.com/user-attachments/assets/ed849053-1925-43c0-90bf-4895ff7cfcaf
> fix: 멤버 리스트 내 커피챗 뱃지 클릭시 멤버 카드 클릭과 함께 작동되는 문제 해결

- src/api/endpoint/coffeechat/getCoffeechatDetail.ts
- src/components/coffeechat/CoffeeChatCategory/index.tsx
- src/components/coffeechat/CoffeeRecentChatList/index.tsx
- src/components/coffeechat/Loading/index.tsx
- src/components/coffeechat/detail/OpenerProfile/index.tsx
- src/components/coffeechat/detail/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/ChipField/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/CoffeechatInfoForm/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/schema.ts
- src/components/coffeechat/upload/CoffeechatForm/types.ts
- src/components/common/form/TextFieldLineBreak/index.tsx
- src/pages/coffeechat/edit/[id].tsx
- src/pages/coffeechat/index.tsx
- src/pages/coffeechat/upload.tsx
- close #1645
- 커피챗 마무리 작업 진행했어요.
-  커피챗 상세 - 전화번호 없는 경우 폰 아이콘 노출되지 않도록 수정
-  커피챗 수정 - 상세 내용 불러오기
-  커피챗 오픈 - shift+enter disabled처리
-  커피챗 오픈 버튼 연결
-  리패치, 라우터 작업 
- TODO로 주석처리해둔 내용 반영했습니다!
- 로깅, 커피챗 id 없는 페이지 접속/내 커피챗 아닌 커피챗 수정 시도 시 예외처리 진행 예정이에요
> feat: 커피챗 마무리작업

- src/components/feed/page/layout/MobileCommunityLayout.tsx
- close #1663
디자인측 요청에 따라 모바일 gnb 영역과 끝말잇기 사이 여백을  10px -> 12px로 변경했습니다.
> fix: 모바일 gnb 하단 여백 수정

- src/components/coffeechat/CoffeeRecentChatList/index.tsx
- close #1659
- 커피챗 오픈하기 버튼 클릭 시의 모달을 추가해주었어요.
- mds의 dialog를 사용해주었습니다.
- 서버에서 hasCoffeechat boolean 값을 받기로 했어요, 이 부분 추후 반영예정입니다.
> feat: 커피챗 오픈하기 모달 추가

- src/components/coffeechat/detail/SeemoreSelect/index.tsx
- src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
- src/components/coffeechat/detail/index.tsx
- src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
- src/pages/coffeechat/edit/[id].tsx
- src/pages/coffeechat/upload.tsx
- close #1673 
- 커피챗 홈에 데이터가 즉시 반영되지 않는 문제 해결
- 상세 페이지 margin 값 수정
- invalidateQueries로 무효화했던 로직을, refetchQueries로 바로 리패치해주었어요.
- width 100%에 양옆 마진을 주었던 css에서 calc를 사용하는 방식으로 변경했어요.
> feat: 커피챗 qa

- src/components/members/main/MemberCard/index.tsx
- src/components/members/upload/complete/MemberCardOfMe.tsx
- close #1684
프로필 등록 완료 페이지 (/members/complete)에서 mds 이전 디자인을 사용하고있어서,
현재 변경된 멤버 탭과 일치하도록 mds 디자인을 입혀주었습니다
> feat: 프로필 등록 완료 페이지 내 멤버카드를 mds 디자인으로 변경

- src/components/coffeechat/constants/index.ts
- close #1687 
- 커피챗 홈에서 창업 중 필터링을 추가했어요
- 커피챗 홈 constant 라벨에 창업 중을 추가해주었어요.
- 커피챗 업로드 칩 라벨이랑 홈 필터링 라벨이랑 동일한 constants 사용하도록 리팩토링해볼게요 꼭
- 그리고 현재 셀렉트박스에 선택한 옵션이 defaultValue로는 들어가는데, 셀렉트박스 펼쳤을 때에는 체크가 안되어있는 것 같아요. 이부분도 수정 같이 진행하면 좋을 것 같습니다.
> feat: 창업 중 필터링 추가

- src/components/common/Banner/AdsBanner/AdsBox/index.tsx
- src/components/common/Banner/AdsBanner/constants/ads.ts
- src/components/common/Banner/AdsBanner/index.tsx
- close #1688
- 11월 11일~ 11월 26일 광고구좌 변경했어요.
- 멤버나 프로젝트에 접속했다가 다시 홈으로 가면 광고구좌가 없어진다는 제보를 받아서 해당 내용도 수정했어요. 
- 실제로 없어지는 것이 아니라, 다른 페이지에 갔다가 돌아오면 없어져있었는데, 컴포넌트 자체는 잘 생성이 되고 있어서, 강제로 광고구좌가 차지하는 자리에 스타일링을 주었어요. (width:100%, height:100%)
> feat: 광고 구좌 변경

- src/components/members/detail/ProfileSection/index.tsx
- src/components/members/main/MemberCard/index.tsx
- close #1691
- 모바일과 pc에서 같은 사이즈의 아이콘을 쓰고있는 문제가 있어서 모바일용 아이콘을 추가해주었습니다.
- '멤버 상세뷰'에서는 이전 아이콘을 그대로 쓰고있어서 이것또한 mds 아이콘으로 교체해주었습니다.
Responsive로 모바일 pc 나누어서 아이콘 삽입해주었습니다.
> fix: 멤버 프로필 기본 이미지 수정

- src/hooks/useImageUploader.ts
- close #1701 
- 이미지 업로드 훅(커뮤니티 이미지 업로드, 프로젝트 이미지 업로드에 사용)에 디바운싱을 적용했어요.
- 기존에 설치되어있던 lodash-es/debounce를 사용했어요.
- 이미지 업로드 로직에 debounce를 감싸주었습니다.
- 잘 한 게 맞나... 하는 의문이 들어서... 편하게 의견 주세요!!
- 생각했던 것보다 이미지 미리보기가 뜨는 과정이 느리더라고요(기존부터). 이 부분은 로딩 추가하거나, 리사이징하는 로직 추가해보겠습니다..!
> refactor: 커뮤니티 글쓰기 이미지 디바운싱

- src/components/coffeechat/upload/CoffeechatForm/types.ts
- src/pages/coffeechat/edit/[id].tsx
- close #1710
- 커피챗 커리어의 타입을 수정했어요.
- string[] 타입을 삭제했어요
- 업로드 시, 배열 타입인지에 따라 string으로 가공하는 로직을 삭제했어요
- 기존 커리어의 경우, 배열을 받는 칩 섹션 공통 컴포넌트를 사용했는데, 디자인 개편으로 칩 섹션이 아닌 드롭다운/바텀시트를 사용하게 되면서, 배열 타입 정의가 불필요해졌어요!
> refactor: 커피챗 커리어 타입 수정

- src/components/coffeechat/upload/CoffeechatForm/BottomSheetSelect/index.tsx
- close #1721
BottomSheetSelect가 가로스크롤 내에서 사용될 경우 스크롤 영역에 갇혀 보이지 않는 문제가 발생했습니다.
따라서 바텀시트를 `<Portal/>`을 이용해 portal에서 렌더링되도록 수정하였습니다.
> fix: bottomsheetselect를 portal로 렌더링

- src/components/resolution/read/hooks/useImageDownload.ts
- src/pages/test/image/index.tsx
- close #1724
이미지 다운로드 테스트를 위해 현우님이 만들어주신 페이지가
모바일에서 접속시 아무것도 뜨지 않는 문제가 발생했습니다.
이미지 다운로드 훅에서 document객체에 접근하는데,
기존 코드에서 window.onload 이벤트로 브라우저 환경을 확인하는 방식이 제대로 작동하지 않았던 것 같습니다
따라서 이를 제거하고 이미지 다운로드 훅 내에서 window 객체를 확인하는 방식으로 수정하였습니다.
> fix: 이미지 다운로드 테스트용 페이지 모바일에서 안뜨는 현상 해결

- src/components/coffeechat/detail/OpenerProfile/index.tsx
- close #1718 
저번에 커피챗 mds 적용에서, default icon에 대한 부분이 추가 디자인 수정이 있어서 이슈 파서 진행했습니다
간단하게, 기존 user default icon에 대해서 mds를 적용했어요
MDS에서 svg 비율이 figma랑 약간 다르게 설정되어 있는거같은데.. 크리티컬한 이슈는 아니여서 일단 수동으로 맞춰서 진행했습니다. 나중에 플폼팀분들한테 한번 노티드릴게요!
> feat: 커피챗 상세 default 이미지 mds 적용

- .github/workflows/build.yml
- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- src/components/members/detail/DetailinfoSection/index.tsx
- close #1742
아주 간단한 픽스 사항입니다~~
1. 개인 정보 영역 비어있어도 섹션 박스가 표시됨
- 조건 분기가 잘못되어있어서 수정
2. 모바일에서 활동지역 폰트 크기가 큼
> fix: 멤버 프로필 상세 UI 문제 해결

- src/components/mySoptReport/MyReport/index.tsx
- src/components/mySoptReport/ReportCard/CardHeader/index.tsx
- src/components/mySoptReport/index.tsx
- close #1729 
dev서버에서 이미지 저장이 정상적으로 동작함에 따라, ${PLAYGROUND_ORIGIN} 에서 제공하던 url을 변경합니다.
또한, Safari에서 toPng()가 background-image 또는 <img>를 올바르게 변환하지 못함에 따라 html2canvas로 변경하여 Safari에서도 안정적으로 이미지를 다운 받을 수 있도록 변경하였습니다.
> Fix: 이미지 저장시 bg url 변경

- src/components/common/HomePopup/index.tsx
- close #1788 
팝업에서 TimecapsopSubmitModal의 누락된 onSuccess, 누락된 PlaygroundGuideModal을 추가했습니다.
banner의 index와 같은 구조로 추가했습니다.
> fix: 빌드 에러 해결 및 가이드 모달 추가

- src/api/endpoint/resolution/deleteTimecapsop.ts
- src/api/endpoint/resolution/postResolution.ts
- src/components/common/Banner/WelcomeBanner/index.tsx
- src/components/common/BottomSheet/ModalBottomSheet.tsx
- src/components/common/HomePopup/index.tsx
- src/components/resolution/constants.ts
- src/components/resolution/delete/index.tsx
- src/components/resolution/submit/PlaygroundGuideModal.tsx
- src/components/resolution/submit/TimecapsopSubmitModal.tsx
- src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
- src/components/resolution/submit/useConfirmResolution.ts
- src/pages/members/complete.tsx
- close #1787
- 서버와 논의 후 기존의 value(한글)이 아닌 key(영어)에 해당 하는 값으로 요청을 보내는 것으로 수정하기로 결정해서 해당 부분을 수정했어요
- Tag 인터페이스에 key 필드 추가하여 TAG 상수 리스트 수정했어요.
- TimecapsopSubmitModal에서 selectedTag 상태와 onClickTag 함수 로직을 enum key 기준으로 처리하도록 변경했어요.
- 타임캡솝 메세지를 제출할 때 기존에는 메세지 확인 모달이 떴지만 해당 모달이 안뜨고 바로 api 요청이 실행되도록 수정했어요.
https://github.com/user-attachments/assets/ae825a8e-fb58-4c61-af79-c569ad02a367
> fix: 타임캡솝 QA 반영

- src/components/eventLogger/events.ts
- src/components/resolution/submit/PlaygroundGuideModal.tsx
- src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
- src/components/resolution/submit/constants/cards.tsx
- close #1796 
- 타입캡솝 작성 후 뜨는 다른기능 이동 모달에서 기능 카드들을 클릭했을 때 클릭 이벤트를 로깅하도록 추가했습니다.
- handle 이벤트에 로깅 추가했습니다.
> feat: 다른기능이동 모달 클릭 이벤트 로깅

- src/components/common/Banner/WelcomeBanner/index.tsx
- src/components/eventLogger/events.ts
- src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
- src/components/resolution/submit/useConfirmResolution.ts
- src/pages/members/complete.tsx
- close #1795
- 새롭게 정의된 amplitude event로 수정했어요.
- ![image](https://github.com/user-attachments/assets/46a00a3b-e7d2-4ef4-86d7-6b32c878d1f1)
- 홈팝업의 경우 기존과 같아서 따로 수정하지 않았어요!
- 타임캡솝 모달에서 모바일 버전에 터치 스크롤이 원활하지 않던 것도 함께 수정했어요.
- `overflow-y: auto;` 와 `-webkit-overflow-scrolling: touch;`를 모달의 최상위 스크롤 가능 요소에 적용해서 콘텐츠가 요소의 높이를 초과할 경우 스크롤이 잘 동작하도록 했어요.
- 모바일 환경에서 textArea를 선택했을때 가상 키보드에 의해서 textArea가 가려지는 현상은 별도의 처리가 필요할 것 같습니다!
> feat: 타임캡솝 amplitude 이벤트 등록 

- src/components/coffeechat/CoffeeChatCard/index.tsx
- src/components/coffeechat/CoffeeChatCategory/index.tsx
- src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx
- src/components/coffeechat/CoffeeRecentChatList/index.tsx
- src/components/eventLogger/events.ts
- src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
- src/pages/feed/[id].tsx
- close #1807
- 타임캡솝 모달의 3월을 4월로 라이팅 수정했어요
- 필요하지 않은 로깅을 삭제했어요(openToCoffeechat삭제 - openCoffeechat 존재)
- recentCoffeechatCard 로깅 삭제 및 coffeeChatCard channel property 를 추가했어요.
- sendCoffeeChat 로깅에 receiverId, senderId property를 추가했어요.
- 기존에 recentCoffeechatCard와 coffeeChatCard가 나눠져 있고 recentCoffeechatCard클릭시 coffeeChatCard도 함께 로깅되고 있었어서 recentCoffeechatCard을 삭제하고 coffeeChatCard의 property로 channel을 추가해서 `basic`, `recent`를 통해서 최근 항목에 있는  커피챗을 클릭한 것인지 구분이 가능하도록 했어요.
> [FIX] 앰플리튜드 수정 작업

- .storybook/main.ts
- src/components/feed/list/FeedUrlCard.stories.tsx
- src/components/feed/list/FeedUrlCard.tsx
- close #1812
- FeedUrlCard 컴포넌트를 구현했어요
- 기존 스토리북 설정에서는 autodocs 옵션을 true로 수정했어요
- 기본형식의 경우 반응형일때(768px 이하 )`flex-direction: column;`이 적용되어야 하지만 상세보기에서의 FeedUrlCard는
반응형과 관계없이 `flex-direction: column;`이 기본값이라서 `isDetailFeedCard`라는 boolean값을 props에 추가해서 판별 할 수 있도록 하였어요.
- 아직 api구현이 완료되지 않아서 해당 컴포넌트를 뷰자체에는 넣어두지 않았어요 ui는 스토리북으로 확인 부탁드려요!
- 기존 스토리북 설정에서는 autodocs: false로 되어 있어서, docs를 추가해도 문서 탭이 보이지 않았어요. 그래서 해당 옵션을 true로 수정해 문서 탭이 표시되도록 설정했어요. 스토리북은 하나의 컴포넌트를 독립적인 문서처럼 보여줄 수 있기 때문에 각 스토리에 간단한 설명을 덧붙여주는 것이 컴포넌트를 이해하는 데 큰 도움이 된다고 생각해요. 스토리를 추가할 때 설명을 간단히 적어주면 팀원들이 컴포넌트를 빠르게 파악하는 데 도움이 될 것 같은데 이에 대해서는 어떻게 생각하시나요?
- 아직은 솝티클 데이터가 없어서 컴포넌트의 props를 다 옵셔널로 해두었는데 이는 추후에 수정하도록 하겠습니다!
> feat: 커뮤니티에 솝티클 컴포넌트 구현

- src/components/common/Banner/ActiveBannerSlot.tsx
- src/pages/index.tsx
- src/pages/members/complete.tsx
- close #1818
- 환영배너가 아닌 광고배너가 나타나도록 수정했어요
- 홈팝업 주석처리를 했어요
- members/complete에서 isResolutionOpen를 false처리 했어요
이전기수 선생님들께서 환영배너 on/off처리를 간편하게 만들어주셔서 쉽게 수정했습니다!!
> feat: 타임캡솝 및 팝업 제거

- src/components/common/HomePopup/index.tsx
- src/components/feed/list/CategorySelect.tsx
- src/components/feed/list/FeedCategoryTooltip/index.tsx
- src/components/feed/list/FeedCategoryTooltip/useTooltip.ts
- close #1811
메인 페이지에서 솝티클 탭이 있으면 툴팁이 자동노출되도록 컴포넌트 추가했습니다.
~~카테고리에서 솝티클이 있으면 ref를 지정해서 해당하는 위치에 툴팁이 자동노출되도록 구현했습니다.
사용자의 이벤트(scroll. click, keydown)이 일어나면 툴팁이 사라지도록 했습니다
이때 홈에 팝업이 뜨는 경우 팝업에서의 클릭은 감지하지 않도록 팝업 버튼에 `e.stopPropagation();`를 추가했습니다.~~
+) 수정된 기능 명세 반영했습니다.
수정된 기능 명세를 반영하여, 툴팁에 제목과 닫기 버튼이 추가되었습니다.
이 요소들을 사용하는 쪽에서 유연하게 조합할 수 있도록 툴팁은 합성 컴포넌트 패턴으로 작성하였습니다.
기존에는 사용자 이벤트(스크롤, 클릭, 키보드 입력 등)를 감지하여 툴팁을 자동으로 닫았으나,
현재는 닫기 버튼 클릭 또는 솝티클 카테고리 선택 시 툴팁이 닫히고, 해당 날짜에 다시 노출되지 않도록 변경되었습니다.
이를 위해 useTooltip 훅에 closeTooltipForToday 함수를 추가하고, 닫기 버튼 및 카테고리 선택 영역에서 이 함수를 onClick으로 연결했습니다.
툴팁의 닫은 날짜는 localStorage에 저장되며, 향후 다양한 위치에서 툴팁을 사용할 가능성을 고려하여, 스토리지 키를 외부에서 인자로 주입받도록 설계하였습니다.
더 좋은 방법이 있다면 편하게 말씀해주세요!
일단 api가 아직 수정되지 않아서 쿼리 데브툴에서 솝티클 탭을 추가했을 때 화면입니다!
> feat: 솝티클 툴팁 구현

- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/Category/CategoryHeader/index.tsx
- src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
- src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
- src/components/feed/upload/CheckboxFormItem/BlindWriterWarning/index.tsx
- src/components/feed/upload/CodeUploadButton/index.tsx
- src/components/feed/upload/ImageUploadButton/index.tsx
- src/components/feed/upload/Input/LinkInput/index.tsx
- src/components/feed/upload/hooks/useLinkValidator.ts
- src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
- close #1823 
- LinkInput 컴포넌트를 만들었어요
- 링크 유효성을 검사하는 로직을 `useLinkValidator`로 만들었어요.
- LinkInput 컴포넌트를 솝티클 업로드 영역에 분기처리로 추가했어요.
- LinkInput에서 앤터키를 눌렀을 때 form 제출이 되는 걸 막고자 onKeyDown 이벤트에 e.preventDefault()를 통해 기본 동작을 막았어요
- 링크의 유효성 검사는 "https://"로 시작하는지를 정규식을 통해 검사했어요
- ` const isSopticle = parentCategory?.id === SOPTICLE_CATEGORY_ID;` 해당 로직으로 솝트클인지 확인하고
`{isSopticle ? <>  ... </> : <> ... </>}` 이와 같이 솝티클인 경우와 아닌 경우를 나눠서 커뮤니티 업로드 구좌를 구현했어요
- 업로드 페이지에 카테고리를 선택하는 토글에서 솝티클 카테고리를 가장 뒤에 두기 위해서 
` const sortedCategories = categories ? [...categories.slice(1), categories[0]] : [];` 이와 같이 가장 앞에 있던 카테고리를 가장 뒤로 보냈어요.
-  가장 앞에 있던 카테고리를 가장 뒤로 보내는 연산을 메모이제이션 하는 것이 좋을지 아니면 간단한 연산이니 현재 로직을 그대로 둘지에 대해서 고민중이에요. 이에 대한 의견이 궁금합니다!
> feat: 솝티클 업로드 UI

- src/components/blog/Success.tsx
- src/components/eventLogger/events.ts
- src/pages/blog/index.tsx
- close #1831
활동후기 업로드를 할 때, submit에 `reviewUpload`로 로깅 추가했습니다.
활동후기 보러가기를 클릭할 때, `reviewGoToHomepage`로 로깅 추가했습니다. 
활동후기 업로드 페이지로 이동할 때 로깅을 추가해야 하는데,
헤더에 로깅이 들어가서 헤더 PR에 함께 추가하든,
헤더를 배포하고 다시 추가하는 방법을 선택해야 할 것 같습니다.
헤더를 기다리고 여기서 다시 작업하면 작업이 밀릴 것 같은데
헤더 PR에 로깅도 같이 올리고 이 PR을 머지해도 괜찮을까요??
> feat: 활동후기 업로드 로깅 추가

- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/Input/LinkInput/index.tsx
- src/components/feed/upload/hooks/useUploadFeedData.ts
- src/components/feed/upload/types.ts
- src/pages/feed/edit/[id].tsx
- src/pages/feed/upload.tsx
- close #1833
- 솝티클 생성 및 수정 로직 요청에 link 필드를 추가했어요.
- 기존에는 솝티클을 생성하거나 수정할 때 content 필드에 url을 담아 보내면 백엔드에서 해당 url을 크롤링해 title과 content를 채우고, sopticleUrl이라는 필드를 추가해 응답해주는 구조였어요.
하지만 이 구조에서는 게시글을 수정할 때 원래의 url이 아닌 크롤링된 content 값이 content 필드에 채워져 있어 사용자가 실제 url을 확인하거나 수정하는 데 어려움이 발생했고, 결국 수정 시에는 다시 URL을 별도로 감지해서 content에 넣어 보내야 하는 불편함이 있었어요.
이 문제를 해결하기 위해, 백엔드에 요청드려 솝티클 생성 및 수정 시 url을 명확히 전달할 수 있도록 link 필드를 별도로 추가하는 방향으로 구조를 개선했어요!
- 백엔드에서 content가 비워져 있을경우 에러메세지를 보내서 
```
...(isSopticle // / 솝티클이면 content와 title 초기화
? { content: 'content', title: '' }
: {}),
```
이와 같이 카테고리가 sopticle일 경우  content: 'content'를 넣는 방식으로 처리를 해두었어요.
> fix: 솝티클 수정로직 변경

- src/api/endpoint/members/getMemberProperty.ts
- src/components/eventLogger/controllers/amplitude.ts
- src/components/eventLogger/events.ts
- src/components/eventLogger/providers/AmplitudeProvider.tsx
- src/components/feed/common/utils.ts
- src/components/feed/detail/FeedDetailContent.tsx
- src/components/feed/list/FeedList.tsx
- src/components/feed/list/FeedListItems.tsx
- src/components/feed/page/FeedHomePage.tsx
- src/pages/feed/upload.tsx
- close #1827
- click-feedCard 이벤트에 category 이벤트 프로퍼티를 추가했어요
- impression-feedCard 이벤트에 category 이벤트 프로퍼티를 추가했어요
- click-feedLike, feedUnlike 이벤트에 category 이벤트 프로퍼티를 추가했어요
- feedDetail에서는 feedLike이벤트 로깅이 붙어있지 않았어서 디테일 페이지에서도 feedLike이벤트 로깅을 추가했어요
- submitCommunity 이벤트에 category 이벤트 프로퍼티를 추가했어요
- user property에 uploadSopticleCount, uploadReviewCount 를 추가했어요.
- major, organization, job에 한해서 타입에  `nullable`을 추가했어요! 아래 에러가 property받아올 때 해당 항목들에 nullable이 안되어 있어서 나는 에러였다,, 그래서 아마 이때까지 major, organization, job에 null이 포함된 유저는 user property가 안들어갔을 거 같아요,,
- ubmitCommunity 이벤트에 category 이벤트 프로퍼티를 추가하는 과정에서 categoryId로 categoryName을 가져와야 했어서 
categoryIdNameMap 객체를 추가해서 빠르게 조회하여 카테고리 이름을 가져오도록 했어요!
- 36th SP1 new Event Properties에 해당 하는 내용은 모두 해놓은 상태이고(해당 pr) 36th SP1 new User Properties와 관련해서는 슬랙에 …
> feat: sp1관련 앰플리튜드 로깅 추가

- src/components/members/upload/FormSection/Basic/index.tsx
- src/components/members/upload/FormSection/Career.tsx
- close #1843
- 아래와 같이 기존에 모바일 환경에서 input이 뚱뚱해지는 현상을 수정했어요.
- mds를 사용하고 있어서 이와 mds와 관련한 문제인 것 처럼 보이는데 TextField를 감싸는 스타일에 height를 지정하고 선택자를 통해서 input의 height를 100%로 해주니 해결되어서 이와 같은 방식으로 해결했어요
> fix: 모바일 프로필 수정 input 디자인 오류 해결

- src/components/feed/common/utils.ts
- src/components/feed/detail/FeedDetailContent.tsx
- src/components/feed/list/FeedListItems.tsx
- close #1876
- 파트talk, 홍보 카테고리에 한해서는 상세 카테고리가 존재해서 전체 카테고리가 존재했어요. 그런데 해당 전체 카테고리에 한해서만 좋아요를 눌러도 좋아요가 바로 반영되지 않는 문제(낙관적 업데이트 문제)를 해결했어요
- 기존 로직에서는 allPostsQueryKey: useGetPostsInfiniteQuery.getKey('')처럼 전체 포스트의 쿼리키를 빈 문자열로 설정했어요.
그래서 ['posts', '']라는 쿼리Key만 낙관적으로 업데이트되고 있었어요. 하지만 자식 카테고리에 속한 게시글은, 실제로 부모 카테고리 ID를 기준으로 쿼리Key가 캐싱되기 때문에 ['posts', '']로는 해당 데이터를 찾아 업데이트할 수 없어 좋아요 상태가 반영되지 않았습니다.
- 이 문제를 해결하기 위해 getParentCategoryId 함수를 만들어 자식 카테고리는 부모 ID를, 자식이 없는 경우는 빈 문자열을 반환하도록 하고 allPostsQueryKey를 실제 캐싱된 쿼리Key와 일치하도록 수정했어요. 그 결과 낙관적 업데이트가 정상적으로 작동하게 되었습니다.
> fix: 파트톡, 홍보 카테고리의 좋아요 이슈

- src/api/endpoint/feed/postVote.ts
- src/components/feed/common/hooks/useDeleteFeed.ts
- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/list/FeedList.tsx
- src/components/feed/page/FeedUploadPage.tsx
- src/components/feed/upload/votePreview/index.stories.tsx
- src/components/feed/upload/votePreview/index.tsx
- src/components/vote/RadioBox.tsx
- src/components/vote/index.tsx
- src/pages/feed/edit/[id].tsx
- close #1882
- 게시글을 수정하는 경우에는 투표항목을 수정할 수 없도록 처리했어요
- get으로 받아오는 투표정보와 post를 위해 필요한 투표정보가 달라서 게시글 수정할 때 데이터 형태를 변환해서 전달했어요
- 데이터가 바뀔때만 계산하도록 useMemo로 만들었어요
```tsx
const voteForForm = useMemo(() => {
if (!data) return null;
const voteData = data.posts.vote;
return voteData ? { isMultiple: voteData.isMultiple, voteOptions: voteData.options.map((o) => o.content) } : null;
}, [data]);
```
- 업로드화면에서 isEdit일 경우 투표 Preview폼을 disable처리 했어요
> feat: 투표 수정 막기 로직 구현

- src/components/feed/upload/hooks/useUploadFeedData.ts
- close #1898
- 기존에는 질문 카테고리 선택시 익명이 활성화되고 다른 카테고리 선택시 익명이 비활성화되도록 구현하였는데 기획의 요청에 의해서
익명이 한번 선택된다면 익명을 직접 해제하기 전까지 익명이 풀리지 않도록 로직을 처리했어요(솝티클 카테고리 한정 익명 비활성화)
> fix: 게시글 생성 시 익명 상태 관리 수정

- src/components/feed/common/utils/parseMention.tsx
- src/components/feed/detail/DetailFeedCard.tsx
- src/components/feed/home/RecentArea/RecentCard.tsx
- src/components/feed/list/FeedCard.tsx
- close #1902
멘션을 클릭하면 해당 멤버페이지로 이동하도록 추가했습니다.
&nbsp;를 공백으로 변경해주었습니다.
근본적으로 &nbsp가 붙지 않고 넘기는 방법을 찾아야 하는데,
아직 찾지 못해서 일단 직접 파싱해서 뷰에 보여줄 때 공백으로 변경해서 보이도록 했습니다.ㅜㅜ
> feat: 멘션 기능 처리 추가

- src/components/members/main/MemberList/index.tsx
- close #1956
- member.activities가 빈 배열일 때 발생할 수 있는 런타임 에러 방지
- useMemo에서 activities 기본값을 빈 배열로 설정하여 한번에 처리
> fix: member activities 빈배열 처리

- src/components/members/main/MemberList/filters/constants.ts
- src/components/members/main/MemberList/index.tsx
- close #1970 
백엔드에서 filter로 파트 정보를 보내면 enum으로 인증 서버로 보내도록 로직을 수정해주셔서 filter로 보내도록 변경했어요.
maker가 아닌 makers로 enum을 관리하고 있어서 오탈자를 수정했어요.
> fix: 플그 be 수정된 part 로직에 맞게 filter로 파트 정보 요청

- src/components/feed/common/utils.ts
- src/components/feed/home/PopularArea/index.tsx
- src/components/members/main/MemberList/index.tsx
- close #1975 
- 실시간 인기글의 경우 따로 서버로부터 categoryId를 받지 않고 자식 카테고리 이름으로 받게 되는 경우가 생겨 기존 로직으로 
부모 카테고리 id를 찾지못하는 상황이었습니다. 따라서 categoryIdNameMap을 통해 찾는 방식을 제거하고 string에 해당 하는 카테고리명을 넣으면 부모 카테고리에 해당하는 id에 해당 하는 값을 반환하는 util함수를 만들었어요
> fix: 실시간 인기글 categoryId undefined에러 수정

- src/components/members/main/MemberList/filters/constants.ts
- src/components/members/main/MemberList/index.tsx
- close #1993
- 정렬에 "멤버 전체"를 추가했습니다
- 검색에 빈문자열 입력시 검색 필터링을 제거했습니다
- 
- 멤버 전체를 클릭하면 정렬이 되지 않도록 url 파라미터를 비워줬습니다.
- 멤버 검색이 onSubmit으로 동작해서 빈 문자열 입력 후 엔터를 누르면 이벤트가 발생하지 않습니다. 따라서 검색어가 변경될 때 빈문자열이면 검색 필터링을 제거하도록 했습니다.
> refactor: 멤버 필터링 초기화 추가

- src/components/members/upload/FormSection/Tmi/index.tsx
- close #2004 
textarea에서 변경된 값을 인식할 수 있도록 controller로 제어하도록 고쳤어요
mbti를 변경하면서 텍스트를 변경하면 해당 값으로 변경이 되지만, 그냥 텍스트만 변경하면 요청이 가지 않았어요
해당 필드 변경이 isDirty 상태를 변경하지 않고 있었고, textarea에서 전체적으로 발생하고 있었어요
textarea의 변경사항을 정확하게 추적할 수 있도록 controller로 제어하도록 변경했어요
> fix: 프로필 수정 textarea 요청 안가는 이슈 해결
